--------------------------------------------------------
--  DDL for View DM_AMS_TRANSCODE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DM_AMS_TRANSCODE" ("GR_ID", "SAP_ASSET_CODE", "GR_DATE", "COUNTRY_CODE", "SAP_VENDOR", "MFG_SR_NO", "AMS_ASSET_ID", "SAP_PO_NO", "SAP_PO_DATE", "REMARKS", "ASSET_DESCRIPTION", "AR_ID", "SR_NO", "ASSET_CLASS", "SUB_ASSET_TYPE", "LOCATION", "TICB_BAR_CODE", "BAR_CODE_PRINTED", "REQUESTER_DEPT", "REQUESTED_BY", "TECH_GROUP_ID") AS 
  SELECT "GR_ID","SAP_ASSET_CODE","GR_DATE","COUNTRY_CODE","SAP_VENDOR","MFG_SR_NO","AMS_ASSET_ID","SAP_PO_NO","SAP_PO_DATE","REMARKS","ASSET_DESCRIPTION","AR_ID","SR_NO","ASSET_CLASS","SUB_ASSET_TYPE","LOCATION","TICB_BAR_CODE","BAR_CODE_PRINTED","REQUESTER_DEPT","REQUESTED_BY","TECH_GROUP_ID" FROM AMS.AS_VU_ASSETS_VALID
;
