--------------------------------------------------------
--  DDL for Function CHK_KALLO_POST
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "TIMECURR"."CHK_KALLO_POST" 
(
  P_YYMM IN VARCHAR2  
) RETURN NUMBER AS 
V_NORMAL INT(5);
V_OT INT(5);
MBOOL INT(1);
BEGIN
  SELECT COUNT(*) INTO V_NORMAL FROM TIME_DAILY WHERE PROJNO LIKE  '09050%' AND  YYMM = P_YYMM AND
 EMPNO||YYMM||ASSIGN NOT IN (SELECT EMPNO||YYMM||ASSIGN FROM TIME_MAST WHERE YYMM = P_YYMM AND NVL(POSTED,0) = 1 );
 SELECT COUNT(*) INTO V_OT FROM TIME_OT WHERE PROJNO LIKE  '09050%' AND  YYMM = P_YYMM AND
 EMPNO||YYMM||ASSIGN NOT IN (SELECT EMPNO||YYMM||ASSIGN FROM TIME_MAST WHERE YYMM = P_YYMM AND NVL(POSTED,0) = 1 );
 IF V_NORMAL = 0 AND V_OT = 0 THEN
    MBOOL := 0;
 ELSE
    MBOOL := 1;
 END IF;
  RETURN MBOOL;
END ;

/
