--------------------------------------------------------
--  Constraints for Table DB_AUTOBOOK_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "DESK_BOOK"."DB_AUTOBOOK_PREFERENCES" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_AUTOBOOK_PREFERENCES" ADD CONSTRAINT "DB_AUTOBOOK_PREFERENCES_PK" PRIMARY KEY ("EMPNO")
  USING INDEX "DESK_BOOK"."DB_AUTOBOOK_PREFERENCES_PK"  ENABLE;
  ALTER TABLE "DESK_BOOK"."DB_AUTOBOOK_PREFERENCES" ADD CONSTRAINT "DB_AUTOBOOK_PREFERENCES_UK1" UNIQUE ("KEY_ID")
  USING INDEX "DESK_BOOK"."DB_AUTOBOOK_PREFERENCES_UK1"  ENABLE;
