--------------------------------------------------------
--  Constraints for Table DB_DESK_DATE_LOCKING
--------------------------------------------------------

  ALTER TABLE "DESK_BOOK"."DB_DESK_DATE_LOCKING" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_DESK_DATE_LOCKING" MODIFY ("ATTENDANCE_DATE" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_DESK_DATE_LOCKING" ADD CONSTRAINT "DB_DESK_DATE_LOCKING_PK" PRIMARY KEY ("DESKID", "ATTENDANCE_DATE")
  USING INDEX "DESK_BOOK"."DB_DESK_DATE_LOCKING_PK"  ENABLE;
