--------------------------------------------------------
--  Constraints for Table DB_DESK_BOOKINGS
--------------------------------------------------------

  ALTER TABLE "DESK_BOOK"."DB_DESK_BOOKINGS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_DESK_BOOKINGS" MODIFY ("ATTENDANCE_DATE" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_DESK_BOOKINGS" ADD CONSTRAINT "DB_DESK_BOOKINGS_PK" PRIMARY KEY ("EMPNO", "ATTENDANCE_DATE")
  USING INDEX "DESK_BOOK"."DB_DESK_BOOKINGS_PK"  ENABLE;
