--------------------------------------------------------
--  Constraints for Table DB_MAP_OFFICE_SHIFTS
--------------------------------------------------------

  ALTER TABLE "DESK_BOOK"."DB_MAP_OFFICE_SHIFTS" MODIFY ("OFFICE_ID" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_MAP_OFFICE_SHIFTS" MODIFY ("SHIFTCODE" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_MAP_OFFICE_SHIFTS" ADD CONSTRAINT "DB_MAP_OFFICE_SHIFTS_PK" PRIMARY KEY ("OFFICE_ID", "SHIFTCODE")
  USING INDEX "DESK_BOOK"."DB_MAP_OFFICE_SHIFTS_PK"  ENABLE;
