--------------------------------------------------------
--  Constraints for Table DB_TAG_OBJ_MAPPING
--------------------------------------------------------

  ALTER TABLE "DESK_BOOK"."DB_TAG_OBJ_MAPPING" MODIFY ("KEY_ID" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_OBJ_MAPPING" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_OBJ_MAPPING" MODIFY ("OBJ_ID" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_OBJ_MAPPING" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_OBJ_MAPPING" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_OBJ_MAPPING" ADD CONSTRAINT "DB_TAG_OBJ_MAPPING_UK1" UNIQUE ("KEY_ID")
  USING INDEX  ENABLE;
