--------------------------------------------------------
--  Constraints for Table DB_TAG_MASTER
--------------------------------------------------------

  ALTER TABLE "DESK_BOOK"."DB_TAG_MASTER" MODIFY ("KEY_ID" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_MASTER" MODIFY ("TAG_NAME" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_MASTER" MODIFY ("TAG_DESC" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_MASTER" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "DESK_BOOK"."DB_TAG_MASTER" ADD CONSTRAINT "DB_TAG_MASTER_UK1" UNIQUE ("KEY_ID")
  USING INDEX  ENABLE;
