--------------------------------------------------------
--  Constraints for Table OFB_USER_ACTIONS
--------------------------------------------------------

  ALTER TABLE "TCMPL_HR"."OFB_USER_ACTIONS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_USER_ACTIONS" MODIFY ("ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_USER_ACTIONS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_USER_ACTIONS" ADD CONSTRAINT "OFB_USER_ACTIONS_UK1" UNIQUE ("EMPNO", "ROLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "TCMPL_HR"."OFB_USER_ACTIONS" ADD CONSTRAINT "OFB_USER_ACTIONS_PK" PRIMARY KEY ("EMPNO", "ACTION_ID")
  USING INDEX  ENABLE;
