--------------------------------------------------------
--  Constraints for Table OFB_ROLE_ACTIONS
--------------------------------------------------------

  ALTER TABLE "TCMPL_HR"."OFB_ROLE_ACTIONS" MODIFY ("ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_ROLE_ACTIONS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_ROLE_ACTIONS" MODIFY ("ACTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_ROLE_ACTIONS" MODIFY ("ACTION_DESC" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_ROLE_ACTIONS" MODIFY ("IS_ACTION_FOR_HOD" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_ROLE_ACTIONS" ADD CONSTRAINT "OFB_ROLE_ACTIONS_PK" PRIMARY KEY ("ACTION_ID")
  USING INDEX  ENABLE;
