--------------------------------------------------------
--  Constraints for Table OFB_EMP_EXIT_APPROVALS
--------------------------------------------------------

  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" MODIFY ("ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" ADD CONSTRAINT "OFB_EMP_EXIT_APPROVALS_PK" PRIMARY KEY ("EMPNO", "ACTION_ID")
  USING INDEX  ENABLE;
