--------------------------------------------------------
--  Constraints for Table OFB_EMP_EXITS
--------------------------------------------------------

  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXITS" MODIFY ("RESIGNATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXITS" MODIFY ("END_BY_DATE" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXITS" MODIFY ("PARENT" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXITS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXITS" MODIFY ("RELIEVING_DATE" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."OFB_EMP_EXITS" ADD CONSTRAINT "OFB_EMP_EXIT_PK" PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE;
