--------------------------------------------------------
--  DDL for Trigger TRIGGER7
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "COMMONMASTERS"."TRIGGER7" 
BEFORE INSERT OR UPDATE OF EMPNO,DESK_NO,MAIL_ID,PHONE_OFF,FAX,VOIP,MOBILE_RES,PHONE_RES,MOBILE_OFF,R_ADD_1,R_ADD_2,R_ADD_3,R_ADD_4,PAN,PASSPORT_NO,ISSUE_DATE,EXPIRY_DATE,PASSPORT_ISSUED_AT,BLOOD_GROUP,DOMAIN_LOGIN,USER_UPDATE,SURNAME,NAME,FATHER_NAME,P_ADD_1,P_ADD_2,P_ADD_3,P_ADD_4,F_ADD_1,F_ADD_2,F_ADD_3,F_ADD_4,REF_PERSON_NAME,REF_PERSON_PHONE,LOCATION,PUNCH_CARD_STATUS,DOB,FATHER_OCCUPATION,INSR_DETAILS,CO_BUS,PICK_UP_POINT,R_PINCODE,P_PINCODE,F_PINCODE,MARITAL_STATUS,RELIGION,SURNAME_OLD,FATHER_NAME_OLD,NAME_OLD,P_ADD_1_OLD,P_ADD_2_OLD,P_ADD_3_OLD,P_ADD_4_OLD,P_PINCODE_OLD,INCLUDE_DAD_HUSB_NAME,NO_DAD_HUSB_IN_NAME ON EMP_DETAILS 
REFERENCING OLD AS Old NEW AS New 
FOR EACH ROW 
BEGIN
  :New.modified_on := sysdate;
END;

/
ALTER TRIGGER "COMMONMASTERS"."TRIGGER7" ENABLE;
