

  CREATE TABLE "TIMECURR"."JOB_RESPONSIBLE_TYPE_JOB_DEPT" 
   (	"JOB_RESPONSIBLE_ROLE_ID" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"TYPE_OF_JOB" VARCHAR2(10 BYTE), 
	"COSTCODE" CHAR(4 BYTE), 
	 CONSTRAINT "JOB_RESPONSIBLE_TYPE_JOB__UK1" UNIQUE ("TYPE_OF_JOB", "COSTCODE", "JOB_RESPONSIBLE_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "JOB_RESPONSIBLE_TYPE_JOB__FK1" FOREIGN KEY ("COSTCODE")
	  REFERENCES "TIMECURR"."COSTMAST" ("COSTCODE") ENABLE, 
	 CONSTRAINT "JOB_RESPONSIBLE_TYPE_JOB__FK2" FOREIGN KEY ("JOB_RESPONSIBLE_ROLE_ID")
	  REFERENCES "TIMECURR"."JOB_RESPONSIBLE_ROLES_MST" ("JOB_RESPONSIBLE_ROLE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

