
  CREATE TABLE "TIMECURR"."JOB_APPROVALS_LOG" 
   (	"PROJNO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"REVISION" NUMBER(2,0) NOT NULL ENABLE, 
	"APPROVAL_DATE" DATE NOT NULL ENABLE, 
	"JOB_RESPONSIBLE_ROLE_ID" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"PRINCIPAL_EMPNO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"APPROVED_BY_EMPNO" CHAR(5 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

  CREATE INDEX "TIMECURR"."JOB_APPROVALS_ON_BEHALF_LOGS_INDEX1" ON "TIMECURR"."JOB_APPROVALS_LOG" ("PROJNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

