
  CREATE TABLE "TIMECURR"."JOB_UPDATE_PM_JS_BULK_LOG" 
   (	"PROJNO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"EMPNO_FROM" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"EMPNO_TO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

