

  CREATE TABLE "TIMECURR"."JOB_RESPONSIBLE_ROLES_DEFAULTS" 
   (	"JOB_RESPONSIBLE_ROLE_ID" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"EMPNO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"IS_DEFAULT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "JOB_RESPONSIBLE_ROLES_DEFA_PK" PRIMARY KEY ("JOB_RESPONSIBLE_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "JOB_RESPONSIBLE_ROLES_DEF_FK1" FOREIGN KEY ("JOB_RESPONSIBLE_ROLE_ID")
	  REFERENCES "TIMECURR"."JOB_RESPONSIBLE_ROLES_MST" ("JOB_RESPONSIBLE_ROLE_ID") ENABLE, 
	 CONSTRAINT "JOB_RESPONSIBLE_ROLES_DEF_FK2" FOREIGN KEY ("EMPNO")
	  REFERENCES "TIMECURR"."EMPLMAST" ("EMPNO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "TIMECURR"."JOB_RESPONSIBLE_ROLES_DEFAULTS"."IS_DEFAULT" IS '1 or 0';

