
  CREATE TABLE "TIMECURR"."JOB_RESPONSIBLE_TYPE_JOB_REQRD" 
   (	"JOB_RESPONSIBLE_ROLE_ID" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"TYPE_OF_JOB" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "JOB_RESPONSIBLE_TYPE_JOB_REQRD_PK" PRIMARY KEY ("JOB_RESPONSIBLE_ROLE_ID", "TYPE_OF_JOB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "JOB_RESPONSIBLE_TYPE_JOB_REQRD_FK1" FOREIGN KEY ("JOB_RESPONSIBLE_ROLE_ID")
	  REFERENCES "TIMECURR"."JOB_RESPONSIBLE_ROLES_MST" ("JOB_RESPONSIBLE_ROLE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

