
  CREATE TABLE "TIMECURR"."RAP_COSTCODE_GROUP_COSTCODES" 
   (	"COSTCODE_ID" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"COSTCODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(4 BYTE), 
	"ORDERBY" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"GROUP_ID" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "RAP_COSTCODE_GROUP_COSTCODES_PK" PRIMARY KEY ("COSTCODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "RAP_COSTCODE_GROUP_COSTCODES_UK1" UNIQUE ("COSTCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "RAP_COSTCODE_GROUP_COSTCODES_UK2" UNIQUE ("COSTCODE", "ORDERBY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "RAP_COSTCODE_GROUP_COSTCODES_FK1" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "TIMECURR"."RAP_COSTCODE_GROUP" ("GROUP_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

