
  CREATE TABLE "TIMECURR"."RAP_OSC_MASTER" 
   (	"OSCM_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"OSCM_DATE" DATE NOT NULL ENABLE, 
	"PROJNO5" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"OSCM_VENDOR" CHAR(3 BYTE) NOT NULL ENABLE, 
	"OSCM_TYPE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"PO_NUMBER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PO_DATE" DATE NOT NULL ENABLE, 
	"PO_AMT" NUMBER(13,2) NOT NULL ENABLE, 
	"LOCK_ORIG_BUDGET" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODIFIED_BY" CHAR(5 BYTE) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	"CUR_PO_AMT" NUMBER(13,2), 
	 CONSTRAINT "RAP_OUTSIDE_SUBCONTRACT_MA_PK" PRIMARY KEY ("OSCM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "RAP_OSC_MASTER_UK1" UNIQUE ("PROJNO5", "OSCM_VENDOR", "PO_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "RAP_OUTSIDE_SUBCONTRACT_M_FK1" FOREIGN KEY ("OSCM_VENDOR")
	  REFERENCES "TIMECURR"."SUBCONTRACTMAST" ("SUBCONTRACT") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "TIMECURR"."RAP_OSC_MASTER"."OSCM_TYPE" IS 'MONO or MULTI';

