
  CREATE TABLE "TIMECURR"."RAP_OSC_DETAIL" 
   (	"OSCD_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"OSCM_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"COSTCODE" CHAR(4 BYTE) NOT NULL ENABLE, 
	"MODIFIED_BY" CHAR(5 BYTE) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	"ADDED_ON" DATE, 
	 CONSTRAINT "RAP_OUTSIDE_SUBCONTRACT_DE_PK" PRIMARY KEY ("OSCD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "RAP_OUTSIDE_SUBCONTRACT_D_UK1" UNIQUE ("OSCM_ID", "COSTCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "RAP_OUTSIDE_SUBCONTRACT_D_FK2" FOREIGN KEY ("COSTCODE")
	  REFERENCES "TIMECURR"."COSTMAST" ("COSTCODE") ENABLE, 
	 CONSTRAINT "RAP_OSC_DETAIL_FK1" FOREIGN KEY ("OSCM_ID")
	  REFERENCES "TIMECURR"."RAP_OSC_MASTER" ("OSCM_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

