CREATE TABLE "TIMECURR"."TS_COSTCODE_GROUP_COSTCODE" 
("COSTCODE_GROUP_ID" CHAR(5 BYTE) NOT NULL ENABLE, 
"COSTCODE" CHAR(4 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "TS_COSTCODE_GROUP_COSTCODE_PK" PRIMARY KEY ("COSTCODE_GROUP_ID", "COSTCODE"),
 CONSTRAINT "TS_COSTCODE_GROUP_COSTCOD_FK1" FOREIGN KEY ("COSTCODE") REFERENCES "TIMECURR"."COSTMAST" ("COSTCODE") ENABLE)