CREATE TABLE "TIMECURR"."TS_COSTCODE_GROUP" 
("COSTCODE_GROUP_ID" CHAR(5 BYTE) NOT NULL ENABLE, 
"COSTCODE_GROUP_NAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
"COSTCODE_GROUP_DESC" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "TS_COSTCODE_GROUP_PK" PRIMARY KEY ("COSTCODE_GROUP_ID"));