
  CREATE TABLE "TIMECURR"."TS_OSC_MHRS_DETAIL" 
   (	"OSCD_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"OSCM_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PROJNO" CHAR(7 BYTE) NOT NULL ENABLE, 
	"WPCODE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"ACTIVITY" CHAR(7 BYTE) NOT NULL ENABLE, 
	"HOURS" NUMBER(8,2) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	"MODIFIED_BY" CHAR(5 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TS_OSC_MRS_DETAIL_PK" PRIMARY KEY ("OSCD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "TS_OSC_MHRS_DETAIL_UK1" UNIQUE ("PROJNO", "WPCODE", "ACTIVITY", "OSCM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "TS_OSC_MRS_DETAIL_FK1" FOREIGN KEY ("OSCM_ID")
	  REFERENCES "TIMECURR"."TS_OSC_MHRS_MASTER" ("OSCM_ID") ENABLE, 
	 CONSTRAINT "TS_OSC_MRS_DETAIL_FK2" FOREIGN KEY ("PROJNO")
	  REFERENCES "TIMECURR"."PROJMAST" ("PROJNO") ENABLE, 
	 CONSTRAINT "TS_OSC_MRS_DETAIL_FK3" FOREIGN KEY ("WPCODE")
	  REFERENCES "TIMECURR"."TIME_WPCODE" ("WPCODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

