--------------------------------------------------------
--  DDL for View VU_COSTMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DESK_BOOK"."VU_COSTMAST" ("COSTCODE", "NAME", "ABBR", "HOD", "HOD_ABBR", "DY_HOD", "NOOFEMPS", "COSTGROUP", "GROUPS", "TM01_GRP", "TMA_GRP", "COST_TYPE", "ACTIVITY", "GROUP_CHART", "COSTGRP", "ITALIAN_NAME", "BU", "CHANGED_NEMPS", "INOFFICE", "SECRETARY", "COMP", "ACTIVE", "SDATE", "EDATE", "PHASE", "SAPCC", "CLOSED", "PARENT_COSTCODE", "NOOFCONS", "TCM_CC", "TCM_ACT_PH", "TCM_PAS_PH", "TCM_CC_DESC", "PO") AS 
  select "COSTCODE","NAME","ABBR","HOD","HOD_ABBR","DY_HOD","NOOFEMPS","COSTGROUP","GROUPS","TM01_GRP","TMA_GRP","COST_TYPE","ACTIVITY","GROUP_CHART","COSTGRP","ITALIAN_NAME","BU","CHANGED_NEMPS","INOFFICE","SECRETARY","COMP","ACTIVE","SDATE","EDATE","PHASE","SAPCC","CLOSED","PARENT_COSTCODE","NOOFCONS","TCM_CC","TCM_ACT_PH","TCM_PAS_PH","TCM_CC_DESC","PO" from commonmasters.costmast
;
