--------------------------------------------------------
--  DDL for View VU_PROJMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DESK_BOOK"."VU_PROJMAST" ("PROJNO", "NAME", "CLIENT", "SDATE", "EXPTCDATE", "CDATE", "COSTCODE", "PRJMNGR", "PRJDYMNGR", "ORIGINAL", "REVISED", "PROJTYPE", "TYPE", "TMAGRP", "ABBR", "ACTIVE", "TCM_JOBS", "TCM_GRP", "PRJOPER", "TCMNO", "REIMB_JOB", "EOU_JOB", "EXCL_BILLING", "EXCL_DELTA_BILLING", "BU", "PROJ_NO", "BLOCK_BOOKING", "CO", "PHASE_RULE", "NEWCOSTCODE", "REVCDATE", "BLOCK_OT", "CCAPPRL", "SAP_WBS", "PREVCO") AS 
  select "PROJNO","NAME","CLIENT","SDATE","EXPTCDATE","CDATE","COSTCODE","PRJMNGR","PRJDYMNGR","ORIGINAL","REVISED","PROJTYPE","TYPE","TMAGRP","ABBR","ACTIVE","TCM_JOBS","TCM_GRP","PRJOPER","TCMNO","REIMB_JOB","EOU_JOB","EXCL_BILLING","EXCL_DELTA_BILLING","BU","PROJ_NO","BLOCK_BOOKING","CO","PHASE_RULE","NEWCOSTCODE","REVCDATE","BLOCK_OT","CCAPPRL","SAP_WBS","PREVCO" from commonmasters.projmast
;
