--------------------------------------------------------
--  Ref Constraints for Table EMP_DETAILS
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS" ADD CONSTRAINT "FK_BUS_CODE" FOREIGN KEY ("CO_BUS")
	  REFERENCES "COMMONMASTERS"."EMP_BUS_MASTER" ("CODE") ENABLE NOVALIDATE;
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS" ADD CONSTRAINT "FK_PC_STAT" FOREIGN KEY ("PUNCH_CARD_STATUS")
	  REFERENCES "COMMONMASTERS"."EMP_PUNCH_CARD_STATUS" ("CODE") ENABLE NOVALIDATE;
