--------------------------------------------------------
--  Ref Constraints for Table EMP_FAMILY_LOG
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_FAMILY_LOG" ADD CONSTRAINT "FK_OCCUPATION_LOG" FOREIGN KEY ("OCCUPATION")
	  REFERENCES "COMMONMASTERS"."EMP_OCCUPATION" ("CODE") ENABLE NOVALIDATE;
  ALTER TABLE "COMMONMASTERS"."EMP_FAMILY_LOG" ADD CONSTRAINT "FK_RELATION_LOG" FOREIGN KEY ("RELATION")
	  REFERENCES "COMMONMASTERS"."EMP_RELATION_MAST" ("CODE") ENABLE NOVALIDATE;
