REM INSERTING into SELFSERVICE.SS_LEAVETYPE
SET DEFINE OFF;
Insert into SELFSERVICE.SS_LEAVETYPE (DESCRIPTION,LEAVETYPE) values ('Optional Holiday','OH');
Insert into SELFSERVICE.SS_LEAVETYPE (DESCRIPTION,LEAVETYPE) values ('Privilege Leave','PL');
Insert into SELFSERVICE.SS_LEAVETYPE (DESCRIPTION,LEAVETYPE) values ('Sick Leave','SL');
Insert into SELFSERVICE.SS_LEAVETYPE (DESCRIPTION,LEAVETYPE) values ('Excess Leave','EX');
Insert into SELFSERVICE.SS_LEAVETYPE (DESCRIPTION,LEAVETYPE) values ('Casual Leave','CL');
Insert into SELFSERVICE.SS_LEAVETYPE (DESCRIPTION,LEAVETYPE) values ('Compensatory Off','CO');
Insert into SELFSERVICE.SS_LEAVETYPE (DESCRIPTION,LEAVETYPE) values ('Leave for Expatriates (Consultants)','LV');
