REM INSERTING into SELFSERVICE.SS_ONDUTYMAST
SET DEFINE OFF;
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('RW','Remote Work (Work from Home)',-1,8);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('DP','Deputation',3,6);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('TR','On Tour',3,7);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('OD','On Duty',2,5);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('MP','Missed Punch (Single)',2,2);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('LE','Late Come (Upto 1 Hrs)',2,1);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('SL','Short Lv (LateRepo & EarlyGo)',2,3);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('IO','Forgetting Punch Card',2,4);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('HT','Home Town',-1,9);
Insert into SELFSERVICE.SS_ONDUTYMAST (TYPE,DESCRIPTION,TABLETAG,SORT_ORDER) values ('VS','Visa Problem On Duty',-1,10);
