--------------------------------------------------------
--  DDL for Table ATTEND_PLAN_WK
--------------------------------------------------------

  CREATE TABLE "ITINV_STK"."ATTEND_PLAN_WK" 
   (	"KEYID" VARCHAR2(10), 
	"EMPNO" CHAR(5), 
	"WK_START_DATE" DATE, 
	"WK_END_DATE" DATE, 
	"MON" NUMBER(1,0) DEFAULT 0, 
	"TUE" NUMBER(1,0) DEFAULT 0, 
	"WED" NUMBER(1,0) DEFAULT 0, 
	"THU" NUMBER(1,0) DEFAULT 0, 
	"FRI" NUMBER(1,0) DEFAULT 0, 
	"SAT" NUMBER(1,0) DEFAULT 0, 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"CREATED_BY" CHAR(5), 
	"CREATED_ON" DATE
   ) ;

   COMMENT ON COLUMN "ITINV_STK"."ATTEND_PLAN_WK"."MON" IS '0 or 1';
   COMMENT ON COLUMN "ITINV_STK"."ATTEND_PLAN_WK"."TUE" IS '0 or 1';
   COMMENT ON COLUMN "ITINV_STK"."ATTEND_PLAN_WK"."WED" IS '0 or 1';
   COMMENT ON COLUMN "ITINV_STK"."ATTEND_PLAN_WK"."THU" IS '0 or 1';
   COMMENT ON COLUMN "ITINV_STK"."ATTEND_PLAN_WK"."FRI" IS '0 or 1';
   COMMENT ON COLUMN "ITINV_STK"."ATTEND_PLAN_WK"."SAT" IS '0 or 1';
   COMMENT ON COLUMN "ITINV_STK"."ATTEND_PLAN_WK"."ISDELETED" IS '0 or 1';
