--------------------------------------------------------
--  DDL for Table ATTEND_SHIFT_BUS_PICKUP
--------------------------------------------------------

  CREATE TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" 
   (	"EMPNO" CHAR(5), 
	"SHIFT" CHAR(2), 
	"BUS" CHAR(1), 
	"STATION" VARCHAR2(30), 
	"SIDE" CHAR(4), 
	"CITY_LANDMARK" VARCHAR2(100), 
	"TASKFORCE" VARCHAR2(40), 
	"SPECIAL_NOTE" VARCHAR2(200), 
	"EMP_PLAN" NUMBER(1,0) DEFAULT 0, 
	"CREATED_BY" CHAR(5), 
	"CREATED_ON" DATE, 
	"MODELER" NUMBER(1,0) DEFAULT 0
   ) ;

   COMMENT ON COLUMN "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP"."SIDE" IS 'EAST or WEST';
   COMMENT ON COLUMN "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP"."MODELER" IS '0 or 1';
