--------------------------------------------------------
--  DDL for Table DIST_LAPTOP_REQUEST
--------------------------------------------------------

  CREATE TABLE "ITINV_STK"."DIST_LAPTOP_REQUEST" 
   (	"EMPNO" CHAR(5), 
	"SW_REQUIRED" VARCHAR2(1000), 
	"WINDOWS_VER" VARCHAR2(2), 
	"REQ_DATE" DATE, 
	"REQ_BY" VARCHAR2(5), 
	"IT_ACTION_CODE" VARCHAR2(2), 
	"IT_ACTION_BY" VARCHAR2(5), 
	"IT_REMARKS" VARCHAR2(100), 
	"IT_ACTION_DATE" DATE, 
	"LAPTOP_AMS_ID" VARCHAR2(30), 
	"HEADPHONE_QRCODE" VARCHAR2(30), 
	"DOCKING_QRCODE" VARCHAR2(30), 
	"ISSUE_DATE" DATE, 
	"IS_REQUESTED" VARCHAR2(2), 
	"REASON_4_NOPICKUP" NUMBER(2,0), 
	"PICKUPREASON_MODIFIED_BY" VARCHAR2(5), 
	"PICKUPREASON_MODIFIED_ON" DATE
   ) ;
