--------------------------------------------------------
--  Constraints for Table ATTEND_PLAN_WK_TEMP_30
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("ISDELETED" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("SAT" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("FRI" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("THU" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("WED" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("TUE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("MON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("WK_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("WK_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_30" MODIFY ("KEYID" NOT NULL ENABLE);
