--------------------------------------------------------
--  Constraints for Table ATTEND_PLAN_WK_TEMP_10
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("ISDELETED" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("SAT" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("FRI" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("THU" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("WED" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("TUE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("MON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("WK_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("WK_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_TEMP_10" MODIFY ("KEYID" NOT NULL ENABLE);
