--------------------------------------------------------
--  Constraints for Table ATTEND_PLAN_DATA_TEMP
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("BUS" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("SHIFT" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("MODELER" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("ATTENDING_OFFICE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("ASSIGN" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_DATA_TEMP" ADD CONSTRAINT "ATTEND_PLAN_DATA_TEMP_PK" PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE;
