--------------------------------------------------------
--  Constraints for Table ATTEND_PLAN_WK_JOB_LOG
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_JOB_LOG" MODIFY ("JOB_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_JOB_LOG" MODIFY ("REMARKS" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_JOB_LOG" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_JOB_LOG" MODIFY ("WK_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_JOB_LOG" MODIFY ("WK_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK_JOB_LOG" MODIFY ("KEYID" NOT NULL ENABLE);
