--------------------------------------------------------
--  Constraints for Table ATTEND_SHIFT_BUS_PICKUP
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" MODIFY ("MODELER" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" MODIFY ("EMP_PLAN" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" MODIFY ("SHIFT" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_SHIFT_BUS_PICKUP" ADD CONSTRAINT "ATTEND_SHIFT_BUS_PICKUP_PK" PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE;
