--------------------------------------------------------
--  Constraints for Table ATTEND_OFFICE_SEAT_CAP
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ATTEND_OFFICE_SEAT_CAP" MODIFY ("WK_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_OFFICE_SEAT_CAP" MODIFY ("WK_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_OFFICE_SEAT_CAP" MODIFY ("ALLT_OCU" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_OFFICE_SEAT_CAP" MODIFY ("TOT_SEAT_AVL" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_OFFICE_SEAT_CAP" MODIFY ("TOT_SEAT_CAP" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_OFFICE_SEAT_CAP" MODIFY ("OFFICE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_OFFICE_SEAT_CAP" ADD CONSTRAINT "ATTEND_OFFICE_SEAT_CAP_PK" PRIMARY KEY ("OFFICE", "WK_START_DATE")
  USING INDEX  ENABLE;
