--------------------------------------------------------
--  Constraints for Table ATTEND_PLAN_WK
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" ADD CONSTRAINT "UK_ATTEND_PLAN_WK" UNIQUE ("EMPNO", "WK_START_DATE", "WK_END_DATE")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("ISDELETED" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("SAT" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("FRI" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("THU" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("WED" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("TUE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("MON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("WK_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("WK_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" MODIFY ("KEYID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ATTEND_PLAN_WK" ADD CONSTRAINT "PK_ATTEND_PLAN_WK" PRIMARY KEY ("KEYID")
  USING INDEX  ENABLE;
