--------------------------------------------------------
--  Constraints for Table BB_EMP_PC_LOG
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."BB_EMP_PC_LOG" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."BB_EMP_PC_LOG" MODIFY ("DELETE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."BB_EMP_PC_LOG" MODIFY ("PCNAME" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."BB_EMP_PC_LOG" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."BB_EMP_PC_LOG" MODIFY ("KEY_ID" NOT NULL ENABLE);
