--------------------------------------------------------
--  Constraints for Table DIST_LAPTOP_ALREADY_ISSUED
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."DIST_LAPTOP_ALREADY_ISSUED" MODIFY ("LAPTOP_AMS_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."DIST_LAPTOP_ALREADY_ISSUED" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."DIST_LAPTOP_ALREADY_ISSUED" ADD CONSTRAINT "DIST_LAPTOP_ALREADY_ISSUED_PK" PRIMARY KEY ("EMPNO", "LAPTOP_AMS_ID")
  USING INDEX  ENABLE;
