--------------------------------------------------------
--  Constraints for Table DIST_LAPTOP_ALREADY_ISSUED_LOG
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."DIST_LAPTOP_ALREADY_ISSUED_LOG" MODIFY ("LAPTOP_AMS_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."DIST_LAPTOP_ALREADY_ISSUED_LOG" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."DIST_LAPTOP_ALREADY_ISSUED_LOG" ADD CONSTRAINT "DIST_LAPTOP_ALREADY_ISSU_CHK1" CHECK (is_issued in (1,0)) ENABLE;
