--------------------------------------------------------
--  Constraints for Table PH_COUNTRY_MASTER
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."PH_COUNTRY_MASTER" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."PH_COUNTRY_MASTER" MODIFY ("DIAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."PH_COUNTRY_MASTER" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."PH_COUNTRY_MASTER" ADD CONSTRAINT "PH_COUNTRY_MASTER_UK1" UNIQUE ("DIAL_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."PH_COUNTRY_MASTER" ADD CONSTRAINT "PH_COUNTRY_MASTER_PK" PRIMARY KEY ("COUNTRY_CODE")
  USING INDEX  ENABLE;
