--------------------------------------------------------
--  Constraints for Table ST_ITEM_REQUESTS
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ST_ITEM_REQUESTS" MODIFY ("REMARKS" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_ITEM_REQUESTS" MODIFY ("REQUESTER_ENGR" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_ITEM_REQUESTS" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_ITEM_REQUESTS" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_ITEM_REQUESTS" MODIFY ("ITEM_CODE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_ITEM_REQUESTS" ADD CONSTRAINT "ST_ITEM_REQUESTS_PK" PRIMARY KEY ("REQ_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."ST_ITEM_REQUESTS" ADD CONSTRAINT "REQ_CHECK_QTY" CHECK (qty > 0) ENABLE;
