--------------------------------------------------------
--  Constraints for Table ST_IT_EMP_LIST
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ST_IT_EMP_LIST" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_IT_EMP_LIST" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_IT_EMP_LIST" ADD CONSTRAINT "ST_IT_EMP_LIST_UK1" UNIQUE ("EMPNO")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."ST_IT_EMP_LIST" ADD CONSTRAINT "ST_IT_EMP_LIST_PK" PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."ST_IT_EMP_LIST" ADD CONSTRAINT "ST_IT_EMP_LIST_CK2" CHECK (length(nvl(trim(empno),' ')) = 5) ENABLE;
  ALTER TABLE "ITINV_STK"."ST_IT_EMP_LIST" ADD CONSTRAINT "ST_IT_EMP_LIST_CK1" CHECK (empno = upper(empno)) ENABLE;
  ALTER TABLE "ITINV_STK"."ST_IT_EMP_LIST" ADD CONSTRAINT "ST_IT_EMP_LIST_CHK1" CHECK (nvl(status,8) = 0 Or nvl(status,9) =1) ENABLE;
