--------------------------------------------------------
--  Constraints for Table ST_REF_TYPE_MASTER
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ST_REF_TYPE_MASTER" MODIFY ("REF_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_REF_TYPE_MASTER" MODIFY ("REF_TYPE_DESC" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_REF_TYPE_MASTER" ADD CONSTRAINT "ST_REF_TYPE_MASTER_UK1" UNIQUE ("REF_TYPE_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."ST_REF_TYPE_MASTER" ADD CONSTRAINT "ST_REF_TYPE_MASTER_PK" PRIMARY KEY ("REF_TYPE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."ST_REF_TYPE_MASTER" ADD CONSTRAINT "ST_REF_TYPE_MASTER_CON" CHECK ( "REF_TYPE_CODE" = upper(ref_type_code)) ENABLE;
  ALTER TABLE "ITINV_STK"."ST_REF_TYPE_MASTER" ADD CONSTRAINT "ST_REF_TYPE_MASTER_CHK1" CHECK (nvl(trim(ref_type_code),' ') <> ' ') ENABLE;
