--------------------------------------------------------
--  Constraints for Table ST_STOCK_IN
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."ST_STOCK_IN" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_STOCK_IN" MODIFY ("REMARKS" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_STOCK_IN" MODIFY ("IN_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_STOCK_IN" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."ST_STOCK_IN" ADD CONSTRAINT "ST_STOCK_IN_PK" PRIMARY KEY ("IN_ID")
  USING INDEX  ENABLE;
