--------------------------------------------------------
--  Constraints for Table STK_SUB_ITEM_TYPE
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."STK_SUB_ITEM_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUB_ITEM_TYPE" MODIFY ("S_SUB_ITEM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUB_ITEM_TYPE" MODIFY ("ITEM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUB_ITEM_TYPE" MODIFY ("SKEY_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUB_ITEM_TYPE" ADD CONSTRAINT "STK_SUB_ITEM_TYPE_PK" PRIMARY KEY ("SKEY_ID")
  USING INDEX  ENABLE;
