--------------------------------------------------------
--  Constraints for Table STK_USERID_EMPNO
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" ADD CONSTRAINT "USERID-EMPNO_UK1" UNIQUE ("EMPNO")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" MODIFY ("INSERT_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" MODIFY ("OFFICE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USERID_EMPNO" MODIFY ("EMPNO" NOT NULL ENABLE);
