--------------------------------------------------------
--  Constraints for Table STK_STOCK_IN
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("REMARK" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("SUB_ITEM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("ITEM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("STK_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" MODIFY ("KEY_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_STOCK_IN" ADD CONSTRAINT "STK_STOCK_IN_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX  ENABLE;
