--------------------------------------------------------
--  Constraints for Table STK_SUSPENSE_TABLE
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" MODIFY ("SUBITEM" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" MODIFY ("ITEMTYPE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" MODIFY ("NOW_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" MODIFY ("CLOSING_KEY_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_SUSPENSE_TABLE" ADD CONSTRAINT "STK_CLOSING_TABLE_PK" PRIMARY KEY ("CLOSING_KEY_ID")
  USING INDEX  ENABLE;
