--------------------------------------------------------
--  Constraints for Table STK_REQUEST
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."STK_REQUEST" MODIFY ("ISSUED" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_REQUEST" MODIFY ("REQUESTED_DATE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_REQUEST" MODIFY ("REQUESTED_BY" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_REQUEST" MODIFY ("REMARK_TXT" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_REQUEST" MODIFY ("SUB_ITEM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_REQUEST" MODIFY ("ITEM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_REQUEST" MODIFY ("TICKET_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_REQUEST" ADD CONSTRAINT "STK_REQUEST_PK" PRIMARY KEY ("TICKET_ID")
  USING INDEX  ENABLE;
