--------------------------------------------------------
--  Constraints for Table STK_USER_RIGHTS
--------------------------------------------------------

  ALTER TABLE "ITINV_STK"."STK_USER_RIGHTS" MODIFY ("KEY_ID" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USER_RIGHTS" MODIFY ("EMP_ROLE" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USER_RIGHTS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "ITINV_STK"."STK_USER_RIGHTS" ADD CONSTRAINT "STK_USER_RIGHTS_UK1" UNIQUE ("EMPNO", "EMP_ROLE")
  USING INDEX  ENABLE;
  ALTER TABLE "ITINV_STK"."STK_USER_RIGHTS" ADD CONSTRAINT "STK_USER_RIGHTS_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX  ENABLE;
