--------------------------------------------------------
--  File created - Thursday-August-26-2021   
--------------------------------------------------------

@D:\OracleProjects\SelfService\SEQUENCES\NETWORK_PRINTER_DATA_SEQ.sql
--@D:\OracleProjects\SelfService\TABLES\SS_EMPLMAST_SUPPLEMENT.sql
@D:\OracleProjects\SelfService\TABLES\AD_DETAILS.sql
@D:\OracleProjects\SelfService\TABLES\AD_DETAILS_20151211.sql
@D:\OracleProjects\SelfService\TABLES\AD_MOBILE.sql
@D:\OracleProjects\SelfService\TABLES\AD_SYNC.sql
@D:\OracleProjects\SelfService\TABLES\AD_SYNC_20151211.sql
@D:\OracleProjects\SelfService\TABLES\AD_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\AD_TEMP_1.sql
@D:\OracleProjects\SelfService\TABLES\ASSETADMIN.sql
@D:\OracleProjects\SelfService\TABLES\ASSETADMIN1.sql
@D:\OracleProjects\SelfService\TABLES\DATA001.sql
@D:\OracleProjects\SelfService\TABLES\EMP_AC_9794.sql
@D:\OracleProjects\SelfService\TABLES\EMP_PAYROLL.sql
@D:\OracleProjects\SelfService\TABLES\EMP_PDATE_9794.sql
@D:\OracleProjects\SelfService\TABLES\EMP_PUNCH_4_9794.sql
@D:\OracleProjects\SelfService\TABLES\EMP_TASKFORCE_9794.sql
@D:\OracleProjects\SelfService\TABLES\EMP_WEEK_SELECTED.sql
@D:\OracleProjects\SelfService\TABLES\FTP_ADMIN_USER.sql
@D:\OracleProjects\SelfService\TABLES\HOLIDAYS.sql
@D:\OracleProjects\SelfService\TABLES\LL_APPROVER.sql
@D:\OracleProjects\SelfService\TABLES\LL_ASSIGNMENT.sql
@D:\OracleProjects\SelfService\TABLES\LL_CATEGORY.sql
@D:\OracleProjects\SelfService\TABLES\LL_COUNTRY.sql
@D:\OracleProjects\SelfService\TABLES\LL_DOCUMENTS.sql
@D:\OracleProjects\SelfService\TABLES\LL_DRAFT_DOCUMENT.sql
@D:\OracleProjects\SelfService\TABLES\LL_FINALDOCUMENTS.sql
@D:\OracleProjects\SelfService\TABLES\LL_FUNCTIONCODE.sql
@D:\OracleProjects\SelfService\TABLES\LL_HODUSERS.sql
@D:\OracleProjects\SelfService\TABLES\LL_KEYWORDS.sql
@D:\OracleProjects\SelfService\TABLES\LL_KEYWORDS_20150130.sql
@D:\OracleProjects\SelfService\TABLES\LL_LICENSOR.sql
@D:\OracleProjects\SelfService\TABLES\LL_MEMBERS.sql
@D:\OracleProjects\SelfService\TABLES\LL_ORIGINATOR.sql
@D:\OracleProjects\SelfService\TABLES\LL_PHASES.sql
@D:\OracleProjects\SelfService\TABLES\LL_RECORDED.sql
@D:\OracleProjects\SelfService\TABLES\LL_RECORDED_20141122.sql
@D:\OracleProjects\SelfService\TABLES\LL_RECORDED_20150123.sql
@D:\OracleProjects\SelfService\TABLES\LL_REVIEWER_DOC.sql
@D:\OracleProjects\SelfService\TABLES\LL_REVIEWREMARKS.sql
@D:\OracleProjects\SelfService\TABLES\LL_REVIEWREMARKS_20141122.sql
@D:\OracleProjects\SelfService\TABLES\LL_REVIEWREMARKS_20150123.sql
@D:\OracleProjects\SelfService\TABLES\LL_TCMPROJECT.sql
@D:\OracleProjects\SelfService\TABLES\PF_CONSENT_2011.sql
@D:\OracleProjects\SelfService\TABLES\PRINT_LOG.sql
@D:\OracleProjects\SelfService\TABLES\QUIZ_MASTER.sql
@D:\OracleProjects\SelfService\TABLES\QUIZ_PRQ02.sql
@D:\OracleProjects\SelfService\TABLES\QUIZ_PRQ03.sql
@D:\OracleProjects\SelfService\TABLES\QUIZ_TP_XLS.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_AUTOPUNCH_DEL_BETWEEN.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_DAILY_TS.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_DAILY_TS_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_EMP_LIST.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_EMP_LIST_20180625.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_EMP_LIST_DEL.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_EMP_ROLES.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_2_DEL.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_DEL_BETWEEN.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_FIRST_LAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_GENERATE.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_GENERATE_4_BT.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_GENRAT_NOFOUND1.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_GENRAT_NO_FOUND.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_GEN_NO_FOUND_FIN.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_REQUIRED.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_REQUIRED_1.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_REQUIRED_2.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_REQUIRED_3.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_PUNCH_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_ROLE_MASTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_TS_PERIOD.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_TS_SS_MAY.sql
@D:\OracleProjects\SelfService\TABLES\SS_9794_TS_SS_MAY_JUN.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_AS_LOP.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_DETAIL.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_LOP.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_LOP_REVERSE.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_MASTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_PAYSLIP_PERIOD.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_TS_DETAIL.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_TS_LEAVE.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_TS_LOP.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_TS_LOP_REVERSE.sql
@D:\OracleProjects\SelfService\TABLES\SS_ABSENT_TS_MASTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_ACCENTURE_EMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_BATCH_ERROR_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_BATCH_LOG_DETAILS.sql
@D:\OracleProjects\SelfService\TABLES\SS_BATCH_LOG_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_BATCH_STATUS_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_BATCH_TYPE_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_BL_LO_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_BUSLATE_LAYOFF_DETAIL.sql
@D:\OracleProjects\SelfService\TABLES\SS_BUSLATE_LAYOFF_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_CLINIC.sql
@D:\OracleProjects\SelfService\TABLES\SS_CLINIC_DETAIL.sql
@D:\OracleProjects\SelfService\TABLES\SS_CLINIC_DETAIL_20101129.sql
@D:\OracleProjects\SelfService\TABLES\SS_CLINIC_DETAIL_20141210.sql
@D:\OracleProjects\SelfService\TABLES\SS_CLINIC_DETAIL_20161114.sql
@D:\OracleProjects\SelfService\TABLES\SS_CLINIC_LIMIT.sql
@D:\OracleProjects\SelfService\TABLES\SS_CONSCENT.sql
@D:\OracleProjects\SelfService\TABLES\SS_CONTMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_DATATYPE.sql
@D:\OracleProjects\SelfService\TABLES\SS_DAYS.sql
@D:\OracleProjects\SelfService\TABLES\SS_DAYS_DETAILS.sql
@D:\OracleProjects\SelfService\TABLES\SS_DAYS_DETAILS_1.sql
@D:\OracleProjects\SelfService\TABLES\SS_DEBIT_TS_LEAVE.sql
@D:\OracleProjects\SelfService\TABLES\SS_DELEGATE.sql
@D:\OracleProjects\SelfService\TABLES\SS_DELTAHRSBAL.sql
@D:\OracleProjects\SelfService\TABLES\SS_DELTAHRSBAL_OT.sql
@D:\OracleProjects\SelfService\TABLES\SS_DEPT_GROUPING.sql
@D:\OracleProjects\SelfService\TABLES\SS_DEPT_NOT_4_ABSENT.sql
@D:\OracleProjects\SelfService\TABLES\SS_DEPU.sql
@D:\OracleProjects\SelfService\TABLES\SS_DEPU_DELETED.sql
@D:\OracleProjects\SelfService\TABLES\SS_DEPU_HIST.sql
@D:\OracleProjects\SelfService\TABLES\SS_DEPU_REJECTED.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKASSIGNMENT.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKASSIGNMENT_20091126.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKASSIGNMENT_20091127.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKASSIGNMENT_25NOV_BACUP.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKASSINMENT_20091118.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKMONITOR.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKPC.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKREFILL.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKTASK.sql
@D:\OracleProjects\SelfService\TABLES\SS_DESKTEL.sql
@D:\OracleProjects\SelfService\TABLES\SS_DMS_STATUS2020.sql
@D:\OracleProjects\SelfService\TABLES\SS_DMS_STATUS2021.sql
@D:\OracleProjects\SelfService\TABLES\SS_EMPLMAST_SUPPLEMENT.sql
@D:\OracleProjects\SelfService\TABLES\SS_EMPLPHOTOS.sql
@D:\OracleProjects\SelfService\TABLES\SS_EMP_CARD_RFID_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_EMP_COMP_LASTDATE_4_MUSTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_EMP_TRANSFER.sql
@D:\OracleProjects\SelfService\TABLES\SS_ENGG_COSTCODES.sql
@D:\OracleProjects\SelfService\TABLES\SS_EXTRAHOLIDAY.sql
@D:\OracleProjects\SelfService\TABLES\SS_FEEDBACK.sql
@D:\OracleProjects\SelfService\TABLES\SS_FIESTA_2011.sql
@D:\OracleProjects\SelfService\TABLES\SS_FILE_UPLOAD_LOG.sql
@D:\OracleProjects\SelfService\TABLES\SS_FILE_UPLOAD_PARAM.sql
@D:\OracleProjects\SelfService\TABLES\SS_FILTERON.sql
@D:\OracleProjects\SelfService\TABLES\SS_FIM_DATA.sql
@D:\OracleProjects\SelfService\TABLES\SS_FORPWD.sql
@D:\OracleProjects\SelfService\TABLES\SS_GENERAL_CODES.sql
@D:\OracleProjects\SelfService\TABLES\SS_GUEST_REGISTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_HALFDAYMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_BILL.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_BILLMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_BLD.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_EMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_EMP_24FEB15.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_HRD.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_HRDUSER.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_HRD_24FEB15.sql
@D:\OracleProjects\SelfService\TABLES\SS_HEALTH_RPT.sql
@D:\OracleProjects\SelfService\TABLES\SS_HOLIDAY_15NOV2012.sql
@D:\OracleProjects\SelfService\TABLES\SS_HOLIDAY_ATTENDANCE.sql
@D:\OracleProjects\SelfService\TABLES\SS_HR_FRM_MENU.sql
@D:\OracleProjects\SelfService\TABLES\SS_HR_PEND_OD.sql
@D:\OracleProjects\SelfService\TABLES\SS_HSESUGG.sql
@D:\OracleProjects\SelfService\TABLES\SS_HSE_INCIDENTREPORT.sql
@D:\OracleProjects\SelfService\TABLES\SS_HSE_QUIZ.sql
@D:\OracleProjects\SelfService\TABLES\SS_HSE_QUIZ_2.sql
@D:\OracleProjects\SelfService\TABLES\SS_HSE_QUIZ_3.sql
@D:\OracleProjects\SelfService\TABLES\SS_IMPORTPUNCH.sql
@D:\OracleProjects\SelfService\TABLES\SS_IMPORTPUNCH1.sql
@D:\OracleProjects\SelfService\TABLES\SS_IMPORTPUNCH2.sql
@D:\OracleProjects\SelfService\TABLES\SS_IP_ADD.sql
@D:\OracleProjects\SelfService\TABLES\SS_ISD_CODE_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_LDAP_LIST.sql
@D:\OracleProjects\SelfService\TABLES\SS_LDAP_LIST_200911251026.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAD_APPROVER.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVEAPP.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVEAPP_DELETED.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVEAPP_REJECTED.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVEBAL.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVELEDG.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVETYPE.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVE_ADJ.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVE_ADJ_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVE_BAL_MAX_LIMIT.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVE_UPLOAD_LOG.sql
@D:\OracleProjects\SelfService\TABLES\SS_LEAVE_UPLOAD_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_LOCK_OT_HRS_DOWNLOAD_PERIOD.sql
@D:\OracleProjects\SelfService\TABLES\SS_LUNCHMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_MOBILEVOTE.sql
@D:\OracleProjects\SelfService\TABLES\SS_MONTHLY_CREDIT_EXCEPTION.sql
@D:\OracleProjects\SelfService\TABLES\SS_MONTHLY_CREDIT_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER_20120310.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER_4ALLOWANCE.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER_4ALLOWANCE_20090407.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER_4ALLOWANCE_20101006.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER_4ALLOWANCE_20101220.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER_BACKUP.sql
@D:\OracleProjects\SelfService\TABLES\SS_MUSTER_BACKUP_20080303.sql
@D:\OracleProjects\SelfService\TABLES\SS_NAVRATRI.sql
@D:\OracleProjects\SelfService\TABLES\SS_NAVRATRI_2011.sql
@D:\OracleProjects\SelfService\TABLES\SS_NAVRATRI_2017.sql
@D:\OracleProjects\SelfService\TABLES\SS_NAVRATRI_2018.sql
@D:\OracleProjects\SelfService\TABLES\SS_NAVRATRI_2019.sql
@D:\OracleProjects\SelfService\TABLES\SS_OD2RW_LIST.sql
@D:\OracleProjects\SelfService\TABLES\SS_OFFICE_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_ONDUTY.sql
@D:\OracleProjects\SelfService\TABLES\SS_ONDUTYAPP.sql
@D:\OracleProjects\SelfService\TABLES\SS_ONDUTYAPP_DELETED.sql
@D:\OracleProjects\SelfService\TABLES\SS_ONDUTYAPP_REJECTED.sql
@D:\OracleProjects\SelfService\TABLES\SS_ONDUTYMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_OPERATOR.sql
@D:\OracleProjects\SelfService\TABLES\SS_OT.sql
@D:\OracleProjects\SelfService\TABLES\SS_OT1.sql
@D:\OracleProjects\SelfService\TABLES\SS_OTAPPRL.sql
@D:\OracleProjects\SelfService\TABLES\SS_OTDETAIL.sql
@D:\OracleProjects\SelfService\TABLES\SS_OTMASTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_OTWEEKLY.sql
@D:\OracleProjects\SelfService\TABLES\SS_OT_DETAILS_4_YEAR.sql
@D:\OracleProjects\SelfService\TABLES\SS_OT_DETAILS_4_YEAR_ALL.sql
@D:\OracleProjects\SelfService\TABLES\SS_OT_DETAILS_4_YEAR_ALL_0225.sql
@D:\OracleProjects\SelfService\TABLES\SS_OT_DETAILS_4_YEAR_ALL_REST.sql
@D:\OracleProjects\SelfService\TABLES\SS_OT_DOWNLOAD_DBF_LOCK.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_CANON.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_CANON_ERRORS.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_CANON_MANUAL.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_CANON_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_DATES.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_KYOCER.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_KYOCER_ERRORS.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_KYOCER_MANUAL.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAGECOUNT_KYOCER_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAPER_SIZE_MAP.sql
@D:\OracleProjects\SelfService\TABLES\SS_PAYROLLTYPEMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_PHONE_CALL_LOG_20171120.sql
@D:\OracleProjects\SelfService\TABLES\SS_PHONE_CALL_LOG_CURR.sql
@D:\OracleProjects\SelfService\TABLES\SS_PHONE_EXT_LOG.sql
@D:\OracleProjects\SelfService\TABLES\SS_PHOTOCONSENT.sql
@D:\OracleProjects\SelfService\TABLES\SS_PLACE.sql
@D:\OracleProjects\SelfService\TABLES\SS_PLOTTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_PL_REVISION_APP.sql
@D:\OracleProjects\SelfService\TABLES\SS_PL_REVISION_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_PORTAL_NEWS.sql
@D:\OracleProjects\SelfService\TABLES\SS_PRINTLOG_TEST.sql
@D:\OracleProjects\SelfService\TABLES\SS_PRINT_LOG.sql
@D:\OracleProjects\SelfService\TABLES\SS_PRINT_RATE_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCHBACKUPON01042003.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCHBACKUP_20070711.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCHDATABACKUP.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_200604_17_18_19.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_20100329.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_20110426.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_ALL.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_AUTO.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_AUTO_TYPE_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_BACKUP_20061031.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_BACKUP_20100226.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_BAL.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_MANUAL.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_UPLOAD_BLOB.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_UP_TO_20071231.sql
@D:\OracleProjects\SelfService\TABLES\SS_PUNCH_WFH.sql
@D:\OracleProjects\SelfService\TABLES\SS_REJOIN.sql
@D:\OracleProjects\SelfService\TABLES\SS_REPORT_FIELDS.sql
@D:\OracleProjects\SelfService\TABLES\SS_REPORT_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_SECRETARY_20081011.sql
@D:\OracleProjects\SelfService\TABLES\SS_SECRETARY_DESK.sql
@D:\OracleProjects\SelfService\TABLES\SS_SECRETARY_REP.sql
@D:\OracleProjects\SelfService\TABLES\SS_SHIFTMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_SHIFTMAST_20090401.sql
@D:\OracleProjects\SelfService\TABLES\SS_SHIFT_AUTO_ASSIGN_LOG.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_ALLOWANCE_PERIOD_ADJ.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_ALLOWANCE_PROCESSED.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_ALLOWANCE_ROLLOVER.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_ALLOWANCE_TRANS.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_ALLWNC_PERIOD_ADJ_DEL.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_EMPLOYEE.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_GRADE_ALLOWANCE.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_LOC_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_MUSTER.sql
@D:\OracleProjects\SelfService\TABLES\SS_SITE_MUSTER_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\SS_SUGGESTION.sql
@D:\OracleProjects\SelfService\TABLES\SS_SWIPE_MACH_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_TABLETAG.sql
@D:\OracleProjects\SelfService\TABLES\SS_TCMPL_IP_4_WFH_RDP.sql
@D:\OracleProjects\SelfService\TABLES\SS_TCMPL_IP_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_TCMPL_IP_SKIP.sql
@D:\OracleProjects\SelfService\TABLES\SS_TEMP_DESK_ASSIGN.sql
@D:\OracleProjects\SelfService\TABLES\SS_TRAVELREQ.sql
@D:\OracleProjects\SelfService\TABLES\SS_TRAVELREQ_200100218.sql
@D:\OracleProjects\SelfService\TABLES\SS_UN_APPRD_APP.sql
@D:\OracleProjects\SelfService\TABLES\SS_USB_REQUEST.sql
@D:\OracleProjects\SelfService\TABLES\SS_USB_REQUEST_CHG_LOG.sql
@D:\OracleProjects\SelfService\TABLES\SS_USERMAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_USER_DEPT_RIGHTS.sql
@D:\OracleProjects\SelfService\TABLES\SS_USER_DEPT_RIGHTS_20150825.sql
@D:\OracleProjects\SelfService\TABLES\SS_USER_TYPE_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_WORKED_HRS_DETAIL.sql
@D:\OracleProjects\SelfService\TABLES\SS_WORKED_HRS_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SS_XL_BLOB.sql
@D:\OracleProjects\SelfService\TABLES\SS_XL_BLOB_DATA.sql
/*
@D:\OracleProjects\SelfService\TABLES\SWP_BUS_ROUTES.sql
@D:\OracleProjects\SelfService\TABLES\SWP_EMP_RESPONSE.sql
@D:\OracleProjects\SelfService\TABLES\SWP_EMP_TRAINING.sql
@D:\OracleProjects\SelfService\TABLES\SWP_EMP_TRAINING_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\SWP_EMP_WITH_COMP_MOB.sql
@D:\OracleProjects\SelfService\TABLES\SWP_INOCULATED_12JUN.sql
@D:\OracleProjects\SelfService\TABLES\SWP_ISP.sql
@D:\OracleProjects\SelfService\TABLES\SWP_IT_PREREQUISITES.sql
@D:\OracleProjects\SelfService\TABLES\SWP_MAIL_LOG.sql
@D:\OracleProjects\SelfService\TABLES\SWP_RELATION_MAST.sql
@D:\OracleProjects\SelfService\TABLES\SWP_SOFTWARES.sql
@D:\OracleProjects\SelfService\TABLES\SWP_TPL_VACCINE_BATCH.sql
@D:\OracleProjects\SelfService\TABLES\SWP_TPL_VACCINE_BATCH_EMP.sql
@D:\OracleProjects\SelfService\TABLES\SWP_VACCINATION_OFFICE.sql
@D:\OracleProjects\SelfService\TABLES\SWP_VACCINATION_OFFICE_210612.sql
@D:\OracleProjects\SelfService\TABLES\SWP_VACCINATION_OFFICE_BATCH_2.sql
@D:\OracleProjects\SelfService\TABLES\SWP_VACCINATION_OFFICE_FAMILY.sql
@D:\OracleProjects\SelfService\TABLES\SWP_VACCINE_COVID_EMP.sql
@D:\OracleProjects\SelfService\TABLES\SWP_VACCINE_DATES.sql
@D:\OracleProjects\SelfService\TABLES\SWP_VACCINE_MASTER.sql
*/
@D:\OracleProjects\SelfService\TABLES\TEMP.sql
@D:\OracleProjects\SelfService\TABLES\TEMPASSET.sql
@D:\OracleProjects\SelfService\TABLES\TEST_1.sql
--@D:\OracleProjects\SelfService\TABLES\USERIDS.sql
@D:\OracleProjects\SelfService\TABLES\USERIDS_20210510.sql
@D:\OracleProjects\SelfService\TABLES\USERID_LOG.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ACTION_TRANS.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ACTION_TRANS_07DEC16.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ACTION_TYPE.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ALLOCATION_OLD.sql
@D:\OracleProjects\SelfService\TABLES\XDM_AMS_TRANSCODE.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETADD.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETADD_16APR10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETADD_BACKUP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETADD_ERR.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETCODE.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETCODE_05DEC16.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETCODE_20DEC.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETCODE_BACK14DEC.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETCODE_MACHINE.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETCODE_TOSITE.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETMODIFICATION.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETMOVE_TRAN.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETMOVE_TRAN_16APR10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETMOVE_TRAN_HISTORY.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETMOVE_TRAN_HIST_051216.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSETTYPE.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSET_MODIFY.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSET_OFFICE.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSET_OUT_OF_USE_LOG.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ASSET_REMOVED.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DEPUTATION_26NOV.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DEPUTATION_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_05DEC16.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_16APR10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_20DEC.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_31DEC.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_3SEP10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_4SEP10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_ERR.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_LOG.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKALLOCATION_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKLOCK.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKLOCK_16APR10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKLOCK_BACKUP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKLOCK_ERR.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKLOCK_REASON.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKMASTER.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKMASTER_OLD.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKMASTER_TEMP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKMASTER_VISIO_BACKUP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_DESKMASTER_VISIO_ID.sql
@D:\OracleProjects\SelfService\TABLES\XDM_EMAILID.sql
@D:\OracleProjects\SelfService\TABLES\XDM_EMPADD.sql
@D:\OracleProjects\SelfService\TABLES\XDM_EMP_LEFT.sql
@D:\OracleProjects\SelfService\TABLES\XDM_EMP_LEFT_DEL.sql
@D:\OracleProjects\SelfService\TABLES\XDM_FIXEDPC.sql
@D:\OracleProjects\SelfService\TABLES\XDM_GUESTMASTER.sql
@D:\OracleProjects\SelfService\TABLES\XDM_INTERNET.sql
@D:\OracleProjects\SelfService\TABLES\XDM_INTERNETMASTER.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ITUSER.sql
@D:\OracleProjects\SelfService\TABLES\XDM_LAPTOP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_LAPTOP_PERMT.sql
@D:\OracleProjects\SelfService\TABLES\XDM_LOGINRIGHT.sql
@D:\OracleProjects\SelfService\TABLES\XDM_LOGINRIGHT_20150925.sql
@D:\OracleProjects\SelfService\TABLES\XDM_NEWJOIN_EMP.sql
@D:\OracleProjects\SelfService\TABLES\XDM_NEWJOIN_TRANS.sql
@D:\OracleProjects\SelfService\TABLES\XDM_NEWJOIN_TRANS_20150401.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ONDEPUTATION.sql
@D:\OracleProjects\SelfService\TABLES\XDM_ONDEPUTATION_31JAN2010.sql
@D:\OracleProjects\SelfService\TABLES\XDM_PCNAME.sql
@D:\OracleProjects\SelfService\TABLES\XDM_PCNAME_20091119.sql
@D:\OracleProjects\SelfService\TABLES\XDM_PENDING_PC_LOCK.sql
@D:\OracleProjects\SelfService\TABLES\XDM_PENDING_PC_LOCK_20150925.sql
@D:\OracleProjects\SelfService\TABLES\XDM_SECRETARY.sql
@D:\OracleProjects\SelfService\TABLES\XDM_SOURCEDESK.sql
@D:\OracleProjects\SelfService\TABLES\XDM_SPECIAL_SHIFTING.sql
@D:\OracleProjects\SelfService\TABLES\XDM_TARGETDESK.sql
@D:\OracleProjects\SelfService\TABLES\XDM_TASKFORCETRAN.sql
@D:\OracleProjects\SelfService\TABLES\XDM_TRAN_HIST_20100416.sql
@D:\OracleProjects\SelfService\TABLES\XDM_USERMASTER.sql
@D:\OracleProjects\SelfService\TABLES\XDM_USERMASTER_16APR10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_USERMASTER_20DEC.sql
@D:\OracleProjects\SelfService\TABLES\XDM_USERMASTER_31DEC.sql
@D:\OracleProjects\SelfService\TABLES\XDM_USERMASTER_4SEP10.sql
@D:\OracleProjects\SelfService\TABLES\XDM_USERMASTER_ERR.sql
@D:\OracleProjects\SelfService\TABLES\XDM_USERMASTER_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\CV_EMPLDETAILS.sql
@D:\OracleProjects\SelfService\VIEWS\DESMAS_ALLOCATION.sql
@D:\OracleProjects\SelfService\VIEWS\DESMAS_ALLOCATION_ALL.sql
@D:\OracleProjects\SelfService\VIEWS\DESMAS_EMPTYDESK.sql
@D:\OracleProjects\SelfService\VIEWS\DESMAS_EMP_OFFICE.sql
@D:\OracleProjects\SelfService\VIEWS\DESMAS_STATUS.sql
@D:\OracleProjects\SelfService\VIEWS\DESMAS_STATUS_4_REPORT.sql
@D:\OracleProjects\SelfService\VIEWS\DESMAS_USERMASTER.sql
@D:\OracleProjects\SelfService\VIEWS\DISPLEDG.sql
@D:\OracleProjects\SelfService\VIEWS\DM_PCLIST.sql
@D:\OracleProjects\SelfService\VIEWS\DM_PC_MOVEMENT_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\DM_PC_STATUS.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_ASSET_DESK_20130101.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_ASSET_LIST.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_DESK_LIST.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_EMP_DESK_20130101.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_EMP_DESK_OFFICE.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_EMP_MOVE_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_PC_MOVE_HIST.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_PC_MOVE_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_PC_STATUS.sql
@D:\OracleProjects\SelfService\VIEWS\DM_VU_USER_DESK_PC.sql
@D:\OracleProjects\SelfService\VIEWS\EMP_DETAILS_FAMILY.sql
@D:\OracleProjects\SelfService\VIEWS\EMP_DETAILS_NOT_FILLED.sql
@D:\OracleProjects\SelfService\VIEWS\EMP_DETAILS_PASSPORT.sql
@D:\OracleProjects\SelfService\VIEWS\EMP_DETAILS_TOTAL.sql
@D:\OracleProjects\SelfService\VIEWS\EMP_DETAILS_USING_BUS.sql
@D:\OracleProjects\SelfService\VIEWS\EMP_OUTSIDE.sql
@D:\OracleProjects\SelfService\VIEWS\JOBMASTER.sql
@D:\OracleProjects\SelfService\VIEWS\LL_DECLINED.sql
@D:\OracleProjects\SelfService\VIEWS\LL_REJECTED.sql
@D:\OracleProjects\SelfService\VIEWS\ODAPPRL.sql
@D:\OracleProjects\SelfService\VIEWS\OT_962709_FROM_APR2010.sql
@D:\OracleProjects\SelfService\VIEWS\OT_962709_TILL_MAR2010.sql
@D:\OracleProjects\SelfService\VIEWS\PS_COSTMAST.sql
@D:\OracleProjects\SelfService\VIEWS\PS_PROJMAST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_9794_VU_BT_PUNCH_COUNT.sql
@D:\OracleProjects\SelfService\VIEWS\SS_9794_VU_PUNCH_SEC.sql
@D:\OracleProjects\SelfService\VIEWS\SS_9794_VU_TS.sql
@D:\OracleProjects\SelfService\VIEWS\SS_BB_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\SS_CONSCENT_REP.sql
@D:\OracleProjects\SelfService\VIEWS\SS_CONSTRAINT.sql
--@D:\OracleProjects\SelfService\VIEWS\SS_COSTMAST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_COSTMASTAS.sql
@D:\OracleProjects\SelfService\VIEWS\SS_DEPU_EDTICB.sql
--@D:\OracleProjects\SelfService\VIEWS\SS_DESGMAST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_DESG_NAME.sql
@D:\OracleProjects\SelfService\VIEWS\SS_DISPLEDG.sql
@D:\OracleProjects\SelfService\VIEWS\SS_DISPLEDG_HIST.sql
--@D:\OracleProjects\SelfService\VIEWS\SS_EMPLMAST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_EMPLMAST_ALL.sql
@D:\OracleProjects\SelfService\VIEWS\SS_EMPLMAST_EDTICB.sql
@D:\OracleProjects\SelfService\VIEWS\SS_EMPLMAST_INST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_EMPLMAST_TICB.sql
@D:\OracleProjects\SelfService\VIEWS\SS_EMPLMAST_WIN_ID.sql
@D:\OracleProjects\SelfService\VIEWS\SS_EMP_PRINT_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\SS_HA_APP_STAT.sql
@D:\OracleProjects\SelfService\VIEWS\SS_HEALTH_STATUS.sql
@D:\OracleProjects\SelfService\VIEWS\SS_HOLIDAYS.sql
@D:\OracleProjects\SelfService\VIEWS\SS_HOLIDAYS2001.sql
@D:\OracleProjects\SelfService\VIEWS\SS_HSE_QUIZ_VIEW.sql
@D:\OracleProjects\SelfService\VIEWS\SS_INTEGRATEDPUNCH.sql
@D:\OracleProjects\SelfService\VIEWS\SS_INTEGRATEDPUNCHTEST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_INTEGRATEDPUNCH_DEV.sql
@D:\OracleProjects\SelfService\VIEWS\SS_INTEGRATEDPUNCH_MACH.sql
@D:\OracleProjects\SelfService\VIEWS\SS_IPFORMAT.sql
@D:\OracleProjects\SelfService\VIEWS\SS_JOB_INDUSTRY.sql
@D:\OracleProjects\SelfService\VIEWS\SS_LEAVEAPP_EDTICB.sql
@D:\OracleProjects\SelfService\VIEWS\SS_LEAVE_APP_LEDG.sql
@D:\OracleProjects\SelfService\VIEWS\SS_LEAVE_PENDING4APPRL.sql
@D:\OracleProjects\SelfService\VIEWS\SS_ODAPPRL.sql
@D:\OracleProjects\SelfService\VIEWS\SS_ODAPPRL_EDTICB.sql
@D:\OracleProjects\SelfService\VIEWS\SS_ODAPPSTAT.sql
@D:\OracleProjects\SelfService\VIEWS\SS_ONDUTYAPP_EDTICB.sql
@D:\OracleProjects\SelfService\VIEWS\SS_OPBAL2002.sql
@D:\OracleProjects\SelfService\VIEWS\SS_OTDET_4_ANITA.sql
@D:\OracleProjects\SelfService\VIEWS\SS_OTMASTER_EDTICB.sql
@D:\OracleProjects\SelfService\VIEWS\SS_OT_4_ANITA.sql
@D:\OracleProjects\SelfService\VIEWS\SS_PHONE_CALL_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\SS_PROJMAST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_TAB.sql
@D:\OracleProjects\SelfService\VIEWS\SS_TIME_DAILY.sql
@D:\OracleProjects\SelfService\VIEWS\SS_TIME_OT.sql
@D:\OracleProjects\SelfService\VIEWS\SS_TRAINING_LIST_4_OT.sql
@D:\OracleProjects\SelfService\VIEWS\SS_TRAINING_MAST_4_OT.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_4_LEAVE_CALENDAR.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_ABSENT_LOP.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_ABSENT_LOP_NU.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_ABSENT_LOP_REVERSE.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_ABSENT_TS_LOP.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_ABSENT_TS_LOP_REVERSE.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_CONTMAST.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_MANUAL_PUNCH.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_MANUAL_PUNCH_REP.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_OT_ALL.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_PHONE_LOG.sql
@D:\OracleProjects\SelfService\VIEWS\SS_VU_PRINT_LOG_PIVOT.sql
--@D:\OracleProjects\SelfService\VIEWS\SWP_VU_EMP_RESPONSE.sql
--@D:\OracleProjects\SelfService\VIEWS\SWP_VU_EMP_VACCINE_DATE.sql
--@D:\OracleProjects\SelfService\VIEWS\SWP_VU_TPL_VACCINE_BATCH_DET.sql
--@D:\OracleProjects\SelfService\VIEWS\SWP_VU_VACCINE_OFF_BATCH2_REGN.sql
@D:\OracleProjects\SelfService\VIEWS\TEMPTEST.sql
@D:\OracleProjects\SelfService\VIEWS\TEMP_DISPLEDG.sql
@D:\OracleProjects\SelfService\VIEWS\TR_EMPLMAST_WIN_ID.sql
@D:\OracleProjects\SelfService\VIEWS\VIEW1.sql
@D:\OracleProjects\SelfService\VIEWS\VU_TO_DELETE.sql
@D:\OracleProjects\SelfService\VIEWS\View1_1.sql
@D:\OracleProjects\SelfService\INDEXES\DM_EMAILID_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_ONDUTYAPP_IDX___00410000.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_BDATE_DEPU_HIST.sql
@D:\OracleProjects\SelfService\INDEXES\DM_ASSETCODE_INDEX2.sql
@D:\OracleProjects\SelfService\INDEXES\EWP_IPHONE_USERS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVE_ADJ_IDX_011.sql
@D:\OracleProjects\SelfService\INDEXES\U_APPNO_DEPU.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_EMP_TRAINING_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SITE_ALLOWANCE_PROCESS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_SS_UP_FILE.sql
@D:\OracleProjects\SelfService\INDEXES\DM_NEWJOIN_EMP_PK.sql
@D:\OracleProjects\SelfService\INDEXES\TABLE1_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ENTRY_DATE_CANON_MANUAL.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DAYS_IDX_002.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_WFH_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DELTAHRSBAL_OT_IDX_001.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVE_ADJ__PK41080795457153.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_008.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IMPORTPUNCH.sql
@D:\OracleProjects\SelfService\INDEXES\SS_ONDUTYAPP_IDX_001.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DEPU_IDX___00410001.sql
@D:\OracleProjects\SelfService\INDEXES\PK_REP_MAST.sql
@D:\OracleProjects\SelfService\INDEXES\PK_SEC_EMPNO_HOD_REP.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_VACCINE_COVID_EMP_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_IDX_008.sql
@D:\OracleProjects\SelfService\INDEXES\DM_ASSETTYPE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_014.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SITE_ALLOWANCE_PERIOD__PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_SS_UPLOAD_FILE.sql
@D:\OracleProjects\SelfService\INDEXES\IDX_GEN_CODES.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HEALTH_RPT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_PDATE_DELTABAL.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_030.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_006.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SITE_MOBI_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_MANUAL_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_TPL_VACINE_BATCH_UK1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_ONDUTYAPP_IDX_006.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_VACCINE_DATES_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_MANUAL_ID_CANON_MANUAL.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DAYS_DETAILS_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPHHMMDATETYPEHHSMMS.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SITE_ALLOWANCE_TRANS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\DM_EMP_LEFT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_CLINIC_DETAIL_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_020.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_HH_MM_PDATE_TYPE.sql
@D:\OracleProjects\SelfService\INDEXES\DM_ASSETADD_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_MONTHLY_CREDIT_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_003.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_005.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SITE_ALLOWANCE_ROLLOVE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\U_ADJNO_LEAVEADJ.sql
@D:\OracleProjects\SelfService\INDEXES\SS_BATCH_TYPE_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\U_EMPNO_MON_YYYY.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_RELATION_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ETY_DT_PRN_Q_KYOCER_M.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HEALTH_HRD_PK.sql
@D:\OracleProjects\SelfService\INDEXES\INDEX2.sql
@D:\OracleProjects\SelfService\INDEXES\LL_RECORDED_PK.sql
@D:\OracleProjects\SelfService\INDEXES\IDX___024C0002.sql
@D:\OracleProjects\SelfService\INDEXES\DM_GUESTMASTER_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVE_BAL_MAX_LIMIT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SUGGESTION_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_TPL_VACCINE_BATCH_EMP_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_007.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_CODE_PDATE.sql
@D:\OracleProjects\SelfService\INDEXES\U_EMPNOHH1MM1TYPEPDATE.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DEPU_IDX_003.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_BALDATE_LEAVEBAL.sql
@D:\OracleProjects\SelfService\INDEXES\PK_PAYROLLTYPE_TYPE.sql
@D:\OracleProjects\SelfService\INDEXES\LL_APPROVER_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_MANUAL_ID_KYOCER_MANUAL.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_009.sql
@D:\OracleProjects\SelfService\INDEXES\SS_MONTHLY_CREDIT_MAST_UK1.sql
@D:\OracleProjects\SelfService\INDEXES\DM_LOGINRIGHT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_LEAVE_UP_TEMP.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_004.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVE_ADJ_IDX_004.sql
@D:\OracleProjects\SelfService\INDEXES\DM_TARGETDESK_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_REJOIN_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HEALTH_BILL_PK.sql
@D:\OracleProjects\SelfService\INDEXES\LL_REVIEWREMARKS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\U_APPNO_PDATE_ONDUTYAPP.sql
@D:\OracleProjects\SelfService\INDEXES\SS_BATCH_ERRORS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DEPU_IDX_008.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SWIPE_MACH_PK.sql
@D:\OracleProjects\SelfService\INDEXES\IDX_GEN_CODES_1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_002.sql
@D:\OracleProjects\SelfService\INDEXES\DM_DESKMASTER_VISIO_ID_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_WFH_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_VACCINATION_OFFICE_FAM_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_CONTMAST_PK51086329176495.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_063.sql
@D:\OracleProjects\SelfService\INDEXES\PK_LEAVETYPE.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_001.sql
@D:\OracleProjects\SelfService\INDEXES\IDX___024C0001.sql
@D:\OracleProjects\SelfService\INDEXES\IDX___024C0004.sql
@D:\OracleProjects\SelfService\INDEXES\SS_9794_EMP_LIST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_EMP_TRANSF_PK11112264442918.sql
@D:\OracleProjects\SelfService\INDEXES\DM_ASSETCODE_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\U_APPNO_DEPU_HIST.sql
@D:\OracleProjects\SelfService\INDEXES\PK_MUSTER_4ALOWNC.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_BDATE.sql
@D:\OracleProjects\SelfService\INDEXES\SS_CLINIC_PK.sql
@D:\OracleProjects\SelfService\INDEXES\USERIDS_INDEX2.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_EMP_RESPONSE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_REP_FIELDS.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DMS_STATUS2020_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_ABSENT_TS_LEAVE_PK1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_OTDETAIL_PK31028090953295.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ENTRY_DT_KYOCER_MANUAL.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PRINT_LOG_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_029.sql
@D:\OracleProjects\SelfService\INDEXES\DM_DESKMASTER_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_9794_EMP_LIST_UK1.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_PDATE.sql
@D:\OracleProjects\SelfService\INDEXES\PK_SEC.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SECRETARY_RIGHTS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_SITEMAST.sql
@D:\OracleProjects\SelfService\INDEXES\USERIDS_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\AD_SYNC_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_FEEDBACK_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_LUNCHMAST_SHIFT_PAR.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX___01210000.sql
@D:\OracleProjects\SelfService\INDEXES\SS_OFFICE_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DAYS_DETAILS_IDX_125.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_MON_YYYY.sql
@D:\OracleProjects\SelfService\INDEXES\SS_CONSCENT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DEPU_IDX_012.sql
@D:\OracleProjects\SelfService\INDEXES\PK_TYPE_ONDUTYMAST.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_VACCINE_MASTER_PK.sql
@D:\OracleProjects\SelfService\INDEXES\LL_ASSIGNMENT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_SITELOC.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PRINT_LOG_INDEX2.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_IT_PREREQUISITES_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PL_REVISION_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\DM_LAPTOP_PERMT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_VACCINATION_OFFICE_BAT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_004.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HEALTH_EMP_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_9794_ROLE_MASTER_UK1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_OTMASTER_UK21028183671263.sql
@D:\OracleProjects\SelfService\INDEXES\DM_TASKFORCETRAN_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ETY_DT_PRN_Q_CANON.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DELTAHRSBAL_OT_IDX_002.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_BATCH_LOG_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAD_APPROVER_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ETY_DT_1_8_PRN_Q_KYOCER.sql
@D:\OracleProjects\SelfService\INDEXES\LL_CATEGORY_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_9794_ROLE_MASTER_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DELEGATE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\LL_MEMBERS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_BATCH_STATUS_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\DM_SOURCEDESK_PK.sql
@D:\OracleProjects\SelfService\INDEXES\U_FILE_UP_KEY.sql
@D:\OracleProjects\SelfService\INDEXES\SS_ONDUTY_IDX_006.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_010.sql
@D:\OracleProjects\SelfService\INDEXES\SS_9794_EMP_ROLES_PK.sql
@D:\OracleProjects\SelfService\INDEXES\U_EMPNO_HH_MM_PDATE_APPNO.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_ALL_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_HR_MENU.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IDX_PUNCH_EMPNOHHMMDATE.sql
@D:\OracleProjects\SelfService\INDEXES\DM_EMPADD_PK.sql
@D:\OracleProjects\SelfService\INDEXES\IDX___01230001.sql
@D:\OracleProjects\SelfService\INDEXES\U_LEAVE_UP_KEY.sql
@D:\OracleProjects\SelfService\INDEXES\SS_USB_REQUEST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PHOTOCONSENT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\PK_CODE.sql
@D:\OracleProjects\SelfService\INDEXES\PK_SITEMUSTER.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_TPL_VACINE_BATCH_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_ISP_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DELTAHRSBAL_IDX_138.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_064.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DESKASSIGNMENT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\DM_ASSETMOVE_TRAN_HIS_IND1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_MANUAL_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\PK_SYS0804141204.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HEALTH_BILLMAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_019.sql
@D:\OracleProjects\SelfService\INDEXES\SS_MUSTER_INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_VACCINATION_OFFICE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX___00410002.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DAYS_DETAILS_IDX_007.sql
@D:\OracleProjects\SelfService\INDEXES\AD_DETAILS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVEAPP_IDX_007.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVE_ADJ_IDX_002.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVELEDG_IDX_015.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HOLIDAY_ATTENDANCE_UK1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HSE_QUIZ_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_ABSENT_LOP_REVERSE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LOCK_EXTRA_HRS_PERIOD_PK.sql
@D:\OracleProjects\SelfService\INDEXES\DM_ASSETMOVE_TRAN_PK.sql
@D:\OracleProjects\SelfService\INDEXES\IDX___024C0003.sql
@D:\OracleProjects\SelfService\INDEXES\SS_CLINIC_LIMIT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_OTDETAIL_IDX_001.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PORTAL_NEWS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\DM_NEWJOIN_TRANS_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_OT_DOWNLOAD_DBF_LOCK_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_ACN_EMP.sql
@D:\OracleProjects\SelfService\INDEXES\ASSETADMIN_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SWP_BUS_ROUTES_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ETY_DT_PRN_Q_CANON_M.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HOLIDAY_ATTENDANCE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_USER_TYPE_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\U_APPNO_LEAVEAPP.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HSE_INCIDENTREPORT_PK.sql
@D:\OracleProjects\SelfService\INDEXES\FTP_ADMIN_USER_PK.sql
@D:\OracleProjects\SelfService\INDEXES\U_APP_NO.sql
@D:\OracleProjects\SelfService\INDEXES\INDEX1.sql
@D:\OracleProjects\SelfService\INDEXES\PK_EMPNO_TYPE_USERMAST.sql
@D:\OracleProjects\SelfService\INDEXES\SS_NAVRATRI_PK.sql
@D:\OracleProjects\SelfService\INDEXES\DM_PENDING_PC_LOCK_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ETY_DT_1_8_PRN_Q_CANON.sql
@D:\OracleProjects\SelfService\INDEXES\LL_REVIEWER_DOC_PK.sql
@D:\OracleProjects\SelfService\INDEXES\UNQ_FILENAME.sql
@D:\OracleProjects\SelfService\INDEXES\SS_EMP_COMP_LASTDATE.sql
@D:\OracleProjects\SelfService\INDEXES\SS_DEPU_IDX_009.sql
@D:\OracleProjects\SelfService\INDEXES\PK_DATATYPE.sql
@D:\OracleProjects\SelfService\INDEXES\U_APPNO.sql
@D:\OracleProjects\SelfService\INDEXES\SS_HEALTH_HRD_IDX___1B5D0004.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PRINT_LOG_INDEX3.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PUNCH_AUTO_TYP_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\EMP_WEEK_MAST_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_PL_REVISION_MAST_UK1.sql
@D:\OracleProjects\SelfService\INDEXES\SS_LEAVE_ADJ_IDX_005.sql
@D:\OracleProjects\SelfService\INDEXES\DM_ASSET_OFFICE_PK.sql
@D:\OracleProjects\SelfService\INDEXES\SS_IND_ETY_DT_PRN_Q_KYOCER.sql
@D:\OracleProjects\SelfService\TRIGGERS\DM_ASSETCODE_NO_USE.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_9794_ROLE_MAST.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_TRIG_ABSENT_DETAIL_01.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_TRIG_DEPU_DELETED.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_TRIG_DEPU_UPDATE.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_TRIG_LEAVE_APP_DEL.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_TRIG_LEAVE_APP_REJECT.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_TRIG_ONDUTYAPP_DELETE.sql
@D:\OracleProjects\SelfService\TRIGGERS\SS_TRIG_ONDUTYAPP_UPDATE.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIGGER1.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIGGER2.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIGGER3.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIGGER4.sql
--@D:\OracleProjects\SelfService\TRIGGERS\TRIGGER5.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIGGER6.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIGGER7.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIG_DESKALLOCATION_LOG.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIG_USB_REQ_LOG.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIG_USERIDS_01.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIG_USERIDS_02.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIG_USERMASTER_LOG.sql
@D:\OracleProjects\SelfService\TRIGGERS\TRIG_VACCINATION_OFFICE_01.sql
@D:\OracleProjects\SelfService\PROCEDURES\CALCALL.sql
@D:\OracleProjects\SelfService\PROCEDURES\CALCALL1.sql
@D:\OracleProjects\SelfService\PROCEDURES\CALCALL2.sql
@D:\OracleProjects\SelfService\PROCEDURES\CALCOT.sql
@D:\OracleProjects\SelfService\PROCEDURES\CHANGE_PASSWORD.sql
@D:\OracleProjects\SelfService\PROCEDURES\CHANGE_SHIFT.sql
@D:\OracleProjects\SelfService\PROCEDURES\DELETEINBETWEENPUNCHLOOP.sql
@D:\OracleProjects\SelfService\PROCEDURES\DELETELEAVE.sql
@D:\OracleProjects\SelfService\PROCEDURES\DELETEOT.sql
@D:\OracleProjects\SelfService\PROCEDURES\DELETE_IN_BETWEEN_PUNCH.sql
@D:\OracleProjects\SelfService\PROCEDURES\DEL_HA_APP.sql
@D:\OracleProjects\SelfService\PROCEDURES\DEL_OD_APP.sql
@D:\OracleProjects\SelfService\PROCEDURES\DEL_SITE_ALLOWANCE_4MONTH.sql
@D:\OracleProjects\SelfService\PROCEDURES\EXECUTE_IMMEDIATE.sql
@D:\OracleProjects\SelfService\PROCEDURES\FILL_HALFDAYMAST_4_SHIFT.sql
@D:\OracleProjects\SelfService\PROCEDURES\FILL_HALFDAY_LUNCH_4_SHIFT.sql
@D:\OracleProjects\SelfService\PROCEDURES\FILL_LUNCHMAST_4_SHIFT.sql
@D:\OracleProjects\SelfService\PROCEDURES\GENERATEPUNCH4ALL.sql
@D:\OracleProjects\SelfService\PROCEDURES\GENERATE_AUTO_PUNCH.sql
@D:\OracleProjects\SelfService\PROCEDURES\GENERATE_AUTO_PUNCH_4OD.sql
@D:\OracleProjects\SelfService\PROCEDURES\GETSHIFT.sql
@D:\OracleProjects\SelfService\PROCEDURES\GET_LEAVE_BALANCE.sql
@D:\OracleProjects\SelfService\PROCEDURES\GET_OT_DATA.sql
@D:\OracleProjects\SelfService\PROCEDURES\INSERTPUNCH.sql
@D:\OracleProjects\SelfService\PROCEDURES\INSERTPUNCHUNIQUE.sql
@D:\OracleProjects\SelfService\PROCEDURES\INSERT_AUTO_PUNCH.sql
@D:\OracleProjects\SelfService\PROCEDURES\INSERT_DATES.sql
@D:\OracleProjects\SelfService\PROCEDURES\MONTHLYPUNCHBAL.sql
@D:\OracleProjects\SelfService\PROCEDURES\N_CFWDDELTAHRS1.sql
@D:\OracleProjects\SelfService\PROCEDURES\N_CFWDDELTAHRS1_20060428.sql
@D:\OracleProjects\SelfService\PROCEDURES\N_CFWD_LWD_DELTAHRS.sql
@D:\OracleProjects\SelfService\PROCEDURES\OPENBAL.sql
@D:\OracleProjects\SelfService\PROCEDURES\OPENBALPL.sql
@D:\OracleProjects\SelfService\PROCEDURES\OPENBALSPECIFIC.sql
@D:\OracleProjects\SelfService\PROCEDURES\OTPERIODS.sql
@D:\OracleProjects\SelfService\PROCEDURES\PROCEDURE1.sql
@D:\OracleProjects\SelfService\PROCEDURES\PROC_DEL_MIDD_PUNCHA.sql
@D:\OracleProjects\SelfService\PROCEDURES\PROC_DM_ACTION.sql
@D:\OracleProjects\SelfService\PROCEDURES\PROC_DM_EMPLEFT.sql
@D:\OracleProjects\SelfService\PROCEDURES\RAJCALCALL1.sql
@D:\OracleProjects\SelfService\PROCEDURES\RESET_PUNCH.sql
--@D:\OracleProjects\SelfService\PROCEDURES\SEND_MAIL_FROM_API.sql
@D:\OracleProjects\SelfService\PROCEDURES\SEND_MAIL_OT_NOT_APPROVED.sql
@D:\OracleProjects\SelfService\PROCEDURES\SEND_TEST_EMAIL_2_USER.sql
@D:\OracleProjects\SelfService\PROCEDURES\SET_OD_ORDER.sql
@D:\OracleProjects\SelfService\PROCEDURES\TO_BE_DELETED_OD2RW.sql
@D:\OracleProjects\SelfService\PROCEDURES\VACCINE_BATCH_SEND_MAIL.sql
@D:\OracleProjects\SelfService\PROCEDURES\WORKEDHRS.sql
@D:\OracleProjects\SelfService\PACKAGES\DESK.sql
@D:\OracleProjects\SelfService\PACKAGES\DESK_MAIL.sql
@D:\OracleProjects\SelfService\PACKAGES\EMP_CARD_RFID.sql
@D:\OracleProjects\SelfService\PACKAGES\GENERATE_CSHARP_CODE.sql
@D:\OracleProjects\SelfService\PACKAGES\HEALTH.sql
@D:\OracleProjects\SelfService\PACKAGES\IMPORT_PUNCH.sql
@D:\OracleProjects\SelfService\PACKAGES\LEAVE.sql
@D:\OracleProjects\SelfService\PACKAGES\LEAVE_ADJ.sql
@D:\OracleProjects\SelfService\PACKAGES\LEAVE_BAL.sql
@D:\OracleProjects\SelfService\PACKAGES\LEAVE_MONTHLY_CREDIT.sql
@D:\OracleProjects\SelfService\PACKAGES\LESSON.sql
@D:\OracleProjects\SelfService\PACKAGES\MEET.sql
@D:\OracleProjects\SelfService\PACKAGES\MGMT_REQUEST.sql
@D:\OracleProjects\SelfService\PACKAGES\MGMT_USERS.sql
@D:\OracleProjects\SelfService\PACKAGES\MISC.sql
@D:\OracleProjects\SelfService\PACKAGES\MIS_PUNCH.sql
@D:\OracleProjects\SelfService\PACKAGES\NETWORK_DATA_PRINTER.sql
@D:\OracleProjects\SelfService\PACKAGES\NU_EMP.sql
@D:\OracleProjects\SelfService\PACKAGES\OD.sql
@D:\OracleProjects\SelfService\PACKAGES\PENDING_APPROVALS.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_09794.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_9794_NU.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_9794_TS.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_9794_USER_MGMT.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_ABSENT.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_ABSENT_TS.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_BATCH_LOG.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_LEAVE_REP.sql
@D:\OracleProjects\SelfService\PACKAGES\PKG_SHIFT.sql
@D:\OracleProjects\SelfService\PACKAGES\PN.sql
@D:\OracleProjects\SelfService\PACKAGES\PRINT_LOG_MIS.sql
@D:\OracleProjects\SelfService\PACKAGES\SA.sql
@D:\OracleProjects\SelfService\PACKAGES\SELF_ATTENDANCE.sql
@D:\OracleProjects\SelfService\PACKAGES\SS.sql
@D:\OracleProjects\SelfService\PACKAGES\SS_MAIL.sql
@D:\OracleProjects\SelfService\PACKAGES\SS_PHONE.sql
@D:\OracleProjects\SelfService\PACKAGES\SS_TS_LEAVE_COMPARE.sql
@D:\OracleProjects\SelfService\PACKAGES\SUM_WRK_HRS.sql
--@D:\OracleProjects\SelfService\PACKAGES\SWP.sql
--@D:\OracleProjects\SelfService\PACKAGES\SWP_OFFICE_VACCINE.sql
--@D:\OracleProjects\SelfService\PACKAGES\SWP_OFFICE_VACCINE_BATCH_2.sql
--@D:\OracleProjects\SelfService\PACKAGES\SWP_TRAINING.sql
--@D:\OracleProjects\SelfService\PACKAGES\SWP_USERS.sql
--@D:\OracleProjects\SelfService\PACKAGES\SWP_VACCINEDATE.sql
---@D:\OracleProjects\SelfService\PACKAGES\SWP_VACCINE_REMINDER.sql
@D:\OracleProjects\SelfService\PACKAGES\TT1.sql
@D:\OracleProjects\SelfService\PACKAGES\USB.sql
@D:\OracleProjects\SelfService\PACKAGES\USER_PROFILE.sql
@D:\OracleProjects\SelfService\PACKAGES\WFH_ATTENDANCE.sql
--@D:\OracleProjects\SelfService\PACKAGES\XLSX_READ.sql
--@D:\OracleProjects\SelfService\PACKAGES\XL_BLOB.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\DESK.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\DESK_MAIL.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\EMP_CARD_RFID.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\GENERATE_CSHARP_CODE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\HEALTH.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\IMPORT_PUNCH.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\LEAVE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\LEAVE_ADJ.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\LEAVE_BAL.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\LEAVE_MONTHLY_CREDIT.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\LESSON.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\MEET.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\MGMT_REQUEST.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\MGMT_USERS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\MISC.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\MIS_PUNCH.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\NETWORK_DATA_PRINTER.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\NU_EMP.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\OD.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PENDING_APPROVALS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_09794.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_9794_NU.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_9794_TS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_9794_USER_MGMT.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_ABSENT.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_ABSENT_TS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_BATCH_LOG.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_LEAVE_REP.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PKG_SHIFT.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PN.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\PRINT_LOG_MIS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SA.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SELF_ATTENDANCE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SS_MAIL.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SS_PHONE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SS_TS_LEAVE_COMPARE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SUM_WRK_HRS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SWP.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SWP_OFFICE_VACCINE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SWP_OFFICE_VACCINE_BATCH_2.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SWP_TRAINING.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SWP_USERS.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SWP_VACCINEDATE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\SWP_VACCINE_REMINDER.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\TT1.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\USB.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\USER_PROFILE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\WFH_ATTENDANCE.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\XLSX_READ.sql
@D:\OracleProjects\SelfService\PACKAGE_BODIES\XL_BLOB.sql
@D:\OracleProjects\SelfService\FUNCTIONS\AUTOAPPROVAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\AVAILEDLUNCHTIME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\AVAILEDLUNCHTIME1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\AVAILEDLUNCHTIME1_COPY.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CASUALLEAVECHECK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CFWDDELTAHRSTEST.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CFWDDELTAHRSTEST1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CFWDOTDELTAHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CFWD_DHRS_WEEK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CHECKAPP.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CHECKHOLIDAY.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CHECKPLCLDIFF.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CLOSINGCLBAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CLOSINGCOBAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CLOSINGEXBAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CLOSINGOHBAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CLOSINGPLBAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CLOSINGSLBAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\CLPLDIFF.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DELTAHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DELTAHRS1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_GETPCNAME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_GETUSER.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_GET_EMP_OFFICE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_IS_DESK_OCCUPIED.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_IS_NU_USER.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_IS_USER_DEPU.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_IS_USER_REJOIN.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_IS_USER_RESIGN.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_LASTDESK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_OFFICE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\DM_PREV_DESK_DEL_DATE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\EARLYGO.sql
@D:\OracleProjects\SelfService\FUNCTIONS\EARLYGO1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ESTIMATEDLUNCHTIME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ESTIMATEDLUNCHTIME1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ESTIMATEDWRKHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\EXCHECK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\FIRSTLASTPUNCH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\FIRSTLASTPUNCH1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\FIRSTLASTPUNCHDATA.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GEN_NUMBERS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETABSENT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETABSENTDATE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETABSENTDATE_SHIFT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETCONSECUTIVECL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETCONSECUTIVECL1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETDIFFPLSLCL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETDIFFSICK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETDISCREPANCYCNT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETEMPNAME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETLASTDAYOFWEEK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETLASTDAYOFWEEK1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETLASTWORKINGDAY.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETLCOMEAPPCNTR.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETLEAVEPERIOD.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETODHH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETODMM.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETPLLEAVECOUNT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETSHIFT1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETSHIFTINTIME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETSHIFTINTIME1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETSHIFTOUTTIME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GETSLEAVEAPPCNTR.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_EMP_COMPANY.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_EMP_DEPT.sql
--@D:\OracleProjects\SelfService\FUNCTIONS\GET_EMP_NAME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_EMP_PEN_LVE_4_MONTH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_HOLIDAY.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_MGR_USERID.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_MUSTER_STATUS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_PARENT_NAME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_PL_LEAVE_COUNT_IN_YEAR.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_PROJECT_DESC.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_PUNCH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_PUNCH_MONTH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_PUNCH_NUM.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_PUNCH_SEC.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_SITE_ALLOWANCE_DUE_DATE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_TEL_PHONE_COUNTRY_CODE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_TIME_SHEET_EXTRA_HRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_TIME_SHEET_EXTRA_HRS_TOT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_TIME_SHEET_WORK_HRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_TIME_SHEET_WORK_HRS_TOT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\GET_TIME_SHET_EXTRA_HRS_TOT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\HOLIDAYSBETWEEN.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISABSENT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISEXTRAHOURS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLASTDAYOFMONTH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLASTWORKDAY.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLASTWORKDAY1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLCOMEEGOAPP.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLDT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLDT_APPL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLEAVEDEPUTOUR.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISLEAVENEGATIVE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISSHIFT_INMONTH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\ISSLEAVEAPP.sql
@D:\OracleProjects\SelfService\FUNCTIONS\IS_GRADE_X.sql
@D:\OracleProjects\SelfService\FUNCTIONS\IS_LEAVE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\IS_ODD_PUNCH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\LASTDAY_CFWD_DHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\LASTDAY_CFWD_DHRS1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\LATECOME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\LATECOME1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\LC_APPCOUNT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\MAXPUNCH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\MAXPUNCH1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\MISSEDPUNCH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_CFWDDELTAHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_DELTAHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_GETENDDATE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_GETSTARTDATE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_IS_EMP_ABSENT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_LEAVE_SUM.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_LUNCH_TIME.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_MAXPUNCH.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_MEAL_VR_LEAVE_BAL.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_OTPERIOD.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_OT_4_TRAINING.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_SUM_SLAPP_COUNT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_TIMESHEETALLOWED.sql
@D:\OracleProjects\SelfService\FUNCTIONS\N_WORKEDHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\OPENBALPLFUNC.sql
@D:\OracleProjects\SelfService\FUNCTIONS\OTPERIOD.sql
@D:\OracleProjects\SelfService\FUNCTIONS\OTPERIOD1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\OTPERIOD2.sql
@D:\OracleProjects\SelfService\FUNCTIONS\OTPERIODNEW.sql
@D:\OracleProjects\SelfService\FUNCTIONS\PENALTYLEAVE.sql
@D:\OracleProjects\SelfService\FUNCTIONS\PENALTYLEAVE1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\PLCLCOMBINECHECK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\PUNCHCOUNT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\SANJAYX.sql
@D:\OracleProjects\SelfService\FUNCTIONS\SEC_TO_CHAR.sql
@D:\OracleProjects\SelfService\FUNCTIONS\SHIFT_WORK_HRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\SLCHECK.sql
@D:\OracleProjects\SelfService\FUNCTIONS\SL_APPCOUNT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\SS_MONTH_WRK_HRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\SUMSL_APPCOUNT.sql
@D:\OracleProjects\SelfService\FUNCTIONS\TOTWRKHRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\TO_HRS.sql
@D:\OracleProjects\SelfService\FUNCTIONS\WORKEDHRS1.sql
@D:\OracleProjects\SelfService\FUNCTIONS\WORKEDHRS11.sql
@D:\OracleProjects\SelfService\FUNCTIONS\WORKEDHRS2.sql
@D:\OracleProjects\SelfService\FUNCTIONS\WORKEDHRS3.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_UP_TO_20071231.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DESKREFILL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_VACCINE_COVID_EMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\ASSETADMIN1.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\PF_CONSENT_2011.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HOLIDAY_ATTENDANCE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DELTAHRSBAL_OT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_PENDING_PC_LOCK_20150925.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_9794_ROLE_MASTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_REPORT_FIELDS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_VACCINATION_OFFICE_FAMILY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DESKASSIGNMENT_20091126.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_BUS_ROUTES.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PHOTOCONSENT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_ONDUTYAPP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LUNCHMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_20110426.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVELEDG.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DELEGATE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PORTAL_NEWS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_EXTRAHOLIDAY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_9794_PUNCH_GENERATE_4_BT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETMOVE_TRAN_16APR10.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_ALLOWANCE_TRANS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_EMPLPHOTOS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_NAVRATRI_2011.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DAYS_DETAILS_1.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\AD_TEMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_EMP_RESPONSE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DESKASSINMENT_20091118.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CLINIC.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_OTMASTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_LAPTOP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVEAPP_DELETED.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\AD_MOBILE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_VACCINATION_OFFICE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_MONTHLY_CREDIT_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_ALLOWANCE_ROLLOVER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HSE_QUIZ_2.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_BUSLATE_LAYOFF_DETAIL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVE_BAL_MAX_LIMIT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\AD_SYNC_20151211.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_USER_DEPT_RIGHTS_20150825.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DMS_STATUS2020.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_PENDING_PC_LOCK.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETADD.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_LOGINRIGHT_20150925.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CONTMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SECRETARY_20081011.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_OTDETAIL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_NEWJOIN_TRANS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_ALL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_REVIEWREMARKS_20141122.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CLINIC_DETAIL_20101129.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVETYPE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_ASSIGNMENT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\QUIZ_MASTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_DESKLOCK.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_CATEGORY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_9794_AUTOPUNCH_DEL_BETWEEN.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETMODIFICATION.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DESKASSIGNMENT_20091127.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HSE_QUIZ.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVE_UPLOAD_LOG.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_BACKUP_20100226.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_ISP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HSESUGG.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_MEMBERS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_AUTO.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_BATCH_ERROR_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_TASKFORCETRAN.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_SECRETARY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PAYROLLTYPEMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_USER_DEPT_RIGHTS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_ALLOWANCE_PROCESSED.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_USER_TYPE_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_TRAVELREQ.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_COUNTRY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_VACCINATION_OFFICE_210612.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HEALTH_EMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_NAVRATRI_2018.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HEALTH_HRD_24FEB15.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETADD_BACKUP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_AUTO_TYPE_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SHIFTMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\QUIZ_PRQ03.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVEAPP_REJECTED.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_ABSENT_LOP_REVERSE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_SOURCEDESK.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_ALLOWANCE_PERIOD_ADJ.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETMOVE_TRAN_HIST_051216.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\USERIDS_20210510.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\AD_DETAILS_20151211.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PL_REVISION_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_BATCH_LOG_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_REJOIN.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVEBAL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_BATCH_TYPE_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_NEWJOIN_EMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\AD_SYNC.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_RECORDED_20150123.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_FUNCTIONCODE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_VACCINE_DATES.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_REVIEWER_DOC.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CLINIC_DETAIL_20141210.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HALFDAYMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DEPU_HIST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_NEWJOIN_TRANS_20150401.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_ONDUTY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_ACCENTURE_EMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_RELATION_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_BAL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_TRAN_HIST_20100416.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ACTION_TYPE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_BUSLATE_LAYOFF_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CLINIC_LIMIT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_TPL_VACCINE_BATCH_EMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HSE_INCIDENTREPORT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SWIPE_MACH_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HEALTH_EMP_24FEB15.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_EMP_LEFT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_9794_EMP_ROLES.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETADD_16APR10.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_BL_LO_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_9794_PUNCH_REQUIRED_1.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVE_ADJ_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETMOVE_TRAN.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_OT_DETAILS_4_YEAR.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_LOGINRIGHT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DELTAHRSBAL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETMOVE_TRAN_HISTORY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_EMP_TRANSFER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\USERIDS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_REPORT_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CONSCENT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_APPROVER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_TEMP_DESK_ASSIGN.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\AD_TEMP_1.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_9794_EMP_LIST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\EMP_PAYROLL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SECRETARY_REP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\DATA001.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_MUSTER_20120310.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_DESKMASTER_VISIO_ID.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_LOC_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SECRETARY_DESK.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_PCNAME.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVE_ADJ.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\AD_DETAILS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_ABSENT_TS_LEAVE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CLINIC_DETAIL_20161114.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_TPL_VACCINE_BATCH.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_CLINIC_DETAIL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_MUSTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_WFH.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_NAVRATRI_2017.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_20100329.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HEALTH_RPT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SUGGESTION.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_MUSTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_TABLETAG.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_REVIEWREMARKS_20150123.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_VACCINE_MASTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DESKASSIGNMENT_25NOV_BACUP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_DESKLOCK_BACKUP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_FILE_UPLOAD_LOG.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_BATCH_STATUS_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_FIESTA_2011.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_MANUAL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_200604_17_18_19.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_ABSENT_TS_LOP_REVERSE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\ASSETADMIN.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_MUSTER_4ALLOWANCE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_IT_PREREQUISITES.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HSE_QUIZ_3.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PL_REVISION_APP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_DESKLOCK_16APR10.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DATATYPE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAD_APPROVER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSET_OFFICE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\QUIZ_TP_XLS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_TARGETDESK.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_FEEDBACK.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_DESKLOCK_ERR.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HR_FRM_MENU.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_RECORDED.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_MUSTER_TEMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVEAPP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_NAVRATRI_2019.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_USERMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_USB_REQUEST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_ORIGINATOR.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_DESKMASTER_VISIO_BACKUP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DESKASSIGNMENT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETADD_ERR.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SITE_EMPLOYEE.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HEALTH_BILLMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_RECORDED_20141122.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_ONDUTYMAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HEALTH_BILL.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_EMP_TRAINING_TEMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LOCK_OT_HRS_DOWNLOAD_PERIOD.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_EMP_WITH_COMP_MOB.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_SHIFTMAST_20090401.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LDAP_LIST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_EMP_COMP_LASTDATE_4_MUSTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DEPU.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\QUIZ_PRQ02.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_GUESTMASTER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HEALTH_HRD.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_DAYS_DETAILS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_9794_PUNCH_DEL_BETWEEN.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_OFFICE_MAST.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_OT_DOWNLOAD_DBF_LOCK.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_NAVRATRI.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_EMP_TRAINING.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_HOLIDAY_15NOV2012.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_EMAILID.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\PRINT_LOG.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\LL_REVIEWREMARKS.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\EMP_WEEK_SELECTED.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\FTP_ADMIN_USER.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_LAPTOP_PERMT.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_LEAVE_UPLOAD_TEMP.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCHBACKUP_20070711.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SWP_VACCINATION_OFFICE_BATCH_2.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_EMPADD.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_FILE_UPLOAD_PARAM.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_PUNCH_BACKUP_20061031.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSET_MODIFY.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\SS_TRAVELREQ_200100218.sql
@D:\OracleProjects\SelfService\CONSTRAINTS\XDM_ASSETTYPE.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_9794_EMP_ROLES.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_BATCH_LOG_DETAILS.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_BATCH_LOG_MAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_BUSLATE_LAYOFF_DETAIL.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_BUSLATE_LAYOFF_MAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_HALFDAYMAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_LEAVEAPP.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_LEAVELEDG.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_LEAVE_ADJ.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_LEAVE_UPLOAD_TEMP.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_LUNCHMAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_ONDUTY.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_ONDUTYAPP.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_ONDUTYMAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_OTDETAIL.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_PUNCH_AUTO.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_REPORT_FIELDS.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_SITE_EMPLOYEE.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_SITE_MAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_SITE_MUSTER.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_SITE_MUSTER_TEMP.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_SWIPE_MACH_MAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SS_USERMAST.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SWP_TPL_VACCINE_BATCH_EMP.sql
@D:\OracleProjects\SelfService\REF_CONSTRAINTS\SWP_VACCINE_DATES.sql
