--------------------------------------------------------
--  File created - Monday-October-04-2021   
--------------------------------------------------------
REM INSERTING into TCMPL_APP_CONFIG.SEC_ACTIONS
SET DEFINE OFF;
REM INSERTING into TCMPL_APP_CONFIG.SEC_MODULE_ROLE_ACTIONS
SET DEFINE OFF;
REM INSERTING into TCMPL_APP_CONFIG.SEC_MODULE_ROLES
SET DEFINE OFF;
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M04','R004','M04R004');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M04','R011','M04R011');
REM INSERTING into TCMPL_APP_CONFIG.SEC_MODULE_USER_ROLES
SET DEFINE OFF;
Insert into TCMPL_APP_CONFIG.SEC_MODULE_USER_ROLES (MODULE_ID,ROLE_ID,EMPNO,PERSON_ID,MODULE_ROLE_KEY_ID) values ('M04','R011','02320','01009257','M04R011');
REM INSERTING into TCMPL_APP_CONFIG.SEC_MODULES
SET DEFINE OFF;
Insert into TCMPL_APP_CONFIG.SEC_MODULES (MODULE_ID,MODULE_NAME,MODULE_LONG_DESC,MODULE_IS_ACTIVE,MODULE_SCHEMA_NAME,FUNC_TO_CHECK_USER_ACCESS,MODULE_SHORT_DESC) values ('M04','SELFSERVICE','Attendance, Leave Management','OK','SELFSERVICE',null,'SelfService');
