--------------------------------------------------------
--  DDL for Procedure STK_CLOSING_BALANCE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "ITINV_STK"."STK_CLOSING_BALANCE" (
    PARAM_ITEM    IN OUT VARCHAR2 ,
    PARAM_SUBITEM IN OUT VARCHAR2 ,
    PARAM_BALANCE OUT NUMBER )
AS
  qty_request    NUMBER;
  TOTAL_issued   NUMBER;
  TOTAL_STOCK_IN NUMBER;
  main_reult     NUMBER;
  BALANCE        NUMBER;
  SUB            VARCHAR2(2000);
  ITEM           VARCHAR2(2000);
  TAB_CLO        NUMBER;
BEGIN
  SELECT COUNT(*) INTO TAB_CLO FROM STK_CLOSING;
  IF TAB_CLO != 0 THEN
    SELECT SUM(STK_CLOSING.BALANCE)
    INTO BALANCE
    FROM STK_CLOSING
    WHERE ITEM =upper(PARAM_ITEM)
    AND SUBITEM=upper(PARAM_SUBITEM);
  END IF;
  SELECT SUM(STK_REQUEST.QUANTITY)
  INTO TOTAL_issued
  FROM STK_REQUEST
  WHERE STK_REQUEST.ISSUED     ='ISSUED'
  AND STK_REQUEST.ITEM_TYPE    =upper(PARAM_ITEM)
  AND STK_REQUEST.SUB_ITEM_TYPE=upper(PARAM_SUBITEM) ;
  SELECT SUM(STK_STOCK_IN.QUANTITY)
  INTO TOTAL_STOCK_IN
  FROM STK_STOCK_IN
  WHERE ITEM_TYPE  =upper(PARAM_ITEM)
  AND SUB_ITEM_TYPE=upper(PARAM_SUBITEM);
  SELECT S_SUB_ITEM_TYPE
  INTO SUB
  FROM STK_SUB_ITEM_TYPE
  WHERE SKEY_ID= upper(PARAM_SUBITEM) ;
  SELECT ITEMS_TYPE
  INTO ITEM
  FROM STK_ITEM_TYPE_MASTER p
  WHERE p.KEY_ID     = upper(PARAM_ITEM) ;
  PARAM_ITEM        :=ITEM;
  PARAM_SUBITEM     :=SUB;
  IF(TOTAL_STOCK_IN IS NULL) THEN
    TOTAL_STOCK_IN  :=0;
  END IF;
  IF(TOTAL_issued IS NULL) THEN
    TOTAL_issued  :=0;
  END IF;
  IF(TOTAL_issued IS NOT NULL AND TOTAL_STOCK_IN IS NOT NULL) THEN
    PARAM_BALANCE :=TOTAL_STOCK_IN - TOTAL_issued ;
  ELSE
    PARAM_BALANCE:=TOTAL_STOCK_IN ;
  END IF;
END STK_CLOSING_BALANCE;

/
