--------------------------------------------------------
--  DDL for View COSTMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMMONMASTERS"."COSTMAST" ("COSTCODE", "NAME", "ABBR", "HOD", "HOD_ABBR", "DY_HOD", "NOOFEMPS", "COSTGROUP", "GROUPS", "TM01_GRP", "TMA_GRP", "COST_TYPE", "ACTIVITY", "GROUP_CHART", "COSTGRP", "ITALIAN_NAME", "BU", "CHANGED_NEMPS", "INOFFICE", "SECRETARY", "COMP", "ACTIVE", "SDATE", "EDATE", "PHASE", "SAPCC", "CLOSED", "PARENT_COSTCODE", "NOOFCONS", "TCM_CC", "TCM_ACT_PH", "TCM_PAS_PH", "TCM_CC_DESC", "PO") AS 
  select "COSTCODE","NAME","ABBR","HOD","HOD_ABBR","DY_HOD","NOOFEMPS","COSTGROUP","GROUPS","TM01_GRP","TMA_GRP","COST_TYPE","ACTIVITY","GROUP_CHART","COSTGRP","ITALIAN_NAME","BU","CHANGED_NEMPS","INOFFICE","SECRETARY","COMP","ACTIVE","SDATE","EDATE","PHASE","SAPCC","CLOSED","PARENT_COSTCODE","NOOFCONS","TCM_CC","TCM_ACT_PH","TCM_PAS_PH","TCM_CC_DESC","PO" from timecurr.costmast
;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "TCMPL_AFC" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "ITINV_STK" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "AMS" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "DMS" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "IOT_TCMPL" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "STATIONERY" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "TCMPL_HR" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "SELFSERVICE" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "RWM3";
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "REMOTEWORKING";
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "HR_MBO";
  GRANT SELECT ON "COMMONMASTERS"."COSTMAST" TO "EIPM_HSE";
