--------------------------------------------------------
--  DDL for View CV_EMPLMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMMONMASTERS"."CV_EMPLMAST" ("YEAR", "EMPNO", "FULLNAME", "NATIONALITY", "BIRTHDATE", "PER_ADD1", "PER_ADD2", "PER_ADD3", "PER_STATE", "PER_PIN", "PER_STD", "PER_TELNO", "RES_ADD1", "RES_ADD2", "RES_ADD3", "RES_STATE", "RES_PIN", "RES_STD", "RES_TELNO", "PASSPORTNO", "PASSPORTISSUEDATE", "PASSPORTEXPDATE", "PASSPORTISSUEPLACE", "JOININGDATE", "PRESENTPOSITION", "FROMYEAR", "RESPONSIBILITY", "DATEOFISSUE", "DEPT", "MOTHERTONGUE", "NOTES", "ISSUEDATE", "HOD_APPRL", "HRD_APPRL", "LOCKED", "UNLOCK") AS 
  SELECT  YEAR ,
     EMPNO ,
     FULLNAME ,
     NATIONALITY ,
     BIRTHDATE ,
     PER_ADD1 ,
     PER_ADD2 ,
     PER_ADD3 ,
     PER_STATE ,
     PER_PIN ,
     PER_STD ,
     PER_TELNO ,
     RES_ADD1 ,
     RES_ADD2 ,
     RES_ADD3 ,
     RES_STATE ,
     RES_PIN ,
     RES_STD ,
     RES_TELNO ,
     PASSPORTNO ,
     PASSPORTISSUEDATE ,
     PASSPORTEXPDATE ,
     PASSPORTISSUEPLACE ,
     JOININGDATE ,
     PRESENTPOSITION ,
     FROMYEAR ,
     RESPONSIBILITY ,
     DATEOFISSUE ,
     DEPT ,
     MOTHERTONGUE ,
     NOTES ,
     ISSUEDATE ,
     HOD_APPRL ,
     HRD_APPRL ,
     LOCKED ,
     UNLOCK 
  FROM timecurr.cv_emplmast
;
  GRANT SELECT ON "COMMONMASTERS"."CV_EMPLMAST" TO "SELFSERVICE";
