--------------------------------------------------------
--  DDL for View DESGMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMMONMASTERS"."DESGMAST" ("DESGCODE", "DESG", "ORD", "SUBCODE") AS 
  select "DESGCODE","DESG","ORD","SUBCODE" from timecurr.desgmast
;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "TCMPL_AFC" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "ITINV_STK" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "AMS" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "DMS" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "IOT_TCMPL" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "STATIONERY" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "TCMPL_HR" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "SELFSERVICE" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "RWM3";
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "REMOTEWORKING";
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "HR_MBO";
  GRANT SELECT ON "COMMONMASTERS"."DESGMAST" TO "EIPM_HSE";
