--------------------------------------------------------
--  DDL for View EMP_DETAILS_PASSPORT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMMONMASTERS"."EMP_DETAILS_PASSPORT" ("EMPNO", "NAME", "PARENT", "ASSIGN", "PASSPORT_NO", "ISSUE_DATE", "EXPIRY_DATE", "PASSPORT_ISSUED_AT") AS 
  SELECT /*+ NOPARALLEL(EMP_DETAILS, EMPLMAST, ) */ EMPLMAST.EMPNO, EMPLMAST.NAME, EMPLMAST.PARENT, EMPLMAST.ASSIGN, EMP_DETAILS.PASSPORT_NO, EMP_DETAILS.ISSUE_DATE, EMP_DETAILS.EXPIRY_DATE, EMP_DETAILS.PASSPORT_ISSUED_AT
FROM EMP_DETAILS , EMPLMAST
WHERE ( (EMP_DETAILS.EMPNO = EMPLMAST.EMPNO) AND
(EMP_DETAILS.PASSPORT_NO IS NOT NULL) and emplmast.status=1 )
ORDER BY EMPLMAST.EMPNO ASC

;
  GRANT SELECT ON "COMMONMASTERS"."EMP_DETAILS_PASSPORT" TO "SELFSERVICE";
