--------------------------------------------------------
--  DDL for View EMP_DETAILS_FAMILY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMMONMASTERS"."EMP_DETAILS_FAMILY" ("EMPNO", "NAME", "ASSIGN", "PARENT", "MEMBER", "DOB", "REMARKS", "OCCUPATION", "RELATION") AS 
  SELECT /*+ NOPARALLEL(B, A, EMP_OCCUPATION, EMP_RELATION_MAST, ) */ A.EMPNO, A.NAME, A.ASSIGN, A.PARENT, B.MEMBER, B.DOB, B.REMARKS, EMP_OCCUPATION.DESCRIPTION OCCUPATION, EMP_RELATION_MAST.DESCRIPTION RELATION
FROM EMP_FAMILY B, EMPLMAST A, EMP_OCCUPATION , EMP_RELATION_MAST
WHERE ( (B.EMPNO = A.EMPNO) AND
(EMP_OCCUPATION.CODE = B.OCCUPATION) AND
(EMP_RELATION_MAST.CODE = B.RELATION) AND
(A.STATUS = 1) 
and a.emptype = 'R'
)
ORDER BY A.EMPNO ASC
;
  GRANT SELECT ON "COMMONMASTERS"."EMP_DETAILS_FAMILY" TO "SELFSERVICE";
