--------------------------------------------------------
--  DDL for View EMPLMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMMONMASTERS"."EMPLMAST" AS 
  (SELECT EMPNO,
    NAME,
    ABBR,
    EMPTYPE,
    EMAIL,
    ASSIGN,
    PARENT,
    DESGCODE,
    PASSWORD,
    DOB,
    DOJ,
    DOL,
    DOR,
    COSTHEAD,
    COSTDY,
    PROJMNGR,
    PROJDY,
    DBA,
    DIRECTOR,
    STATUS,
    SUBMIT,
    OFFICE,
    PROJNO,
    DIROP,
    AMFI_USER,
    AMFI_AUTH,
    SECRETARY,
    DO,
    INV_AUTH,
    JOB_INCHARGE,
    COSTOPR,
    MNGR,
    IPADD,
    PWD_CHGD,
    DOC,
    GRADE,
    PROC_OPR,
    REPORTO,
    COMPANY,
    TRANS_OUT,
    TRANS_IN,
    HR_OPR,
    SEX,
    USER_DOMAIN,
    WEB_ITDECL,
    CATEGORY,
    ESI_COVER,
    EMP_HOD,
    SEATREQ,
    NEWEMP,
    ONDEPUTATION,
    OLDCO,
    MARRIED,
    JOBTITLE,
    EOW,
    EOW_DATE,
    EOW_WEEK,
    LASTNAME,
    FIRSTNAME,
    MIDDLENAME,
    SAPEMP,
    PFSLNO,
    ADD1,
    ADD2,
    ADD3,
    ADD4,
    PINCODE,
    CONTRACT_END_DATE,
    NVL(jobGroup,'NA')             AS jobGroup,
    NVL(JobGroupDesc,'NA')         AS JobGroupDesc,
    NVL(JOBDISCIPLINE ,'NA')       AS JOBDISCIPLINE,
    NVL(JOBDISCIPLINEDESC,'NA')    AS JOBDISCIPLINEDESC ,
    NVL(JOBSUBDISCIPLINE,'NA')     AS JOBSUBDISCIPLINE,
    NVL(JOBSUBDISCIPLINEDESC,'NA') AS JOBSUBDISCIPLINEDESC ,
    NVL(JOBCATEGORY ,'NA')         AS JOBCATEGORY,
    NVL(JOBCATEGOORYDESC ,'NA')    AS JOBCATEGOORYDESC,
    NVL(Jobsubcategory,'NA')       AS Jobsubcategory,
    NVL(Jobsubcategorydesc,'NA')   AS Jobsubcategorydesc,
    itno,
    lastday,
    subcontract,
    NVL(no_tcm_upd,0) AS no_tcm_upd,
    payroll,
    expatriate,
    metaid,
    personid,
    CID,
    ACCTNO BANKACNO,
    IFSCNO,
    get_personal_email(EMPNO) PER_EMAIL,
    get_ad_email(empno) ad_email,
    userid,
    pwd,
    reporting,
    jobtitle_code
  FROM TimeCurr.Emplmast
  )
;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "TCMPL_AFC" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "ITINV_STK" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "AMS" WITH GRANT OPTION;
  GRANT UPDATE ("PASSWORD") ON "COMMONMASTERS"."EMPLMAST" TO "SELFSERVICE";
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "DMS" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "OSD";
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "EIPM";
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "ITDECL";
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "IOT_TCMPL" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "STATIONERY" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "TCMPL_HR" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "SELFSERVICE" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "RWM3";
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "REMOTEWORKING";
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "HR_MBO";
  GRANT SELECT ON "COMMONMASTERS"."EMPLMAST" TO "EIPM_HSE";
