--------------------------------------------------------
--  Constraints for Table SEC_ACTIONS
--------------------------------------------------------

  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ACTIONS" MODIFY ("ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ACTIONS" MODIFY ("ACTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ACTIONS" MODIFY ("ACTION_DESC" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ACTIONS" MODIFY ("ACTION_IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ACTIONS" ADD CONSTRAINT "SEC_ACTONS_PK" PRIMARY KEY ("MODULE_ID", "ACTION_ID")
  USING INDEX  ENABLE;
