--------------------------------------------------------
--  Constraints for Table SEC_ROLES
--------------------------------------------------------

  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ROLES" ADD CONSTRAINT "SEC_ROLES_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ROLES" MODIFY ("ROLE_IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ROLES" MODIFY ("ROLE_DESC" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
