--------------------------------------------------------
--  Constraints for Table SEC_MODULES
--------------------------------------------------------

  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULES" MODIFY ("MODULE_IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULES" MODIFY ("MODULE_LONG_DESC" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULES" MODIFY ("MODULE_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULES" ADD CONSTRAINT "SEC_MODULE_PK" PRIMARY KEY ("MODULE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULES" MODIFY ("MODULE_ID" NOT NULL ENABLE);
