--------------------------------------------------------
--  Constraints for Table SEC_MODULE_ROLES
--------------------------------------------------------

  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULE_ROLES" MODIFY ("KEY_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULE_ROLES" ADD CONSTRAINT "SEC_MODULE_ROLES_PK" PRIMARY KEY ("MODULE_ID", "ROLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULE_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULE_ROLES" MODIFY ("MODULE_ID" NOT NULL ENABLE);
