--------------------------------------------------------
--  File created - Wednesday-February-09-2022   
--------------------------------------------------------
@E:\Oracle Versioning New\Timecurr\TYPES\NGTS_ID_OUT_RECORD.sql
@E:\Oracle Versioning New\Timecurr\TYPES\NGTS_ID_OUT_TABLE.sql
@E:\Oracle Versioning New\Timecurr\TYPES\T_REC_YYMM.sql
@E:\Oracle Versioning New\Timecurr\TYPES\T_TAB_YYMM.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\CREATE_TCM_FILE.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\C_INS_NEW_PROJECT.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\C_INS_NEW_PROJECT_BUDGMAST.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\C_INS_NEW_PROJECT_OPENMAST.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\DT_DROPUSEROBJECTBYID.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\DT_SETPROPERTYBYID.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\GENERATE_DELTA_INVOICES.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\GENERATE_WORKFILE_FINAL.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\GENINS.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\INSERT_NEW_PROJECT.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\INSERT_PRJC_INTO_NEW_EXPTPRJC.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\INS_NEW_PRJ_FORBUDG_INPROJMAST.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\INS_NEW_PRJ_FOROPEN_INPROJMAST.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\OLD_GENERATE_DELTA_INVOICES.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\OLD_GENERATE_WORKFILE_FINAL.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\POST_INVOICES.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\PROCDEL.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\PROCDEL1.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\REMOVE_FROM_EXPT_INSERT_INTO_P.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\REMOV_FRM_EXPT_INS_INTO_P_COST.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\REPOST.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\ROLLBACK_WORKFILE.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\SEND_MAIL_EMPLOYEE_ADDED.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\SEND_MAIL_REVISE_JOB.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\SEND_TEST_EMAIL_2_USER.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\TEST_EMAIL.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\UPDATEMAX6.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\UPDATENOOFEMPS.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\UPDATE_COMPANY_IN_TIMEMAST.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\UPDATE_RESOURCE.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\UPDATE_TMRAPPER.sql
@E:\Oracle Versioning New\Timecurr\PROCEDURES\UPDATE_TOTALS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\CONTRACTPKEY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\DEPUTATION.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\GENERATE_CSHARP_CODE.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_COMMON.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_COSTMAST_AFC.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_COSTMAST_COSTCONTROL.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_COSTMAST_HOD.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_COSTMAST_MAIN.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_EMPLMAST_MAIN.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_EMPLMAST_REPORT.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_EMPLMAST_TABS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_HOLIDAY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\HR_PKG_HRMASTERS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_BULK_TIMESHEET.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_CHECK_AUTH_RIGHTS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_EMP_ACCESS_ROLES.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_EMP_TIMESHEET.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_PRADEEP_OLD.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_PROJECT_FREEZE.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_ROLES.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_SANJAY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_TIMESHEET.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\NGTS_USERS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PKG_09794.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PKG_CV.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PKG_JOB.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PKG_MAIL.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PKG_SENDMAIL.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PKG_SYSTEMGRANTS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PKG_TM.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\PM_RND.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_GTT.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_PROCO.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_REPORTS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_REPORTS_B.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_REPORTS_C.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_REPORTS_GEN.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_SELECT_LIST_QRY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\RAP_UNPIVOT_TMDAILY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_MAINTENANCE.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDD.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDE.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDG.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDI.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDJ.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDM_NOTIFICATION_PKG.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDN.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDP.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDU.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VDV.sql
@E:\Oracle Versioning New\Timecurr\PACKAGES\SMP_VD_UTIL.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\DEPUTATION.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\GENERATE_CSHARP_CODE.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_COMMON.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_COSTMAST_AFC.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_COSTMAST_COSTCONTROL.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_COSTMAST_HOD.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_COSTMAST_MAIN.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_EMPLMAST_MAIN.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_EMPLMAST_REPORT.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_EMPLMAST_TABS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_HOLIDAY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\HR_PKG_HRMASTERS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\IOT_SWP_PRIMARY_WORKSPACE.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\IOT_SWP_SELECT_LIST_QRY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_BULK_TIMESHEET.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_CHECK_AUTH_RIGHTS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_EMP_ACCESS_ROLES.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_EMP_TIMESHEET.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_PRADEEP_OLD.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_PROJECT_FREEZE.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_ROLES.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_SANJAY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_TIMESHEET.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\NGTS_USERS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PKG_09794.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PKG_CV.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PKG_JOB.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PKG_MAIL.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PKG_SENDMAIL.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PKG_SYSTEMGRANTS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PKG_TM.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\PM_RND.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_GTT.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_PROCO.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_REPORTS.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_REPORTS_B.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_REPORTS_C.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_REPORTS_GEN.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_SELECT_LIST_QRY.sql
@E:\Oracle Versioning New\Timecurr\PACKAGE_BODIES\RAP_UNPIVOT_TMDAILY.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\ASSIGN_PM.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHANGE_JOBOPERATOR.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHANGE_PM.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHANGE_SPONSOR.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_BU_TYPE.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_CONTRACT_TYPE.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_COSTMAST_PO.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_EXCL_BILLING.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_EXCL_DELTA_BILLING.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_HIEND_JOBS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_REIMB_JOB.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_TCMNO.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_TCM_JOBS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_TMAGRP.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHG_TYPEOFJOB.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHK_BAYTOWN_POST.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CHK_KALLO_POST.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\CLOSEJOB.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\DELETE_BUDGET.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\DELETE_DATEWISE.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\DT_ADDUSEROBJECT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\EMP_COUNT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\FINAL_TMA_ORDER.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GETCOSTNAME.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GETPROJNAME.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GETTLPNAME.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_ADJ_YYMM.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_AVLBL_CC.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_AVLBL_GRP.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_COUNT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_DESK.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_EHM.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_EHM_CC.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_EMP_HOURS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_EMP_HOURS_BKD.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_EMP_HOURS_RQD.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_FR.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_GRP_DESCR.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_HOURS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_INT_DEPT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_JOB_DIS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_JOB_ETIT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_JOB_GRP.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_JOB_TIT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_LEAVE.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_LEAVE_E.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_LEAVE_N.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_MFS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_MO.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_MOVEMENT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_MS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_OFFFROMDESK.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_OHD_E.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_OHD_N.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_OT.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_OTPERC.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_OT_E.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_OT_N.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_PRJHRS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_PRJHRS_E.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_PRJHRS_N.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_SAP_CC.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_STRENGTH.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_STRENGTH_GRP.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_TMAGRP_DESCR.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_TMATYPE_DESC.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_TMATYPE_DESCR.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_TMA_CLASSI.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_WRKHOURS.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\GET_strength_1.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\INV_RATE.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\JOB_CHG_SPONSOR.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\JOB_REVK_SPON.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\NEW_TMA_ORDER.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\OLD_TMA_ORDER.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\REOPENJOB.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\REVOKE_AFC_APPROVAL.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\REVOKE_JOB_CMD_APPROVAL.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\REVOKE_JOB_SPONSOR_APPROVAL.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\TEST.sql
@E:\Oracle Versioning New\Timecurr\FUNCTIONS\TMA_ORDER.sql
