--------------------------------------------------------
--  Constraints for Table ASSETADMIN1
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."ASSETADMIN1" ADD CONSTRAINT "ASSETADMIN_PK" PRIMARY KEY ("REGNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."ASSETADMIN1" MODIFY ("REGNUM" NOT NULL ENABLE);
