--------------------------------------------------------
--  Constraints for Table DESK_MAST_TO_BE_DELETED
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."DESK_MAST_TO_BE_DELETED" MODIFY ("FLOOR" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."DESK_MAST_TO_BE_DELETED" ADD CONSTRAINT "DESK_MAST_PK" PRIMARY KEY ("DESKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."DESK_MAST_TO_BE_DELETED" MODIFY ("OFFICE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."DESK_MAST_TO_BE_DELETED" MODIFY ("DESKID" NOT NULL ENABLE);
