--------------------------------------------------------
--  Constraints for Table EMP_WEEK_SELECTED
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."EMP_WEEK_SELECTED" ADD CONSTRAINT "EMP_WEEK_MAST_PK" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."EMP_WEEK_SELECTED" MODIFY ("EMPNO" NOT NULL ENABLE);
