--------------------------------------------------------
--  Constraints for Table LL_REVIEWER_DOC
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."LL_REVIEWER_DOC" ADD CONSTRAINT "LL_REVIEWER_DOC_PK" PRIMARY KEY ("LLNUM", "EMPNO", "DOCUMENT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."LL_REVIEWER_DOC" MODIFY ("LLNUM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."LL_REVIEWER_DOC" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."LL_REVIEWER_DOC" MODIFY ("DOCUMENT_NAME" NOT NULL ENABLE);
