--------------------------------------------------------
--  Constraints for Table SS_9794_AUTOPUNCH_DEL_BETWEEN
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_9794_AUTOPUNCH_DEL_BETWEEN" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_AUTOPUNCH_DEL_BETWEEN" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_AUTOPUNCH_DEL_BETWEEN" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_AUTOPUNCH_DEL_BETWEEN" MODIFY ("PDATE" NOT NULL ENABLE);
