--------------------------------------------------------
--  Constraints for Table SS_9794_EMP_ROLES
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_9794_EMP_ROLES" ADD CONSTRAINT "SS_9794_EMP_ROLES_PK" PRIMARY KEY ("EMPNO", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_9794_EMP_ROLES" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_EMP_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
