--------------------------------------------------------
--  Constraints for Table SS_9794_PUNCH_DEL_BETWEEN
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_9794_PUNCH_DEL_BETWEEN" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_PUNCH_DEL_BETWEEN" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_PUNCH_DEL_BETWEEN" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_PUNCH_DEL_BETWEEN" MODIFY ("PDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_PUNCH_DEL_BETWEEN" MODIFY ("MACH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_PUNCH_DEL_BETWEEN" MODIFY ("SS" NOT NULL ENABLE);
