--------------------------------------------------------
--  Constraints for Table SS_9794_ROLE_MASTER
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_9794_ROLE_MASTER" ADD CONSTRAINT "SS_9794_ROLE_MASTER_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_9794_ROLE_MASTER" ADD CONSTRAINT "SS_9794_ROLE_MASTER_UK1" UNIQUE ("ROLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_9794_ROLE_MASTER" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_9794_ROLE_MASTER" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
