--------------------------------------------------------
--  Constraints for Table SS_ABSENT_TS_LEAVE
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_ABSENT_TS_LEAVE" ADD CONSTRAINT "SS_ABSENT_TS_LEAVE_PK" PRIMARY KEY ("EMPNO", "TDATE", "PROJNO", "ACTIVITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_ABSENT_TS_LEAVE" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_ABSENT_TS_LEAVE" MODIFY ("TDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_ABSENT_TS_LEAVE" MODIFY ("PROJNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_ABSENT_TS_LEAVE" MODIFY ("YYYYMM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_ABSENT_TS_LEAVE" MODIFY ("DAY_NO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_ABSENT_TS_LEAVE" MODIFY ("ACTIVITY" NOT NULL ENABLE);
