--------------------------------------------------------
--  Constraints for Table SS_BL_LO_MAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_BL_LO_MAST" ADD CONSTRAINT "PK_CODE" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_BL_LO_MAST" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_BL_LO_MAST" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
