--------------------------------------------------------
--  Constraints for Table SS_BATCH_TYPE_MAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_BATCH_TYPE_MAST" ADD CONSTRAINT "SS_BATCH_TYPE_MAST_PK" PRIMARY KEY ("BATCH_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_BATCH_TYPE_MAST" MODIFY ("BATCH_TYPE_CODE" NOT NULL ENABLE);
