--------------------------------------------------------
--  Constraints for Table SS_BUSLATE_LAYOFF_MAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_MAST" MODIFY ("TIMEIN_HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_MAST" MODIFY ("TIMEIN_MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_MAST" MODIFY ("TIMEOUT_HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_MAST" MODIFY ("TIMEOUT_MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_MAST" ADD PRIMARY KEY ("CODE", "PDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
