--------------------------------------------------------
--  Constraints for Table SS_BUSLATE_LAYOFF_DETAIL
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_DETAIL" ADD CONSTRAINT "PK_EMPNO_CODE_PDATE" PRIMARY KEY ("CODE", "PDATE", "EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_DETAIL" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_DETAIL" MODIFY ("PDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_BUSLATE_LAYOFF_DETAIL" MODIFY ("EMPNO" NOT NULL ENABLE);
