--------------------------------------------------------
--  Constraints for Table SS_CLINIC_DETAIL_20101129
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20101129" ADD CONSTRAINT "SS_CLINIC_DETAIL_PK" PRIMARY KEY ("CLINIC", "LOCATION", "CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20101129" MODIFY ("CLINIC" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20101129" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20101129" MODIFY ("CITY" NOT NULL ENABLE);
