--------------------------------------------------------
--  Constraints for Table SS_CLINIC_DETAIL_20141210
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20141210" MODIFY ("CLINIC" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20141210" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20141210" MODIFY ("CITY" NOT NULL ENABLE);
