--------------------------------------------------------
--  Constraints for Table SS_CLINIC_DETAIL_20161114
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20161114" MODIFY ("CLINIC" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20161114" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_CLINIC_DETAIL_20161114" MODIFY ("CITY" NOT NULL ENABLE);
