--------------------------------------------------------
--  Constraints for Table SS_DEPU_HIST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_DEPU_HIST" ADD CONSTRAINT "PK_EMPNO_BDATE_DEPU_HIST" PRIMARY KEY ("EMPNO", "BDATE", "CHG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_DEPU_HIST" MODIFY ("CHG_NO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_DEPU_HIST" ADD CONSTRAINT "U_APPNO_DEPU_HIST" UNIQUE ("APP_NO", "CHG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
