--------------------------------------------------------
--  Constraints for Table SS_DESKASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_DESKASSIGNMENT" ADD CONSTRAINT "SS_DESKASSIGNMENT_PK" PRIMARY KEY ("EMPNO", "TRANS_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_DESKASSIGNMENT" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_DESKASSIGNMENT" MODIFY ("TRANS_DATE" NOT NULL ENABLE);
