--------------------------------------------------------
--  Constraints for Table SS_DMS_STATUS2020
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_DMS_STATUS2020" ADD CONSTRAINT "SS_DMS_STATUS2020_PK" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_DMS_STATUS2020" MODIFY ("EMPNO" NOT NULL ENABLE);
