--------------------------------------------------------
--  Constraints for Table SS_EMPLPHOTOS
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_EMPLPHOTOS" ADD CONSTRAINT "NOTNULL_FILENAME" CHECK (FILENAME IS NOT NULL
) ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_EMPLPHOTOS" ADD CONSTRAINT "PK_EMPNO" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_EMPLPHOTOS" MODIFY ("SENT_TO_HR" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_EMPLPHOTOS" ADD CONSTRAINT "UNQ_FILENAME" UNIQUE ("FILENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
