--------------------------------------------------------
--  Constraints for Table SS_HOLIDAY_ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_HOLIDAY_ATTENDANCE" ADD CONSTRAINT "SS_HOLIDAY_ATTENDANCE_PK" PRIMARY KEY ("EMPNO", "PDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_HOLIDAY_ATTENDANCE" ADD CONSTRAINT "SS_HOLIDAY_ATTENDANCE_UK1" UNIQUE ("APP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_HOLIDAY_ATTENDANCE" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_HOLIDAY_ATTENDANCE" MODIFY ("PDATE" NOT NULL ENABLE);
