--------------------------------------------------------
--  Constraints for Table SS_LUNCHMAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_LUNCHMAST" ADD CONSTRAINT "PK_LUNCHMAST_SHIFT_PAR" PRIMARY KEY ("SHIFTCODE", "PARENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
