--------------------------------------------------------
--  Constraints for Table SS_LEAVE_UPLOAD_TEMP
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP" ADD CONSTRAINT "PK_LEAVE_UP_TEMP" PRIMARY KEY ("EMPNO", "LEAVETYPE", "DR_CR", "KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP" MODIFY ("LEAVETYPE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP" MODIFY ("LEAVEPERIOD" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP" MODIFY ("DR_CR" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP" MODIFY ("KEY" NOT NULL ENABLE);
