--------------------------------------------------------
--  Constraints for Table SS_LEAVE_ADJ
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("ADJ_DT" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("ADJ_NO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("LEAVETYPE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("DATAENTRYBY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("DB_CR" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("ADJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" MODIFY ("LEAVEPERIOD" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_ADJ" ADD CONSTRAINT "U_ADJNO_LEAVEADJ" UNIQUE ("ADJ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
