--------------------------------------------------------
--  Constraints for Table SS_LEAVE_UPLOAD_LOG
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" ADD CONSTRAINT "CHK_UPPER_UPLAOD_LOG" CHECK (db_cr = upper(db_cr) and adj_type = upper(adj_type)
) ENABLE NOVALIDATE;
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" ADD CONSTRAINT "PK_SS_UP_FILE" PRIMARY KEY ("FILENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" MODIFY ("FILE_UP_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" MODIFY ("LEDG_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" MODIFY ("ADJ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" MODIFY ("DB_CR" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" ADD CONSTRAINT "U_LEAVE_UP_KEY" UNIQUE ("KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
