--------------------------------------------------------
--  Constraints for Table SS_MONTHLY_CREDIT_MAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_MONTHLY_CREDIT_MAST" ADD CONSTRAINT "SS_MONTHLY_CREDIT_MAST_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_MONTHLY_CREDIT_MAST" ADD CONSTRAINT "SS_MONTHLY_CREDIT_MAST_UK1" UNIQUE ("FROM_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_MONTHLY_CREDIT_MAST" MODIFY ("KEY_ID" NOT NULL ENABLE);
