--------------------------------------------------------
--  Constraints for Table SS_OT_DOWNLOAD_DBF_LOCK
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_OT_DOWNLOAD_DBF_LOCK" ADD CONSTRAINT "SS_OT_DOWNLOAD_DBF_LOCK_PK" PRIMARY KEY ("LOCK_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_OT_DOWNLOAD_DBF_LOCK" MODIFY ("LOCK_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_OT_DOWNLOAD_DBF_LOCK" MODIFY ("EMPNO" NOT NULL ENABLE);
