--------------------------------------------------------
--  Constraints for Table SS_ONDUTY
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_ONDUTY" ADD CONSTRAINT "PK_EMPHHMMDATETYPEHHSMMS" UNIQUE ("EMPNO", "HH", "MM", "PDATE", "TYPE", "HHSORT", "MMSORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_ONDUTY" MODIFY ("HHSORT" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_ONDUTY" MODIFY ("MMSORT" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_ONDUTY" ADD CONSTRAINT "U_EMPNO_HH_MM_PDATE_APPNO" UNIQUE ("APP_NO", "EMPNO", "HH", "MM", "PDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
