--------------------------------------------------------
--  Constraints for Table SS_OTMASTER
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_OTMASTER" ADD CONSTRAINT "PK_EMPNO_MON_YYYY" PRIMARY KEY ("EMPNO", "MON", "YYYY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_OTMASTER" ADD CONSTRAINT "SS_OTMASTER_UK21028183671263" UNIQUE ("APP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_OTMASTER" MODIFY ("APP_NO" NOT NULL ENABLE);
