--------------------------------------------------------
--  Constraints for Table SS_PUNCH_BACKUP_20061031
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20061031" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20061031" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20061031" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20061031" MODIFY ("PDATE" NOT NULL ENABLE);
