--------------------------------------------------------
--  Constraints for Table SS_PUNCH_MANUAL
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCH_MANUAL" ADD CONSTRAINT "SS_PUNCH_MANUAL_PK" PRIMARY KEY ("EMPNO", "HH", "MM", "PDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_MANUAL" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_MANUAL" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_MANUAL" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_MANUAL" MODIFY ("PDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_MANUAL" MODIFY ("MACH" NOT NULL ENABLE);
