--------------------------------------------------------
--  Constraints for Table SS_PUNCHBACKUP_20070711
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCHBACKUP_20070711" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCHBACKUP_20070711" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCHBACKUP_20070711" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCHBACKUP_20070711" MODIFY ("PDATE" NOT NULL ENABLE);
