--------------------------------------------------------
--  Constraints for Table SS_PUNCH_20100329
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20100329" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20100329" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20100329" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20100329" MODIFY ("PDATE" NOT NULL ENABLE);
