--------------------------------------------------------
--  Constraints for Table SS_PL_REVISION_MAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PL_REVISION_MAST" ADD CONSTRAINT "SS_PL_REVISION_MAST_PK" PRIMARY KEY ("OLD_APP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_PL_REVISION_MAST" ADD CONSTRAINT "SS_PL_REVISION_MAST_UK1" UNIQUE ("NEW_APP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_PL_REVISION_MAST" MODIFY ("OLD_APP_NO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PL_REVISION_MAST" MODIFY ("NEW_APP_NO" NOT NULL ENABLE);
