--------------------------------------------------------
--  Constraints for Table SS_PUNCH_BACKUP_20100226
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20100226" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20100226" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20100226" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BACKUP_20100226" MODIFY ("PDATE" NOT NULL ENABLE);
