--------------------------------------------------------
--  Constraints for Table SS_PUNCH_BAL
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" ADD CONSTRAINT "PK_EMPNO_PDATE" PRIMARY KEY ("EMPNO", "PDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("PDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("MON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("YYYY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("DELTAHRS" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("SLV_APP_NOS" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("PEN_LV_HRS" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("WRK_HRS" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" MODIFY ("LV_HRS" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_BAL" ADD CONSTRAINT "U_EMPNO_MON_YYYY" UNIQUE ("EMPNO", "MON", "YYYY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
