--------------------------------------------------------
--  Constraints for Table SS_PUNCH_20110426
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20110426" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20110426" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20110426" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20110426" MODIFY ("PDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20110426" MODIFY ("MACH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_20110426" MODIFY ("SS" NOT NULL ENABLE);
