--------------------------------------------------------
--  Constraints for Table SS_PUNCH_UP_TO_20071231
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_PUNCH_UP_TO_20071231" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_UP_TO_20071231" MODIFY ("HH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_UP_TO_20071231" MODIFY ("MM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_PUNCH_UP_TO_20071231" MODIFY ("PDATE" NOT NULL ENABLE);
