--------------------------------------------------------
--  Constraints for Table SS_SITE_ALLOWANCE_PERIOD_ADJ
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_PERIOD_ADJ" ADD CONSTRAINT "SS_SITE_ALLOWANCE_PERIOD__PK" PRIMARY KEY ("EMPNO", "ADJ_FROM", "ADJ_MONTH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_PERIOD_ADJ" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_PERIOD_ADJ" MODIFY ("ADJUSTMENT_MONTH" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_PERIOD_ADJ" MODIFY ("ADJ_FROM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_PERIOD_ADJ" MODIFY ("ADJ_MONTH" NOT NULL ENABLE);
