--------------------------------------------------------
--  Constraints for Table SS_SITE_ALLOWANCE_TRANS
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_TRANS" ADD CONSTRAINT "SS_SITE_ALLOWANCE_TRANS_PK" PRIMARY KEY ("EMPNO", "START_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_TRANS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_TRANS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_TRANS" MODIFY ("PROCESSED_MONTH" NOT NULL ENABLE);
