--------------------------------------------------------
--  Constraints for Table SS_SECRETARY_REP
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_SECRETARY_REP" ADD CONSTRAINT "PK_SEC_EMPNO_HOD_REP" PRIMARY KEY ("EMPNO", "HOD", "REP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
