--------------------------------------------------------
--  Constraints for Table SS_SHIFTMAST_20090401
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_SHIFTMAST_20090401" ADD CONSTRAINT "CHK_SHIFTCODE" CHECK (SHIFTCODE = UPPER(SHIFTCODE)
) ENABLE NOVALIDATE;
  ALTER TABLE "SELFSERVICE"."SS_SHIFTMAST_20090401" ADD PRIMARY KEY ("SHIFTCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
