--------------------------------------------------------
--  Constraints for Table SS_SUGGESTION
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_SUGGESTION" ADD CONSTRAINT "SS_SUGGESTION_PK" PRIMARY KEY ("EMPNO", "TDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_SUGGESTION" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_SUGGESTION" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_SUGGESTION" MODIFY ("TDATE" NOT NULL ENABLE);
