--------------------------------------------------------
--  Constraints for Table SS_SITE_MUSTER
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_SITE_MUSTER" ADD CONSTRAINT "PK_SITEMUSTER" PRIMARY KEY ("EMPNO", "SITECODE", "MNTH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_SITE_MUSTER" MODIFY ("KEY" NOT NULL ENABLE);
