--------------------------------------------------------
--  Constraints for Table SS_TRAVELREQ_200100218
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("TRREQNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("TRDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("MISSTO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("MISSFRDT" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("MISSTODT" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("MISSREASON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("TRDURATION" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("TRTYPE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("VISA" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("MEALS" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ_200100218" MODIFY ("INSTR" NOT NULL ENABLE);
