--------------------------------------------------------
--  Constraints for Table SS_TRAVELREQ
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("TRREQNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("TRDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("MISSTO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("MISSFRDT" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("MISSTODT" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("MISSREASON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("INSTR" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("NTRAVEL" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("TRTYPE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("TRDURATION" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("VISA" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SS_TRAVELREQ" MODIFY ("MEALS" NOT NULL ENABLE);
