--------------------------------------------------------
--  Constraints for Table SS_USERMAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SS_USERMAST" ADD CONSTRAINT "PK_EMPNO_TYPE_USERMAST" PRIMARY KEY ("EMPNO", "TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SS_USERMAST" MODIFY ("ACTIVE" NOT NULL ENABLE);
