--------------------------------------------------------
--  Constraints for Table SWP_SMART_ATTENDANCE_PLAN
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" ADD CONSTRAINT "SWP_WFH_WEEKATND_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" MODIFY ("ATTENDANCE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" MODIFY ("WS_KEY_ID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" MODIFY ("KEY_ID" NOT NULL ENABLE);
