--------------------------------------------------------
--  Constraints for Table SWP_EMP_PRIMARY_WORKSPACE_HIST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("SOURCE_MODIFIEDBY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("SOURCE_MODIFIEDON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("WORKSPACE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EMP_PRIMARY_WORKSPACE_HIST" MODIFY ("KEY" NOT NULL ENABLE);
