--------------------------------------------------------
--  Constraints for Table SWP_IT_PREREQUISITES
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" ADD CONSTRAINT "SWP_IT_PREREQUISITES_PK" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("DOWNLOAD_SPEED" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("UPLOAD_SPEED" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("MONTHLY_QUOTA" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("ISP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("ROUTER_BRAND" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("ROUTER_MODEL" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" MODIFY ("MS_AUTH_ON_OWN_MOB" NOT NULL ENABLE);
