--------------------------------------------------------
--  Constraints for Table SWP_VACCINATION_OFFICE_210612
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_210612" MODIFY ("ATTENDING_VACCINATION" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_210612" MODIFY ("OFFICE_BUS" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_210612" MODIFY ("COWIN_REGTRD" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_210612" MODIFY ("EMPNO" NOT NULL ENABLE);
