--------------------------------------------------------
--  Constraints for Table SWP_MAP_EMP_TASKFORCE
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_MAP_EMP_TASKFORCE" ADD CONSTRAINT "SWP_EMP_TASKFORCE_MAP_PK" PRIMARY KEY ("EMPNO", "PROJNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_MAP_EMP_TASKFORCE" MODIFY ("PROJNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_MAP_EMP_TASKFORCE" MODIFY ("EMPNO" NOT NULL ENABLE);
