--------------------------------------------------------
--  Constraints for Table SWP_RELATION_MAST
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_RELATION_MAST" ADD CONSTRAINT "SWP_RELATION_MAST_CHK1" CHECK (relation_code = upper(relation_code)) ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_RELATION_MAST" ADD CONSTRAINT "SWP_RELATION_MAST_PK" PRIMARY KEY ("RELATION_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_RELATION_MAST" MODIFY ("RELATION_CODE" NOT NULL ENABLE);
