--------------------------------------------------------
--  Constraints for Table SWP_PRIMARY_WORKSPACE
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_PRIMARY_WORKSPACE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_PRIMARY_WORKSPACE" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_PRIMARY_WORKSPACE" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_PRIMARY_WORKSPACE" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_PRIMARY_WORKSPACE" MODIFY ("KEY_ID" NOT NULL ENABLE);
