--------------------------------------------------------
--  Constraints for Table SWP_VACCINATION_OFFICE_BATCH_2
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" ADD CONSTRAINT "SWP_VACCINATION_OFFICE_BAT_PK" PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" MODIFY ("JAB_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" MODIFY ("PREFERRED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" MODIFY ("VACCINATION_FOR" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" MODIFY ("EMPNO" NOT NULL ENABLE);
