--------------------------------------------------------
--  Constraints for Table SWP_BUS_ROUTES
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_BUS_ROUTES" ADD CONSTRAINT "SWP_BUS_ROUTES_PK" PRIMARY KEY ("ROUTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_BUS_ROUTES" MODIFY ("ROUTE_ID" NOT NULL ENABLE);
