--------------------------------------------------------
--  Constraints for Table XDM_NEWJOIN_TRANS
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_NEWJOIN_TRANS" ADD CONSTRAINT "DM_NEWJOIN_TRANS_PK" PRIMARY KEY ("NEWJOINREQNUM", "NEWJOINREQDATE", "EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_NEWJOIN_TRANS" MODIFY ("NEWJOINREQNUM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_NEWJOIN_TRANS" MODIFY ("NEWJOINREQDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_NEWJOIN_TRANS" MODIFY ("EMPNO" NOT NULL ENABLE);
