--------------------------------------------------------
--  Constraints for Table XDM_PENDING_PC_LOCK_20150925
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_PENDING_PC_LOCK_20150925" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_PENDING_PC_LOCK_20150925" MODIFY ("TDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_PENDING_PC_LOCK_20150925" MODIFY ("PCNAME" NOT NULL ENABLE);
