--------------------------------------------------------
--  Constraints for Table XDM_DESKLOCK_ERR
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_ERR" MODIFY ("UNQID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_ERR" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_ERR" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_ERR" MODIFY ("TARGETDESK" NOT NULL ENABLE);
