--------------------------------------------------------
--  Constraints for Table XDM_ASSETADD_ERR
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_ERR" ADD CONSTRAINT "DM_ASSETADD_PK" PRIMARY KEY ("UNQID", "DESKID", "ASSETID", "EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_ERR" MODIFY ("UNQID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_ERR" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_ERR" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_ERR" MODIFY ("EMPNO" NOT NULL ENABLE);
