--------------------------------------------------------
--  Constraints for Table XDM_ASSETMOVE_TRAN_HIST_051216
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HIST_051216" MODIFY ("MOVEREQNUM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HIST_051216" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HIST_051216" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HIST_051216" MODIFY ("DESK_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HIST_051216" MODIFY ("ASSETID" NOT NULL ENABLE);
