--------------------------------------------------------
--  Constraints for Table XDM_TASKFORCETRAN
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_TASKFORCETRAN" ADD CONSTRAINT "DM_TASKFORCETRAN_PK" PRIMARY KEY ("EMPNO", "TID", "SINCEDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_TASKFORCETRAN" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_TASKFORCETRAN" MODIFY ("TID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_TASKFORCETRAN" MODIFY ("SINCEDATE" NOT NULL ENABLE);
