--------------------------------------------------------
--  Constraints for Table XDM_ASSETADD_BACKUP
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_BACKUP" MODIFY ("UNQID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_BACKUP" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_BACKUP" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_BACKUP" MODIFY ("EMPNO" NOT NULL ENABLE);
