--------------------------------------------------------
--  Constraints for Table XDM_PENDING_PC_LOCK
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_PENDING_PC_LOCK" ADD CONSTRAINT "DM_PENDING_PC_LOCK_PK" PRIMARY KEY ("EMPNO", "TDATE", "PCNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_PENDING_PC_LOCK" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_PENDING_PC_LOCK" MODIFY ("TDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_PENDING_PC_LOCK" MODIFY ("PCNAME" NOT NULL ENABLE);
