--------------------------------------------------------
--  Constraints for Table XDM_ASSET_OFFICE
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_ASSET_OFFICE" ADD CONSTRAINT "DM_ASSET_OFFICE_PK" PRIMARY KEY ("ASSETID", "OFFICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_ASSET_OFFICE" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSET_OFFICE" MODIFY ("OFFICE" NOT NULL ENABLE);
