--------------------------------------------------------
--  Constraints for Table XDM_ASSETADD_16APR10
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_16APR10" MODIFY ("UNQID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_16APR10" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_16APR10" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETADD_16APR10" MODIFY ("EMPNO" NOT NULL ENABLE);
