--------------------------------------------------------
--  Constraints for Table XDM_ASSETMOVE_TRAN_HISTORY
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HISTORY" MODIFY ("MOVEREQNUM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HISTORY" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HISTORY" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HISTORY" MODIFY ("DESK_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_HISTORY" MODIFY ("ASSETID" NOT NULL ENABLE);
