--------------------------------------------------------
--  Constraints for Table XDM_LOGINRIGHT
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_LOGINRIGHT" ADD CONSTRAINT "DM_LOGINRIGHT_PK" PRIMARY KEY ("TRANS_ID", "EMPNO", "TO_DESK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_LOGINRIGHT" MODIFY ("TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_LOGINRIGHT" MODIFY ("TO_DESK" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_LOGINRIGHT" MODIFY ("EMPNO" NOT NULL ENABLE);
