--------------------------------------------------------
--  Constraints for Table XDM_SOURCEDESK
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_SOURCEDESK" ADD CONSTRAINT "DM_SOURCEDESK_PK" PRIMARY KEY ("SID", "DESKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_SOURCEDESK" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_SOURCEDESK" MODIFY ("DESKID" NOT NULL ENABLE);
