--------------------------------------------------------
--  Constraints for Table XDM_DESKMASTER_VISIO_ID
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_DESKMASTER_VISIO_ID" ADD CONSTRAINT "DM_DESKMASTER_VISIO_ID_PK" PRIMARY KEY ("DESKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_DESKMASTER_VISIO_ID" MODIFY ("DESKID" NOT NULL ENABLE);
