--------------------------------------------------------
--  Constraints for Table XDM_DESKLOCK
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK" MODIFY ("UNQID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK" MODIFY ("TARGETDESK" NOT NULL ENABLE);
