--------------------------------------------------------
--  Constraints for Table XDM_DESKLOCK_BACKUP
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_BACKUP" MODIFY ("UNQID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_BACKUP" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_BACKUP" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_DESKLOCK_BACKUP" MODIFY ("TARGETDESK" NOT NULL ENABLE);
