--------------------------------------------------------
--  Constraints for Table XDM_NEWJOIN_TRANS_20150401
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_NEWJOIN_TRANS_20150401" MODIFY ("NEWJOINREQNUM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_NEWJOIN_TRANS_20150401" MODIFY ("NEWJOINREQDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_NEWJOIN_TRANS_20150401" MODIFY ("EMPNO" NOT NULL ENABLE);
