--------------------------------------------------------
--  Constraints for Table XDM_EMPADD
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_EMPADD" ADD CONSTRAINT "DM_EMPADD_PK" PRIMARY KEY ("UNQID", "EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."XDM_EMPADD" MODIFY ("UNQID" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_EMPADD" MODIFY ("EMPNO" NOT NULL ENABLE);
