--------------------------------------------------------
--  Constraints for Table XDM_ASSETMOVE_TRAN_16APR10
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_16APR10" MODIFY ("MOVEREQNUM" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_16APR10" MODIFY ("MOVEREQDATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_16APR10" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_16APR10" MODIFY ("CURRDESK" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_16APR10" MODIFY ("TARGETDESK" NOT NULL ENABLE);
