
  CREATE TABLE "TCMPL_APP_CONFIG"."APP_SITE_MAP_LINKS" 
   (	"LINK_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"LINK_CONTROLLER_NAME" VARCHAR2(50 BYTE), 
	"LINK_ACTION_NAME" VARCHAR2(50 BYTE), 
	"LINK_AREA_NAME" VARCHAR2(50 BYTE), 
	"FILTER_MVC_ACTION_NAME" VARCHAR2(100 BYTE), 
	"PROCESS_ID" VARCHAR2(30 BYTE), 
	"PROCESS_PROC_CONTROLLER_NAME" VARCHAR2(50 BYTE), 
	"PROCESS_PROC_ACTION_NAME" VARCHAR2(50 BYTE), 
	"PROCESS_PROC_AREA_NAME" VARCHAR2(50 BYTE), 
	"PROCESS_DWLD_CONTROLLER_NAME" VARCHAR2(50 BYTE), 
	"PROCESS_DWLD_ACTION_NAME" VARCHAR2(50 BYTE), 
	"PROCESS_DWLD_AREA_NAME" VARCHAR2(50 BYTE), 
	"SITE_MAP_MASTER_ID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_LINKS_PK" PRIMARY KEY ("LINK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_LINKS_FK1" FOREIGN KEY ("SITE_MAP_MASTER_ID")
	  REFERENCES "TCMPL_APP_CONFIG"."APP_SITE_MAP_MASTER" ("SITE_MAP_MASTER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

