
  CREATE TABLE "TCMPL_APP_CONFIG"."APP_SITE_MAP_MASTER" 
   (	"SITE_MAP_MASTER_ID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"MODULE_ID" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"MENU_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"IS_LEAF" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"ORDER_BY" NUMBER(4,0) NOT NULL ENABLE, 
	"IS_REPORT" VARCHAR2(2 BYTE) DEFAULT 'KO' NOT NULL ENABLE, 
	"TO_PROCESS" VARCHAR2(2 BYTE) DEFAULT 'KO' NOT NULL ENABLE, 
	"LINK_ID" VARCHAR2(5 BYTE), 
	"PARENT_MENU_ID" VARCHAR2(6 BYTE), 
	 CONSTRAINT "APP_SITE_MAP_MASTER_PK" PRIMARY KEY ("SITE_MAP_MASTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_MASTER_UK1" UNIQUE ("MODULE_ID", "MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_MASTER_UK2" UNIQUE ("MODULE_ID", "MENU_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "TCMPL_APP_CONFIG"."APP_SITE_MAP_MASTER"."IS_REPORT" IS 'OK or KO';
   COMMENT ON COLUMN "TCMPL_APP_CONFIG"."APP_SITE_MAP_MASTER"."TO_PROCESS" IS 'OK or KO';

