
  CREATE TABLE "TCMPL_APP_CONFIG"."APP_SITE_MAP_REPORT" 
   (	"REPORT_FORMAT" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"REPORT_ICON" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SITE_MAP_MASTER_ID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_REPORT_PK" PRIMARY KEY ("REPORT_FORMAT", "SITE_MAP_MASTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_REPORT_FK1" FOREIGN KEY ("SITE_MAP_MASTER_ID")
	  REFERENCES "TCMPL_APP_CONFIG"."APP_SITE_MAP_MASTER" ("SITE_MAP_MASTER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

