--------------------------------------------------------
--  DDL for Table APP_PROCESS_FINISHED
--------------------------------------------------------
CREATE TABLE "TCMPL_APP_CONFIG"."APP_PROCESS_FINISHED" 
   (	"KEY_ID" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"EMPNO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"MODULE_ID" CHAR(3 BYTE) NOT NULL ENABLE, 
	"PROCESS_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROCESS_DESC" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PARAMETER_JSON" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PROCESS_START_DATE" DATE, 
	"PROCESS_FINISH_DATE" DATE, 
	"CREATED_ON" DATE NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) NOT NULL ENABLE, 
	"MAIL_TO" VARCHAR2(4000 BYTE), 
	"MAIL_CC" VARCHAR2(4000 BYTE),
    "PROCESS_ITEM_ID" VARCHAR2(100 BYTE)
   ) 