
  CREATE TABLE "TCMPL_APP_CONFIG"."APP_SITE_MAP_LINKS_PARAMETERS" 
   (	"LINK_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"LINK_ROUTE_PARAMETERS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"IS_REQUIRED" VARCHAR2(2 BYTE), 
	"LINK_MAPPING_ROUTE_PARAMETERS" VARCHAR2(50 BYTE), 
	"LINK_TYPE" VARCHAR2(10 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(50 BYTE), 
	"ORDER_BY" NUMBER(2,0), 
	"FORMULA_ID" VARCHAR2(5 BYTE), 
	 CONSTRAINT "APP_SITE_MAP_LINKS_PARAMETERS_UK1" UNIQUE ("LINK_ID", "LINK_ROUTE_PARAMETERS", "LINK_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_LINKS_PARAMETERS_FK1" FOREIGN KEY ("LINK_ID")
	  REFERENCES "TCMPL_APP_CONFIG"."APP_SITE_MAP_LINKS" ("LINK_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

