
  CREATE TABLE "TCMPL_APP_CONFIG"."APP_SITE_MAP_LINKS_PARAMETERS_FORMULAE" 
   (	"FORMULA_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"LINK_TYPE" VARCHAR2(10 BYTE) DEFAULT 'PROCESS' NOT NULL ENABLE, 
	"FORMULA_PARAMETERS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ORDER_BY" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "APP_SITE_MAP_LINKS_PARAMETERS_FORMULAE_PK" PRIMARY KEY ("FORMULA_ID", "LINK_TYPE", "FORMULA_PARAMETERS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

