
  CREATE GLOBAL TEMPORARY TABLE "TCMPL_APP_CONFIG"."SEC_MODULE_GTT_IMPORT_EXCEL_ERRORS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SECTION" VARCHAR2(1 BYTE), 
	"EXCEL_ROW_NUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"ERROR_TYPE" NUMBER(1,0) NOT NULL ENABLE, 
	"ERROR_TYPE_STRING" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(1000 BYTE) NOT NULL ENABLE
   ) ON COMMIT PRESERVE ROWS ;

