--------------------------------------------------------
--  Ref Constraints for Table SEC_MODULE_ROLES
--------------------------------------------------------

  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULE_ROLES" ADD CONSTRAINT "SEC_MODULE_ROLES_FK1" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "TCMPL_APP_CONFIG"."SEC_MODULES" ("MODULE_ID") ENABLE;
  ALTER TABLE "TCMPL_APP_CONFIG"."SEC_MODULE_ROLES" ADD CONSTRAINT "SEC_MODULE_ROLES_FK2" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "TCMPL_APP_CONFIG"."SEC_ROLES" ("ROLE_ID") ENABLE;
