--------------------------------------------------------
--  DDL for Table SWP_EXCLUDE_EMP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" 
   (	"KEY_ID" VARCHAR2(10 BYTE), 
	"EMPNO" CHAR(5 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REASON" VARCHAR2(400 BYTE), 
	"MODIFIED_ON" DATE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE), 
	"IS_ACTIVE" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Index SWP_EXCLUDE_EMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."SWP_EXCLUDE_EMP_PK" ON "SELFSERVICE"."SWP_EXCLUDE_EMP" ("KEY_ID") 
;
--------------------------------------------------------
--  DDL for Index SWP_EXCLUDE_EMP_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."SWP_EXCLUDE_EMP_UK" ON "SELFSERVICE"."SWP_EXCLUDE_EMP" ("EMPNO", "START_DATE") 
;
--------------------------------------------------------
--  Constraints for Table SWP_EXCLUDE_EMP
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" ADD CONSTRAINT "SWP_EXCLUDE_EMP_UK" UNIQUE ("EMPNO", "START_DATE");
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" ADD CONSTRAINT "SWP_EXCLUDE_EMP_PK" PRIMARY KEY ("KEY_ID");
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("KEY_ID" NOT NULL ENABLE);
