REM INSERTING into TCMPL_APP_CONFIG.SEC_ROLES
SET DEFINE OFF;
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R001','TCMPL_EMP','TCMPL Employee - Status=1','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R002','HOD','Head of Department','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R003','SEC','Dept Secretary','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R010','PAYROLL_ADM','Payroll Admin','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R011','ATTENDANCE_ADM','Attendance Admin','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R004','MANAGER_HOD','Manager HoD - Based on MNGR field','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R012','COSTCONTROL_ADM','Cost controller Admin','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R013','AFC_ADM','Finance Admin','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R014','HRMASTERS_VIEW','HR Masters View','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R005','MANAGER_HOD_ONBEHALF','Approver on behalf Manager HoD','OK');
Insert into TCMPL_APP_CONFIG.SEC_ROLES (ROLE_ID,ROLE_NAME,ROLE_DESC,ROLE_IS_ACTIVE) values ('R006','LEAD','Lead','OK');
