REM INSERTING into TCMPL_APP_CONFIG.SEC_MODULE_ROLES
SET DEFINE OFF;
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M01','R001','M01R001');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M01','R002','M01R002');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M02','R001','M02R001');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M02','R002','M02R002');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M03','R002','M03R002');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M03','R010','M03R010');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M03','R011','M03R011');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M03','R012','M03R012');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M03','R013','M03R013');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M03','R014','M03R014');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M04','R003','M04R003');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M04','R004','M04R004');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M04','R005','M04R005');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M04','R006','M04R006');
Insert into TCMPL_APP_CONFIG.SEC_MODULE_ROLES (MODULE_ID,ROLE_ID,MODULE_ROLE_KEY_ID) values ('M04','R011','M04R011');
