REM INSERTING into TCMPL_APP_CONFIG.SEC_ACTIONS
SET DEFINE OFF;
Insert into TCMPL_APP_CONFIG.SEC_ACTIONS (MODULE_ID,ACTION_ID,ACTION_NAME,ACTION_DESC,ACTION_IS_ACTIVE,MODULE_ACTION_KEY_ID) values ('M03','A001','EDIT_EMPLMAST','Edit Employeemaster','OK','M03A001');
Insert into TCMPL_APP_CONFIG.SEC_ACTIONS (MODULE_ID,ACTION_ID,ACTION_NAME,ACTION_DESC,ACTION_IS_ACTIVE,MODULE_ACTION_KEY_ID) values ('M03','A002','VIEW_HRMASTERS','View HR Masters','OK','M03A002');
