--------------------------------------------------------
--  DDL for Table DM_ASSETCODE_OLD
--------------------------------------------------------

  CREATE TABLE "DM_ASSETCODE_OLD" 
   (	"BARCODE" CHAR(13), 
	"PONUM" CHAR(15), 
	"GRNUM" CHAR(15), 
	"INVOICENUM" VARCHAR2(20), 
	"ASSETTYPE" CHAR(2), 
	"STPI" NUMBER(1,0) DEFAULT 0, 
	"BARCODE1" NUMBER(5,0), 
	"ASSETCODE" CHAR(7), 
	"PRNTFLAG" NUMBER(1,0) DEFAULT 0, 
	"SERIALNUM" VARCHAR2(35), 
	"SCRAP" NUMBER(1,0) DEFAULT 0, 
	"SCRAP_DATE" DATE, 
	"MODEL" VARCHAR2(50), 
	"COMPNAME" VARCHAR2(20), 
	"OUT_OF_SERVICE" NUMBER(1,0), 
	"PODATE" DATE, 
	"WARRANTY_END" DATE, 
	"HDD" VARCHAR2(20), 
	"RAM" VARCHAR2(20), 
	"PROCESSOR" VARCHAR2(50), 
	"OPTICAL_DRIVE" VARCHAR2(50), 
	"INVOICE_DATE" DATE, 
	"SAP_ASSETCODE" VARCHAR2(50), 
	"OUTOFSERVICE_TYPE" NUMBER(1,0), 
	"TO_BE_SCRAP" NUMBER(1,0) DEFAULT 0, 
	"BARCODE_OLD" VARCHAR2(13)
   ) ;

   COMMENT ON COLUMN "DM_ASSETCODE_OLD"."TO_BE_SCRAP" IS '"1" means true; "0" means false';
