CREATE TABLE "DMS"."DM_ACTION_ITEM_EXCLUDE" 
   (	"ACTIONTRANSID" CHAR(11 BYTE) NOT NULL ENABLE, 
	"ASSETID" VARCHAR2(13 BYTE), 
	"SOURCEDESK" VARCHAR2(5 BYTE), 
	"TARGETASSET" VARCHAR2(13 BYTE), 
	"ACTION_TYPE" NUMBER, 
	"REMARKS" VARCHAR2(100 BYTE), 
	"ACTION_DATE" DATE, 
	"ACTION_BY" VARCHAR2(5 BYTE), 
	"SOURCE_EMP" VARCHAR2(50 BYTE), 
	"ASSETID_OLD" VARCHAR2(13 BYTE),
	"ITEM_TYPE" VARCHAR2(2 BYTE),
	 CONSTRAINT "DM_ACTION_ITEM_EXCLUDE_PK" PRIMARY KEY ("ACTIONTRANSID"));