
  CREATE GLOBAL TEMPORARY TABLE "DMS"."DM_GTT_TRANSACTION_DETAIL" 
   (	"TRANS_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE
   ) ON COMMIT PRESERVE ROWS ;


  GRANT INSERT ON "DMS"."DM_GTT_TRANSACTION_DETAIL"  TO "TCMPL_APP_CONFIG";
