--------------------------------------------------------
--  DDL for Table DM_PC_DETAILS
--------------------------------------------------------

  CREATE TABLE "DM_PC_DETAILS" 
   (	"LONG_PC_NAME" VARCHAR2(50), 
	"SHORT_PC_NAME" VARCHAR2(50), 
	"OS" VARCHAR2(150), 
	"COMP_MODEL" VARCHAR2(200), 
	"SERVICE_PACK" VARCHAR2(200), 
	"IP_ADDRESS" VARCHAR2(200), 
	"MAC_ADDRESS" VARCHAR2(200), 
	"DOMAIN_UPDATE_DAYS" VARCHAR2(100), 
	"NO_OF_PROCESSORS" VARCHAR2(200), 
	"NO_OF_CORES" VARCHAR2(100), 
	"CPU" VARCHAR2(200), 
	"SYS_MEM" VARCHAR2(100), 
	"VIDEO_CARD" VARCHAR2(500), 
	"VIDEO_CARD_MEM" VARCHAR2(300), 
	"DISK_SIZE" VARCHAR2(100), 
	"MACHINE_TYPE" VARCHAR2(100)
   ) ;
