
  CREATE TABLE "DMS"."INV_TRANSACTION_DETAIL" 
   (	"TRANS_DET_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ITEM_USABLE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"TRANS_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "INV_TRANSACTION_DETAIL_PK" PRIMARY KEY ("TRANS_DET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "INV_TRANSACTION_DETAIL_UK1" UNIQUE ("TRANS_ID", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "INV_TRANSACTION_DETAIL_FK1" FOREIGN KEY ("TRANS_ID")
	  REFERENCES "DMS"."INV_TRANSACTION_MASTER" ("TRANS_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "DMS"."INV_TRANSACTION_DETAIL"."ITEM_USABLE" IS '''Y'' or ''N''';

