
  CREATE TABLE "DMS"."INV_ITEM_TYPES" 
   (	"ITEM_TYPE_KEY_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ITEM_TYPE_CODE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"CATEGORY_CODE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"ITEM_ASSIGNMENT_TYPE" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"ITEM_TYPE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"PRINT_ORDER" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "INV_ITEM_TYPES_PK" PRIMARY KEY ("ITEM_TYPE_KEY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

  CREATE INDEX "DMS"."INV_ITEM_TYPES_INDEX1" ON "DMS"."INV_ITEM_TYPES" ("ITEM_TYPE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

