
  CREATE TABLE "DMS"."INV_TRANSACTION_MASTER" 
   (	"TRANS_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TRANS_DATE" DATE NOT NULL ENABLE, 
	"EMPNO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"TRANS_TYPE_ID" CHAR(3 BYTE) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(200 BYTE), 
	"MODIFIED_BY" CHAR(5 BYTE) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE,     
	"GATE_PASS_REF_NO" NUMBER(10,0), 
    "GATE_PASS" VARCHAR2(50), 
	 CONSTRAINT "INV_TRANSACTION_MASTER_PK" PRIMARY KEY ("TRANS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "INV_TRANSACTION_MASTER_FK1" FOREIGN KEY ("TRANS_TYPE_ID")
	  REFERENCES "DMS"."INV_TRANSACTION_TYPES" ("TRANS_TYPE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA";

