
  CREATE TABLE "DMS"."INV_EMP_ITEM_MAPPING_RESERVE_RETURN" 
   (	"EMPNO" CHAR(5 BYTE) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TRANS_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "INV_EMP_ITEM_MAPPING_RESERVE_RETURN_PK" PRIMARY KEY ("EMPNO", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

