
  CREATE TABLE "DMS"."INV_CONSUMABLES_DETAIL" 
   (	"CONSUMABLE_DET_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ITEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MFG_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONSUMABLE_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"IS_NEW" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"IS_ISSUED" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"IS_USABLE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	 CONSTRAINT "INV_CONSUMABLES_DETAIL_PK" PRIMARY KEY ("CONSUMABLE_DET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "INV_CONSUMABLES_DETAIL_FK1" FOREIGN KEY ("CONSUMABLE_ID")
	  REFERENCES "DMS"."INV_CONSUMABLES_MASTER" ("CONSUMABLE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "DMS"."INV_CONSUMABLES_DETAIL"."IS_NEW" IS '''Y'' OR ''N''';
   COMMENT ON COLUMN "DMS"."INV_CONSUMABLES_DETAIL"."IS_ISSUED" IS '''Y'' OR ''N''';
   COMMENT ON COLUMN "DMS"."INV_CONSUMABLES_DETAIL"."IS_USABLE" IS '''Y'' OR ''N''';

