
  CREATE TABLE "DMS"."INV_CONSUMABLES_MASTER" 
   (	"CONSUMABLE_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CONSUMABLE_DATE" DATE NOT NULL ENABLE, 
	"CONSUMABLE_DESC" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ITEM_TYPE_KEY_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(4,0) NOT NULL ENABLE, 
	"TOTAL_ISSUED" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	"TOTAL_RESERVED" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	"TOTAL_NON_USABLE" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "INV_CONSUMABLES_MASTER_PK" PRIMARY KEY ("CONSUMABLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "INV_CONSUMABLES_MASTER_UK1" UNIQUE ("CONSUMABLE_DESC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "INV_CONSUMABLES_MASTER_FK1" FOREIGN KEY ("ITEM_TYPE_KEY_ID")
	  REFERENCES "DMS"."INV_ITEM_TYPES" ("ITEM_TYPE_KEY_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA";

