
  CREATE TABLE "DMS"."INV_ITEM_AMS_ASSET_MAPPING" 
   (	"KEY_ID" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"ITEM_TYPE_KEY_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"SUB_ASSET_TYPE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "INV_AMS_SUB_ASSET_MAPPING_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "INV_AMS_SUB_ASSET_MAPPING_FK1" FOREIGN KEY ("ITEM_TYPE_KEY_ID")
	  REFERENCES "DMS"."INV_ITEM_TYPES" ("ITEM_TYPE_KEY_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

