--------------------------------------------------------
--  Ref Constraints for Table SS_BATCH_LOG_MAST
--------------------------------------------------------

  ALTER TABLE "SS_BATCH_LOG_MAST" ADD CONSTRAINT "SS_BATCH_LOG_MAST_FK1" FOREIGN KEY ("BATCH_TYPE_CODE")
	  REFERENCES "SS_BATCH_TYPE_MAST" ("BATCH_TYPE_CODE") ENABLE;
  ALTER TABLE "SS_BATCH_LOG_MAST" ADD CONSTRAINT "SS_BATCH_LOG_MAST_FK2" FOREIGN KEY ("BATCH_STATUS_CODE")
	  REFERENCES "SS_BATCH_STATUS_MAST" ("STATUS_CODE") ENABLE;
