--------------------------------------------------------
--  Ref Constraints for Table SS_HALFDAYMAST
--------------------------------------------------------

  ALTER TABLE "SS_HALFDAYMAST" ADD CONSTRAINT "FK_SHIFTCODE_HDMAST" FOREIGN KEY ("SHIFTCODE")
	  REFERENCES "SS_SHIFTMAST_20090401" ("SHIFTCODE") DISABLE;
  ALTER TABLE "SS_HALFDAYMAST" ADD CONSTRAINT "FK_SHIFT_CODE_HDMAST_NU" FOREIGN KEY ("SHIFTCODE")
	  REFERENCES "SS_SHIFTMAST" ("SHIFTCODE") ENABLE;
