--------------------------------------------------------
--  Ref Constraints for Table SS_LEAVE_UPLOAD_TEMP
--------------------------------------------------------

  ALTER TABLE "SS_LEAVE_UPLOAD_TEMP" ADD CONSTRAINT "FK_LEAVE_UP_TEMP" FOREIGN KEY ("KEY")
	  REFERENCES "SS_LEAVE_UPLOAD_LOG" ("KEY") ENABLE NOVALIDATE;
  ALTER TABLE "SS_LEAVE_UPLOAD_TEMP" ADD CONSTRAINT "FK_LEAVE_UP_TEMP_L_TYPE" FOREIGN KEY ("LEAVETYPE")
	  REFERENCES "SS_LEAVETYPE" ("LEAVETYPE") ENABLE NOVALIDATE;
