--------------------------------------------------------
--  DDL for Table EMP_DETAILS
--------------------------------------------------------

  CREATE TABLE "COMMONMASTERS"."EMP_DETAILS" 
   (	"EMPNO" CHAR(5), 
	"DESK_NO" VARCHAR2(50), 
	"MAIL_ID" VARCHAR2(50), 
	"PHONE_OFF" VARCHAR2(50), 
	"FAX" VARCHAR2(50), 
	"VOIP" VARCHAR2(50), 
	"MOBILE_RES" VARCHAR2(50), 
	"PHONE_RES" VARCHAR2(50), 
	"MOBILE_OFF" VARCHAR2(50), 
	"R_ADD_1" VARCHAR2(50), 
	"R_ADD_2" VARCHAR2(50), 
	"R_ADD_3" VARCHAR2(50), 
	"R_ADD_4" VARCHAR2(50), 
	"PAN" VARCHAR2(50), 
	"PASSPORT_NO" VARCHAR2(50), 
	"ISSUE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"PASSPORT_ISSUED_AT" VARCHAR2(50), 
	"BLOOD_GROUP" CHAR(3), 
	"DOMAIN_LOGIN" VARCHAR2(50), 
	"USER_UPDATE" NUMBER(1,0), 
	"SURNAME" VARCHAR2(60), 
	"NAME" VARCHAR2(60), 
	"FATHER_NAME" VARCHAR2(60), 
	"P_ADD_1" VARCHAR2(50), 
	"P_ADD_2" VARCHAR2(50), 
	"P_ADD_3" VARCHAR2(50), 
	"P_ADD_4" VARCHAR2(50), 
	"F_ADD_1" VARCHAR2(50), 
	"F_ADD_2" VARCHAR2(50), 
	"F_ADD_3" VARCHAR2(50), 
	"F_ADD_4" VARCHAR2(50), 
	"REF_PERSON_NAME" VARCHAR2(60), 
	"REF_PERSON_PHONE" VARCHAR2(50), 
	"LOCATION" VARCHAR2(60), 
	"PUNCH_CARD_STATUS" NUMBER(2,0), 
	"DOB" DATE, 
	"FATHER_OCCUPATION" VARCHAR2(50), 
	"INSR_DETAILS" VARCHAR2(200), 
	"CO_BUS" CHAR(5), 
	"PICK_UP_POINT" VARCHAR2(60), 
	"R_PINCODE" NUMBER(6,0), 
	"P_PINCODE" NUMBER(6,0), 
	"F_PINCODE" NUMBER(6,0), 
	"MARITAL_STATUS" VARCHAR2(15), 
	"RELIGION" VARCHAR2(100), 
	"SURNAME_OLD" VARCHAR2(60), 
	"FATHER_NAME_OLD" VARCHAR2(60), 
	"NAME_OLD" VARCHAR2(60), 
	"P_ADD_1_OLD" VARCHAR2(50), 
	"P_ADD_2_OLD" VARCHAR2(50), 
	"P_ADD_3_OLD" VARCHAR2(50), 
	"P_ADD_4_OLD" VARCHAR2(50), 
	"P_PINCODE_OLD" VARCHAR2(6), 
	"INCLUDE_DAD_HUSB_NAME" NUMBER(1,0), 
	"NO_DAD_HUSB_IN_NAME" NUMBER(1,0), 
	"MODIFIED_ON" DATE, 
	"P_PHONE" VARCHAR2(50), 
	"NATIONALITY" VARCHAR2(20), 
	"P_MOBILE" VARCHAR2(50), 
	"PLACE_OF_BIRTH" VARCHAR2(200), 
	"COUNTRY_OF_BIRTH" VARCHAR2(100), 
	"PERSONAL_EMAIL" VARCHAR2(150), 
	"P_CITY" VARCHAR2(100), 
	"P_DISTRICT" VARCHAR2(100), 
	"P_HOUSE_NO" VARCHAR2(100), 
	"P_COUNTRY" VARCHAR2(100), 
	"R_CITY" VARCHAR2(100), 
	"R_DISTRICT" VARCHAR2(100), 
	"R_HOUSE_NO" VARCHAR2(100), 
	"R_COUNTRY" VARCHAR2(100), 
	"F_CITY" VARCHAR2(100), 
	"F_DISTRICT" VARCHAR2(100), 
	"F_HOUSE_NO" VARCHAR2(100), 
	"F_COUNTRY" VARCHAR2(100), 
	"PASSPORT_GIVEN_NAME" VARCHAR2(100), 
	"NO_OF_CHILD" NUMBER(2,0), 
	"PASSPORT_SURNAME" VARCHAR2(60), 
	"PRIMARY_DATA_UPDATE" NUMBER(1,0), 
	"SECONDARY_DATA_UPDATE" NUMBER(1,0)
   ) ;

   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."EMPNO" IS 'Employee Number';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."DESK_NO" IS 'Desk Number Occupied by Emp in Office';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."MAIL_ID" IS 'TICB Mail ID';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."PHONE_OFF" IS 'Office Phone Number of the Emp';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."FAX" IS 'Office Fax Number of the Emp';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."VOIP" IS 'Voice over IP phone number of Office';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."MOBILE_RES" IS 'Personal Mobile Number';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."PHONE_RES" IS 'Residential Phone Number';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."MOBILE_OFF" IS 'Mobile number provided by Office';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."R_ADD_1" IS 'Residential Address';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."R_ADD_2" IS 'Residential Address';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."R_ADD_3" IS 'Residential Address';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."R_ADD_4" IS 'Residential Address';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."PAN" IS 'PAN number for Income Tax purpose';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."PASSPORT_NO" IS 'Passport number';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."ISSUE_DATE" IS 'Passport Issue Date';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."EXPIRY_DATE" IS 'Passport Expiry Date';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."PASSPORT_ISSUED_AT" IS 'Passport issued at (Place)';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."BLOOD_GROUP" IS 'Blood Group of the Employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."DOMAIN_LOGIN" IS 'TICB Domail Login ID';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."USER_UPDATE" IS 'Has the user updated the data';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."SURNAME" IS 'Surname of the employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."NAME" IS 'Name of the Employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."FATHER_NAME" IS 'Fathers Name of the Employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."P_ADD_1" IS 'Permanent Address of the employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."P_ADD_2" IS 'Permanent Address of the employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."P_ADD_3" IS 'Permanent Address of the employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."P_ADD_4" IS 'Permanent Address of the employee';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."F_ADD_1" IS 'Address of Friend / Relative';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."F_ADD_2" IS 'Address of Friend / Relative';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."F_ADD_3" IS 'Address of Friend / Relative';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."F_ADD_4" IS 'Address of Friend / Relative';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."REF_PERSON_NAME" IS 'Name of the person to be contacted in Emergency';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."REF_PERSON_PHONE" IS 'Phone of the person to be contacted in Emergency';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."LOCATION" IS 'Location (eg Mumbai)';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."PUNCH_CARD_STATUS" IS 'Does the employee have Punch Card cum ID';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."DOB" IS 'Date of Birth';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."FATHER_OCCUPATION" IS 'Father''s Occupation';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."INSR_DETAILS" IS 'ESIC / any other Medi-Claim Details';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."CO_BUS" IS 'Office Bus code by which Employee Travells to the office';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."PICK_UP_POINT" IS 'Office Bus Pick Up Point';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."INCLUDE_DAD_HUSB_NAME" IS 'Include Father''s / Husband''s name in My Name';
   COMMENT ON COLUMN "COMMONMASTERS"."EMP_DETAILS"."NO_DAD_HUSB_IN_NAME" IS 'Do No Include Father''s / Husband''s name in My Name';
  GRANT SELECT ON "COMMONMASTERS"."EMP_DETAILS" TO "NEW_TIMECURR";
  GRANT SELECT ON "COMMONMASTERS"."EMP_DETAILS" TO "ITDECL";
  GRANT SELECT ON "COMMONMASTERS"."EMP_DETAILS" TO "TIMECURR";
  GRANT SELECT ON "COMMONMASTERS"."EMP_DETAILS" TO "SELFSERVICE";
