--------------------------------------------------------
--  DDL for Table SYSTEM_GRANTS_HISTORY
--------------------------------------------------------
  
  CREATE TABLE "COMMONMASTERS"."SYSTEM_GRANTS_HISTORY" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"ROLENAME" VARCHAR2(80 BYTE), 
	"ROLEDESC" VARCHAR2(100 BYTE), 
	"APPLSYSTEM" VARCHAR2(50 BYTE), 
	"MODULE" VARCHAR2(50 BYTE), 
	"COSTCODE" VARCHAR2(6 BYTE), 
	"PROJNO" VARCHAR2(10 BYTE), 
	"ROLE_ON_COSTCODE" VARCHAR2(4 BYTE), 
	"ROLE_ON_PROJNO" VARCHAR2(10 BYTE), 
	"DELETED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

