
  CREATE TABLE "COMMONMASTERS"."SYSTEM_GRANTS" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"ROLENAME" VARCHAR2(80 BYTE), 
	"ROLEDESC" VARCHAR2(100 BYTE), 
	"APPLSYSTEM" VARCHAR2(50 BYTE), 
	"MODULE" VARCHAR2(50 BYTE), 
	"COSTCODE" VARCHAR2(6 BYTE), 
	"PROJNO" VARCHAR2(10 BYTE), 
	"ROLE_ON_COSTCODE" VARCHAR2(4 BYTE), 
	"ROLE_ON_PROJNO" VARCHAR2(10 BYTE), 
	"PERSONID" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

  CREATE OR REPLACE TRIGGER "COMMONMASTERS"."TRIG_SYSTEM_GRANTS_DELETE" After
    Delete On system_grants
    For Each Row
Begin
    Insert Into system_grants_history (
        empno,
        rolename,
        roledesc,
        applsystem,
        module,
        costcode,
        projno,
        role_on_costcode,
        role_on_projno,
        deleted_date
    ) Values (
        :old.empno,
        :old.rolename,
        :old.roledesc,
        :old.applsystem,
        :old.module,
        :old.costcode,
        :old.projno,
        :old.role_on_costcode,
        :old.role_on_projno,
        sysdate
    );

End;
/
ALTER TRIGGER "COMMONMASTERS"."TRIG_SYSTEM_GRANTS_DELETE" ENABLE;


  GRANT FLASHBACK ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT DEBUG ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT REFERENCES ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT INDEX ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT ALTER ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_HR";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_HR";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_HR";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "STATIONERY";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "STATIONERY";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "STATIONERY";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TIME2010";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TIME2010";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "HR_APPL";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "HR_APPL";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "HR_APPL";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "LOGBOOK1";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "LOGBOOK1";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "LOGBOOK1";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "LOGBOOK1";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "AMS";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "AMS";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "AMS";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "AMS";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TIMECURR";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TIMECURR";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TIMECURR";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TIMECURR";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TCMPL_APP_CONFIG" WITH GRANT OPTION;
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SELFSERVICE";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SELFSERVICE";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SELFSERVICE";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SELFSERVICE";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RECRUIT";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RECRUIT";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RECRUIT";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RECRUIT";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAVEL";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAVEL";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAVEL";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAVEL";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAININGNEW";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAININGNEW";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAININGNEW";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TRAININGNEW";
  GRANT FLASHBACK ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT DEBUG ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT QUERY REWRITE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT ON COMMIT REFRESH ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT REFERENCES ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT INDEX ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT ALTER ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "RWM2";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "DMS";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "DMS";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "DMS";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "DMS";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TPL_UTILITIES";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SITE_QUERY";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "OSD";
  GRANT DELETE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "INSURANCE";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "INSURANCE";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "INSURANCE";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "INSURANCE";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "OSD";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "OSD";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "OSD";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TPL_UTILITIES";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TPL_UTILITIES";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "TPL_UTILITIES";
  GRANT UPDATE ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SITE_QUERY";
  GRANT SELECT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SITE_QUERY";
  GRANT INSERT ON "COMMONMASTERS"."SYSTEM_GRANTS" TO "SITE_QUERY";
