REM INSERTING into SELFSERVICE.SS_PUNCH_AUTO_TYPE_MAST
SET DEFINE OFF;
Insert into SELFSERVICE.SS_PUNCH_AUTO_TYPE_MAST (AUTO_PUNCH_TYPE,DESCRIPTION) values (1,'Lunch Auto Punch');
Insert into SELFSERVICE.SS_PUNCH_AUTO_TYPE_MAST (AUTO_PUNCH_TYPE,DESCRIPTION) values (2,'Inter Office Auto Punch');
commit;
