REM INSERTING into SELFSERVICE.SS_TABLETAG
SET DEFINE OFF;
Insert into SELFSERVICE.SS_TABLETAG (TABLETAG,DESCRIPTION) values (0,'SS_LEAVE_ADJ');
Insert into SELFSERVICE.SS_TABLETAG (TABLETAG,DESCRIPTION) values (1,'SS_LEAVEAPP');
Insert into SELFSERVICE.SS_TABLETAG (TABLETAG,DESCRIPTION) values (3,'SS_DEPU');
Insert into SELFSERVICE.SS_TABLETAG (TABLETAG,DESCRIPTION) values (2,'SS_ONDUTY');
Insert into SELFSERVICE.SS_TABLETAG (TABLETAG,DESCRIPTION) values (4,'SS_ONDUTYAPP');
Insert into SELFSERVICE.SS_TABLETAG (TABLETAG,DESCRIPTION) values (-1,'Only for HRD User');
