--------------------------------------------------------
--  DDL for View ACTUAL_TCM_PROJ_COST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."ACTUAL_TCM_PROJ_COST" ("YYMM", "PROJNO", "COSTCODE", "HOURS", "OTHOURS") AS 
  (SELECT A.YYMM,A.PROJNO,A.COSTCODE,SUM(NVL(A.HOURS,0))AS HOURS,
SUM(NVL(A.OTHOURS,0)) AS OTHOURS FROM TIMETRAN A, PROJMAST B
 WHERE B.PROJNO = A.PROJNO AND B.TCM_JOBS = 1
 GROUP BY  A.YYMM,A.PROJNO,A.COSTCODE)

;
