--------------------------------------------------------
--  DDL for View ACTUAL_TCM_PROJ_COST_TOT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."ACTUAL_TCM_PROJ_COST_TOT" ("YYMM", "PROJNO", "COSTCODE", "TOT_ACTUALHOURS") AS 
  (SELECT A.YYMM,A.PROJNO,A.COSTCODE,SUM(NVL(A.HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT_ACTUALHOURS FROM TIMETRAN A, PROJMAST B
 WHERE B.PROJNO = A.PROJNO AND B.TCM_JOBS = 1
 GROUP BY  A.YYMM,A.PROJNO,A.COSTCODE)

;
