--------------------------------------------------------
--  DDL for View EMP_PROJ_HRS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."EMP_PROJ_HRS" ("YYMM", "COSTCODE", "EMPNO", "NAME", "TCM_JOBS", "HOURS", "OTHOURS") AS 
  SELECT A.YYMM,A.COSTCODE,A.EMPNO,B.NAME,C.TCM_JOBS, SUM(NVL(A.HOURS,0)) AS HOURS,SUM(NVL(A.OTHOURS,0)) AS OTHOURS FROM TIMETRAN A,
EMPLMAST B,PROJMAST C  WHERE A.EMPNO = B.EMPNO AND A.PROJNO = C.PROJNO AND A.YYMM > '201003'
GROUP BY A.YYMM,A.COSTCODE,A.EMPNO,B.NAME,C.TCM_JOBS

;
