--------------------------------------------------------
--  DDL for View HOURS_DAILYOT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."HOURS_DAILYOT" ("YYMM", "EMPNO", "ASSIGN", "PROJNO", "AHOURS", "OTHOURS") AS 
  (SELECT yymm,EMPNO,ASSIGN,PROJNO,0 AS AHOURS, SUM(NVL(TOTAL,0)) AS OTHOURS FROM
TIME_OT
WHERE  WPCODE <> '4'  GROUP BY yymm,EMPNO,ASSIGN,PROJNO UNION
SELECT yymm,EMPNO,ASSIGN,PROJNO,SUM(NVL(TOTAL,0)),0 FROM TIME_DAILY
WHERE  WPCODE <> '4'  GROUP BY yymm,EMPNO,ASSIGN,PROJNO )

;
