--------------------------------------------------------
--  DDL for View ITHOURS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."ITHOURS" ("YYMM", "EMPNO", "NAME", "PROJNO", "HOURS", "OTHOURS", "TOT") AS 
  SELECT A.YYMM,A.EMPNO,SUBSTR(B.NAME,1,10)AS NAME,A.PROJNO,SUM(NVL(A.HOURS,0))AS HOURS,SUM(NVL(A.OTHOURS,0))AS OTHOURS,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOT  FROM TIMETRAN A,EMPLMAST B
WHERE A.COSTCODE = '0311' AND A.EMPNO = B.EMPNO GROUP BY A.YYMM,A.EMPNO,B.NAME,A.PROJNO

;
