--------------------------------------------------------
--  DDL for View JOB_PROJECTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."JOB_PROJECTIONS" ("PROJNO", "TCM_JOBS", "COSTCODE", "YYMONTH", "UPTOMARCH") AS 
  (SELECT A.PROJNO,B.TCM_JOBS,A.COSTCODE,'201903' AS YYMONTH, SUM(NVL(A.hours,0)) AS UPTOMARCH FROM prjcmast A, PROJMAST B WHERE A.PROJNO = B.PROJNO AND A.YYMM <= '201903' GROUP BY A.PROJNO,B.TCM_JOBS,A.COSTCODE
UNION
SELECT A.PROJNO,B.TCM_JOBS,A.COSTCODE,A.YYMM,A.hours FROM prjcmast A,PROJMAST B WHERE A.PROJNO = B.PROJNO AND A.YYMM > '201903' )
;
