--------------------------------------------------------
--  DDL for View MAYHRS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."MAYHRS" ("COSTCODE", "PROJ_TYPE", "TOTHOURS") AS 
  ((SELECT A.COSTCODE,'TCM' AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO AND A.YYMM = '200205' AND B.TCM_JOBS = 1 GROUP BY A.COSTCODE)
UNION
(SELECT A.COSTCODE,'NON TCM'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO AND A.YYMM = '200205' AND A.PROJNO NOT IN('1111400','2222400','5555400','6666400')
AND  B.TCM_JOBS = 0  AND B.COSTCODE not in('0402') and a.costcode not in('0237','0236') GROUP BY A.COSTCODE)
UNION
(SELECT B.PARENT,'DEPUTATION'as PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0))
FROM TIMETRAN A,EMPLMAST B WHERE A.EMPNO = B.EMPNO AND
A.YYMM = '200205' AND A.COSTCODE IN('0236','0237') GROUP BY B.PARENT)
union
(SELECT A.COSTCODE,'PROPOSALS'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM TIMETRAN A,PROJMAST B WHERE
A.PROJNO = B.PROJNO AND A.YYMM = '200205' AND B.COSTCODE = '0402'GROUP BY A.COSTCODE)
UNION
(SELECT A.COSTCODE,'TRAINING'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO AND A.YYMM = '200205' AND A.PROJNO = '6666400'
GROUP BY A.COSTCODE)
UNION
(SELECT A.COSTCODE,'VACATION'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM TIMETRAN A WHERE
A.YYMM = '200205' AND A.PROJNO IN('1111400','2222400') GROUP BY A.COSTCODE)
UNION
(SELECT A.COSTCODE,'AVAILABLE'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO AND A.YYMM = '200205' AND A.PROJNO = '5555400'
GROUP BY A.COSTCODE))

;
