--------------------------------------------------------
--  DDL for View ODD_TIMESHEET
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."ODD_TIMESHEET" ("YYMM", "EMPNO", "NAME", "PARENT", "ASSIGN", "PROJNO", "WPCODE", "ACTIVITY", "TOTAL") AS 
  (SELECT TIME_DAILY.YYMM YYMM,
    TIME_DAILY.EMPNO,
    emplmast.NAME ,
    TIME_DAILY.PARENT,
    TIME_DAILY.ASSIGN,
    TIME_DAILY.PROJNO,
    TIME_DAILY.WPCODE,
    TIME_DAILY.ACTIVITY,
    TIME_DAILY.TOTAL
  FROM TIMECURR.TIME_DAILY TIME_DAILY ,
    TIMECURR.EMPLMAST EMPLMAST
  WHERE TIMECURR.TIME_DAILY.EMPNO = TIMECURR.EMPLMAST.EMPNO
  AND TIME_DAILY.parent          <> TIME_DAILY.assign
  UNION
  SELECT TIME_OT.YYMM yymm,
    TIME_OT.EMPNO,
    emplmast.NAME ,
    TIME_OT.PARENT,
    TIME_OT.ASSIGN,
    TIME_OT.PROJNO,
    TIME_OT.WPCODE,
    TIME_OT.ACTIVITY,
    TIME_OT.TOTAL
  FROM TIMECURR.TIME_OT TIME_OT ,
    TIMECURR.EMPLMAST EMPLMAST
  WHERE TIMECURR.TIME_OT.EMPNO = TIMECURR.EMPLMAST.EMPNO
  AND TIME_ot.parent          <> time_ot.assign
  )
;
