--------------------------------------------------------
--  DDL for View OPENMAST_A0304
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."OPENMAST_A0304" ("PROJNO", "COSTCODE", "OPENLAST01", "CURR01", "OPEN01", "OPENLAST04", "CURR04", "OPEN04") AS 
  (SELECT PROJNO,COSTCODE,SUM(NVL(OPENLAST01,0))AS OPENLAST01,SUM(NVL(CURR01,0)) AS CURR01 ,SUM(NVL(OPENLAST01,0))+SUM(NVL(CURR01,0)) AS OPEN01 ,
SUM(NVL(OPENLAST04,0)) AS OPENLAST04,SUM(NVL(CURR04,0)) AS CURR04,SUM(NVL(OPENLAST04,0))+SUM(NVL(CURR04,0)) AS OPEN04 FROM OPENMAST_0304
GROUP BY PROJNO,COSTCODE)

;
