--------------------------------------------------------
--  DDL for View OPENMAST_COSTPROJACT1
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."OPENMAST_COSTPROJACT1" ("COSTCODE", "PROJNO", "ACTIVITY", "TOT1") AS 
  select  COSTCODE,
    PROJNO,
    ACTIVITY, sum(tot) as tot1 from
(
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1112
  WHERE YYMM < '201201'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )
UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1213
  WHERE YYMM < '201301'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )
UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1314
  WHERE YYMM < '201401'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )
)
group by
 COSTCODE,
    PROJNO,
    ACTIVITY

;
