--------------------------------------------------------
--  DDL for View OPENMAST_COSTPROJACT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."OPENMAST_COSTPROJACT" ("COSTCODE", "PROJNO", "ACTIVITY", "TOT") AS 
  select  COSTCODE,
    PROJNO,
    ACTIVITY, sum(tot) as tot from
(
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1112
  WHERE YYMM < '201201'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )
UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1213
  WHERE YYMM < '201301'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )
UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1314
  WHERE YYMM < '201401'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )
UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1415
  WHERE YYMM < '201501'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )  
 UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1516
  WHERE YYMM < '201601'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )  
UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1617
  WHERE YYMM < '201701'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )  

UNION
  (SELECT COSTCODE,
    PROJNO,
    ACTIVITY,
    SUM(NVL(HOURS,0))+SUM(NVL(OTHOURS,0)) AS TOT
  FROM TIMETRAN1718
  WHERE YYMM < '201801'
  GROUP BY COSTCODE,
    PROJNO,
    ACTIVITY
  )  

  
)
group by
 COSTCODE,
    PROJNO,
    ACTIVITY
;
