--------------------------------------------------------
--  DDL for View VEMPLMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."VEMPLMAST" ("EMPNO", "NAME", "ABBR", "EMPTYPE", "EMAIL", "ASSIGN", "PARENT", "DESGCODE", "PASSWORD", "DOB", "DOJ", "DOL", "DOR", "COSTHEAD", "COSTDY", "PROJMNGR", "PROJDY", "DBA", "DIRECTOR", "STATUS", "SUBMIT", "OFFICE", "PROJNO", "DIROP", "AMFI_USER", "AMFI_AUTH", "SECRETARY", "DO", "INV_AUTH", "JOB_INCHARGE", "COSTOPR", "MNGR", "IPADD", "PWD_CHGD", "DOC", "GRADE", "PROC_OPR", "REPORTO") AS 
  select "EMPNO","NAME","ABBR","EMPTYPE","EMAIL","ASSIGN","PARENT","DESGCODE","PASSWORD","DOB","DOJ","DOL","DOR","COSTHEAD","COSTDY","PROJMNGR","PROJDY","DBA","DIRECTOR","STATUS","SUBMIT","OFFICE","PROJNO","DIROP","AMFI_USER","AMFI_AUTH","SECRETARY","DO","INV_AUTH","JOB_INCHARGE","COSTOPR","MNGR","IPADD","PWD_CHGD","DOC","GRADE","PROC_OPR","REPORTO" from emplmast where nvl(status,0)=1
union
select "EMPNO","NAME","ABBR","EMPTYPE","EMAIL","ASSIGN","PARENT","DESGCODE","PASSWORD","DOB","DOJ","DOL","DOR","COSTHEAD","COSTDY","PROJMNGR","PROJDY","DBA","DIRECTOR","STATUS","SUBMIT","OFFICE","PROJNO","DIROP","AMFI_USER","AMFI_AUTH","SECRETARY","DO","INV_AUTH","JOB_INCHARGE","COSTOPR","MNGR","IPADD","PWD_CHGD","DOC","GRADE","PROC_OPR","REPORTO" from tcmemplmast WITH READ ONLY

;
