--------------------------------------------------------
--  DDL for View YEAR_SUM
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TIMECURR"."YEAR_SUM" ("YYMM", "COSTCODE", "PROJ_TYPE", "TOTHOURS") AS 
  ((SELECT A.YYMM,A.COSTCODE,'TCM' AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM
TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO AND A.PROJNO  not like '%30' AND B.TCM_JOBS = 1 GROUP BY A.YYMM,A.COSTCODE)
UNION
(SELECT A.YYMM,A.COSTCODE,'NON TCM BILL'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM
TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO  AND substr(A.PROJNO,1,5) NOT
IN('11114','22224','33334','55554','66664','E1114','E2224','E3334','E5554','E6664') AND B.PROJTYPE <> 'E'
AND  B.TCM_JOBS = 0  GROUP BY
A.YYMM,A.COSTCODE)
UNION
(SELECT A.YYMM,B.PARENT,'DEPUTATION'as PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0))
FROM TIMETRAN A,EMPLMAST B WHERE A.EMPNO = B.EMPNO AND A.COSTCODE IN('0236','0238') GROUP BY A.YYMM,B.PARENT)
union
(SELECT A.YYMM,A.COSTCODE,'PROPOSALS'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM
TIMETRAN A,PROJMAST B WHERE
A.PROJNO = B.PROJNO  AND B.TCM_JOBS = 0 AND B.PROJTYPE <> 'E'  GROUP BY
A.YYMM,A.COSTCODE)
UNION
(SELECT A.YYMM,A.COSTCODE,'EPC'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM TIMETRAN
A,PROJMAST B WHERE
A.PROJNO = B.PROJNO AND  B.PROJTYPE = 'E' AND  B.TCM_JOBS = 0  GROUP BY A.YYMM,A.COSTCODE)
UNION
(SELECT A.YYMM,A.COSTCODE,'TRAINING'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM
TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO AND substr(A.PROJNO,1,5) in('66664','E6664')
GROUP BY A.YYMM,A.COSTCODE)
UNION
(SELECT A.YYMM,A.COSTCODE,'VACATION'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM
TIMETRAN A WHERE  substr(A.PROJNO,1,5) IN('11114','22224','33334','E1114','E2224','E3334') GROUP BY A.YYMM,A.COSTCODE)
UNION
(SELECT A.YYMM,A.COSTCODE,'AVAILABLE'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM
TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO  AND substr(A.PROJNO,1,5) in ('55554','E5554')
GROUP BY A.YYMM,A.COSTCODE)
UNION
(SELECT A.YYMM,A.COSTCODE,'TCM NBILL'AS PROJ_TYPE,SUM(NVL(A.HOURS,0))+SUM(NVL(A.OTHOURS,0)) AS TOTHOURS FROM
TIMETRAN A,PROJMAST B
WHERE A.PROJNO = B.PROJNO AND A.PROJNO  like '%30' AND B.TCM_JOBS = 1 GROUP BY A.YYMM,A.COSTCODE))
;
