--------------------------------------------------------
--  DDL for View DM_VU_DESMAS_ALLOCATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ITINV_STK"."DM_VU_DESMAS_ALLOCATION" ("DESKID", "OFFICE", "FLOOR", "WING", "CABIN", "EMPNO1", "NAME1", "USERID1", "GRADE1", "DESG1", "DEPT1", "EMAIL1", "EMPNO2", "NAME2", "USERID2", "GRADE2", "DESG2", "EMAIL2", "DEPT2", "COMPNAME", "COMPUTER", "PCMODEL", "MONITOR1", "MONMODEL1", "MONITOR2", "MONMODEL2", "TELEPHONE", "TELMODEL", "PRINTER", "PRINTMODEL", "PC_RAM", "PC_GCARD") AS 
  SELECT 
    "DESKID","OFFICE","FLOOR","WING","CABIN","EMPNO1","NAME1","USERID1","GRADE1","DESG1","DEPT1","EMAIL1","EMPNO2","NAME2","USERID2","GRADE2","DESG2","EMAIL2","DEPT2","COMPNAME","COMPUTER","PCMODEL","MONITOR1","MONMODEL1","MONITOR2","MONMODEL2","TELEPHONE","TELMODEL","PRINTER","PRINTMODEL",pc_ram,pc_gcard
FROM
dms.desmas_Allocation_all
;
