--------------------------------------------------------
--  DDL for View VU_ASSET_MAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ITINV_STK"."VU_ASSET_MAST" ("SAP_ASSET_CODE", "SAP_ASSET_CODE_SR_NO", "ASSET_DESCRIPTION", "COUNTRY_DESC", "ASSET_CLASS", "ASSET_CLASS_DESC", "SUB_ASSET_TYPE", "SUB_ASSET_DESC", "LOCATION", "LOCATION_DESC", "TECH_GROUP_ID", "TECH_GROUP_DESC", "TECH_SPEC", "ASSET_MAKE", "ASSET_MODEL", "SAP_PR_NUM", "SAP_PR_DATE", "SAP_PO_NO", "SAP_PO_DATE", "SAP_VENDOR", "VAL_4_ESTIMATE", "MFG_SR_NO", "MR_NUM", "MR_DATE", "VEND_INV_NUM", "VEND_INV_DATE", "LR_NUM", "LR_DATE", "TRANSPORT_DETAILS", "ASSET_AQUI_DATE", "ASSET_INSTALL_DATE", "SITE_GRR_NUM", "SITE_GRR_DATE", "SITE_INWARD_REF", "SITE_INWARD_DATE", "REMARKS", "ASSET_RANGE", "AMS_ASSET_ID", "TICB_BAR_CODE", "REQUESTER_DEPT", "REQUESTED_BY", "ASSET_STATUS", "WARRANTY_END_DATE", "ASSET_NAME", "LABEL_PRINTED", "UPLOAD_ORDER", "DEPT_GROUP", "ASSET_DESK_ID", "GR_ID", "ASSET_CLASS_GROUP", "LOCATION_DEPT_ID") AS 
  SELECT 
    "SAP_ASSET_CODE","SAP_ASSET_CODE_SR_NO","ASSET_DESCRIPTION","COUNTRY_DESC","ASSET_CLASS","ASSET_CLASS_DESC","SUB_ASSET_TYPE","SUB_ASSET_DESC","LOCATION","LOCATION_DESC","TECH_GROUP_ID","TECH_GROUP_DESC","TECH_SPEC","ASSET_MAKE","ASSET_MODEL","SAP_PR_NUM","SAP_PR_DATE","SAP_PO_NO","SAP_PO_DATE","SAP_VENDOR","VAL_4_ESTIMATE","MFG_SR_NO","MR_NUM","MR_DATE","VEND_INV_NUM","VEND_INV_DATE","LR_NUM","LR_DATE","TRANSPORT_DETAILS","ASSET_AQUI_DATE","ASSET_INSTALL_DATE","SITE_GRR_NUM","SITE_GRR_DATE","SITE_INWARD_REF","SITE_INWARD_DATE","REMARKS","ASSET_RANGE","AMS_ASSET_ID","TICB_BAR_CODE","REQUESTER_DEPT","REQUESTED_BY","ASSET_STATUS","WARRANTY_END_DATE","ASSET_NAME","LABEL_PRINTED","UPLOAD_ORDER","DEPT_GROUP","ASSET_DESK_ID","GR_ID","ASSET_CLASS_GROUP","LOCATION_DEPT_ID"
FROM 
    AMS.AS_VU_ASSET_MASTER
;
