--------------------------------------------------------
--  File created - Tuesday-January-04-2022   
--------------------------------------------------------
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_COMMON_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_COMMON_ACTIONS_MAPPING.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_EMP_CONTACT_INFO.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_EMP_EXITS.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_EMP_EXIT_APPROVALS.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_EXIT_APPROVALS_LOG.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_EXIT_APPROVAL_RESET_LOG.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_FILES.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_MAIL_LOG.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_ROLES.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_ROLE_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_USER_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\TABLES\OFB_USER_ROLES.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_COSTMAST.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_DERIVED_ROLES.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_DESGMAST.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_EMPLMAST.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_EMP_EXITS.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_EMP_EXIT_APPROVALS.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_USERIDS.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\OFB_VU_USER_ROLES_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\VIEWS\TO_BE_DELETED.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_FILES_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_EMP_CONTACT_INFO_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_EMP_EXIT_APPROVALS_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_ROLE_ACTIONS_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_COMMON_ACTIONS_MAPPIN_UK1.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_EMP_EXIT_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_USER_ACTIONS_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_ROLE_ACTIONS_INDEX1.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_ROLES_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_USER_ACTIONS_UK1.sql
@D:\GitWorkSpace\DB-OffBoarding\INDEXES\OFB_COMMON_ACTIONS_PK.sql
@D:\GitWorkSpace\DB-OffBoarding\TRIGGERS\TRIG_EXIT_APPROVALS_01.sql
@D:\GitWorkSpace\DB-OffBoarding\TRIGGERS\TRIG_ROLES_01.sql
@D:\GitWorkSpace\DB-OffBoarding\TRIGGERS\TRIG_ROLE_ACTIONS_01.sql
@D:\GitWorkSpace\DB-OffBoarding\TRIGGERS\TRIG_USER_ACTIONS_01.sql
@D:\GitWorkSpace\DB-OffBoarding\PROCEDURES\SEND_MAIL_FROM_API.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\GENERATE_CSHARP_CODE.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\OFB.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\OFB_APPROVAL_STATUS.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\OFB_EXIT.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\OFB_FILES_MANAGE.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\OFB_SEND_MAIL.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\OFB_USER.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGES\SCHEMA_OBJECTS.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\GENERATE_CSHARP_CODE.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\OFB.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\OFB_APPROVAL_STATUS.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\OFB_EXIT.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\OFB_FILES_MANAGE.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\OFB_SEND_MAIL.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\OFB_USER.sql
@D:\GitWorkSpace\DB-OffBoarding\PACKAGE_BODIES\SCHEMA_OBJECTS.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_FILES.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_USER_ROLES.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_EMP_CONTACT_INFO.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_ROLE_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_COMMON_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_ROLES.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_USER_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_COMMON_ACTIONS_MAPPING.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_EMP_EXIT_APPROVALS.sql
@D:\GitWorkSpace\DB-OffBoarding\CONSTRAINTS\OFB_EMP_EXITS.sql
@D:\GitWorkSpace\DB-OffBoarding\REF_CONSTRAINTS\OFB_COMMON_ACTIONS_MAPPING.sql
@D:\GitWorkSpace\DB-OffBoarding\REF_CONSTRAINTS\OFB_ROLE_ACTIONS.sql
@D:\GitWorkSpace\DB-OffBoarding\REF_CONSTRAINTS\OFB_USER_ACTIONS.sql
