--------------------------------------------------------
--  DDL for View DESMAS_ALLOCATION_ALL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."DESMAS_ALLOCATION_ALL" ("DESKID", "OFFICE", "FLOOR", "WING", "CABIN", "EMPNO1", "NAME1", "USERID1", "GRADE1", "DESG1", "DEPT1", "SHIFT1", "EMAIL1", "EMPNO2", "NAME2", "USERID2", "GRADE2", "DESG2", "SHIFT2", "EMAIL2", "DEPT2", "COMPNAME", "COMPUTER", "PCMODEL", "MONITOR1", "MONMODEL1", "MONITOR2", "MONMODEL2", "TELEPHONE", "TELMODEL", "PRINTER", "PRINTMODEL", "DOCSTN", "DOCSTNMODEL", "PC_RAM", "PC_GCARD") AS 
  select "DESKID","OFFICE","FLOOR","WING","CABIN","EMPNO1","NAME1","USERID1","GRADE1","DESG1","DEPT1","SHIFT1","EMAIL1","EMPNO2","NAME2","USERID2","GRADE2","DESG2","SHIFT2","EMAIL2","DEPT2","COMPNAME","COMPUTER","PCMODEL","MONITOR1","MONMODEL1","MONITOR2","MONMODEL2","TELEPHONE","TELMODEL","PRINTER","PRINTMODEL","DOCSTN","DOCSTNMODEL","PC_RAM","PC_GCARD" from dms.desmas_allocation_all
;
