--------------------------------------------------------
--  DDL for View SS_COSTMASTAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_COSTMASTAS" ("COSTCODE", "NAME", "ABBR", "HOD", "HOD_ABBR", "DY_HOD", "NOOFEMPS", "COSTGROUP", "GROUPS", "TM01_GRP", "TMA_GRP", "COST_TYPE", "ACTIVITY", "GROUP_CHART", "COSTGRP", "ITALIAN_NAME", "BU", "CHANGED_NEMPS", "INOFFICE", "SECRETARY", "COMP", "ACTIVE", "SDATE", "EDATE") AS 
  select "COSTCODE","NAME","ABBR","HOD","HOD_ABBR","DY_HOD","NOOFEMPS","COSTGROUP","GROUPS","TM01_GRP","TMA_GRP","COST_TYPE","ACTIVITY","GROUP_CHART","COSTGRP","ITALIAN_NAME","BU","CHANGED_NEMPS","INOFFICE","SECRETARY","COMP","ACTIVE","SDATE","EDATE" from commonmasters.costmast
;
