--------------------------------------------------------
--  DDL for View SS_EMPLMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_EMPLMAST" ("EMPNO", "NAME", "ABBR", "EMPTYPE", "EMAIL", "ASSIGN", "PARENT", "DESGCODE", "PASSWORD", "DOB", "DOJ", "DOL", "DOR", "COSTHEAD", "COSTDY", "PROJMNGR", "PROJDY", "DBA", "DIRECTOR", "STATUS", "SUBMIT", "OFFICE", "PROJNO", "DIROP", "AMFI_USER", "AMFI_AUTH", "SECRETARY", "DO", "INV_AUTH", "JOB_INCHARGE", "COSTOPR", "MNGR", "IPADD", "PWD_CHGD", "DOC", "GRADE", "PROC_OPR", "REPORTO", "COMPANY", "TRANS_OUT", "TRANS_IN", "HR_OPR", "SEX", "USER_DOMAIN", "WEB_ITDECL", "CATEGORY", "ESI_COVER", "EMP_HOD", "SEATREQ", "NEWEMP", "ONDEPUTATION", "OLDCO", "MARRIED", "JOBTITLE", "EOW", "EOW_DATE", "EOW_WEEK", "LASTNAME", "FIRSTNAME", "MIDDLENAME", "PFSLNO", "PAYROLL", "EXPATRIATE", "PERSONID", "METAID", "AD_EMAIL") AS 
  SELECT "EMPNO",
    "NAME",
    "ABBR",
    "EMPTYPE",
    "EMAIL",
    "ASSIGN",
    "PARENT",
    "DESGCODE",
    "PASSWORD",
    "DOB",
    "DOJ",
    "DOL",
    "DOR",
    "COSTHEAD",
    "COSTDY",
    "PROJMNGR",
    "PROJDY",
    "DBA",
    "DIRECTOR",
    "STATUS",
    "SUBMIT",
    "OFFICE",
    "PROJNO",
    "DIROP",
    "AMFI_USER",
    "AMFI_AUTH",
    "SECRETARY",
    "DO",
    "INV_AUTH",
    "JOB_INCHARGE",
    "COSTOPR",
    "MNGR",
    "IPADD",
    "PWD_CHGD",
    "DOC",
    "GRADE",
    "PROC_OPR",
    "REPORTO",
    "COMPANY",
    "TRANS_OUT",
    "TRANS_IN",
    "HR_OPR",
    "SEX",
    "USER_DOMAIN",
    "WEB_ITDECL",
    "CATEGORY",
    "ESI_COVER",
    "EMP_HOD",
    "SEATREQ",
    "NEWEMP",
    "ONDEPUTATION",
    "OLDCO",
    "MARRIED",
    "JOBTITLE",
    "EOW",
    "EOW_DATE",
    "EOW_WEEK",
    "LASTNAME",
    "FIRSTNAME",
    "MIDDLENAME",
    "PFSLNO",
    "PAYROLL",
    expatriate,
    personid,
    metaid,
    ad_email
    
  FROM commonmasters.emplmast
;
  GRANT SELECT ON "SELFSERVICE"."SS_EMPLMAST" TO "TCMPL_APP_CONFIG";
