--------------------------------------------------------
--  DDL for View SS_EMPLMAST_EDTICB
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_EMPLMAST_EDTICB" ("EMPNO", "NAME", "ABBR", "EMPTYPE", "EMAIL", "ASSIGN", "PARENT", "DESGCODE", "PASSWORD", "DOB", "DOJ", "DOL", "DOR", "COSTHEAD", "COSTDY", "PROJMNGR", "PROJDY", "DBA", "DIRECTOR", "STATUS", "SUBMIT", "OFFICE", "PROJNO", "DIROP", "AMFI_USER", "AMFI_AUTH", "SECRETARY", "DO", "INV_AUTH", "JOB_INCHARGE", "COSTOPR", "MNGR", "IPADD", "PWD_CHGD", "DOC", "GRADE", "PROC_OPR", "REPORTO", "COMPANY", "TRANS_OUT", "TRANS_IN", "HR_OPR", "SEX", "USER_DOMAIN", "WEB_ITDECL", "CATEGORY", "ESI_COVER", "DOMAIN_LOGIN") AS 
  Select "EMPNO","NAME","ABBR","EMPTYPE","EMAIL","ASSIGN","PARENT","DESGCODE","PASSWORD","DOB","DOJ","DOL","DOR","COSTHEAD","COSTDY","PROJMNGR","PROJDY","DBA","DIRECTOR","STATUS","SUBMIT","OFFICE","PROJNO","DIROP","AMFI_USER","AMFI_AUTH","SECRETARY","DO","INV_AUTH","JOB_INCHARGE","COSTOPR","MNGR","IPADD","PWD_CHGD","DOC","GRADE","PROC_OPR","REPORTO","COMPANY","TRANS_OUT","TRANS_IN","HR_OPR","SEX","USER_DOMAIN","WEB_ITDECL","CATEGORY","ESI_COVER","DOMAIN_LOGIN" from commonmasters.EmplMast
Where COMPANY='EDT '
Or empno in('02320')
 WITH READ ONLY
;
