--------------------------------------------------------
--  DDL for View SS_EMPLMAST_WIN_ID
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_EMPLMAST_WIN_ID" ("EMPNO", "NAME", "ABBR", "EMPTYPE", "EMAIL", "ASSIGN", "PARENT", "DESGCODE", "PASSWORD", "DOB", "DOJ", "DOL", "DOR", "COSTHEAD", "COSTDY", "PROJMNGR", "PROJDY", "DBA", "DIRECTOR", "STATUS", "SUBMIT", "OFFICE", "PROJNO", "DIROP", "AMFI_USER", "AMFI_AUTH", "SECRETARY", "DO", "INV_AUTH", "JOB_INCHARGE", "COSTOPR", "MNGR", "IPADD", "PWD_CHGD", "DOC", "GRADE", "PROC_OPR", "REPORTO", "COMPANY", "TRANS_OUT", "TRANS_IN", "HR_OPR", "SEX", "USER_DOMAIN", "WEB_ITDECL", "CATEGORY", "ESI_COVER", "EMP_HOD", "SEATREQ", "NEWEMP", "ONDEPUTATION", "OLDCO", "MARRIED", "JOBTITLE", "EOW", "EOW_DATE", "EOW_WEEK", "USERIDS_OFFICE", "USERIDS_WIN_ID", "DOMAIN") AS 
  SELECT a."EMPNO",
    a."NAME",
    a."ABBR",
    a."EMPTYPE",
    a."EMAIL",
    a."ASSIGN",
    a."PARENT",
    a."DESGCODE",
    a."PASSWORD",
    a."DOB",
    a."DOJ",
    a."DOL",
    a."DOR",
    a."COSTHEAD",
    a."COSTDY",
    a."PROJMNGR",
    a."PROJDY",
    a."DBA",
    a."DIRECTOR",
    a."STATUS",
    a."SUBMIT",
    a."OFFICE",
    a."PROJNO",
    a."DIROP",
    a."AMFI_USER",
    a."AMFI_AUTH",
    a."SECRETARY",
    a."DO",
    a."INV_AUTH",
    a."JOB_INCHARGE",
    a."COSTOPR",
    a."MNGR",
    a."IPADD",
    a."PWD_CHGD",
    a."DOC",
    a."GRADE",
    a."PROC_OPR",
    a."REPORTO",
    a."COMPANY",
    a."TRANS_OUT",
    a."TRANS_IN",
    a."HR_OPR",
    a."SEX",
    a."USER_DOMAIN",
    a."WEB_ITDECL",
    a."CATEGORY",
    a."ESI_COVER",
    a."EMP_HOD",
    a."SEATREQ",
    a."NEWEMP",
    a."ONDEPUTATION",
    a."OLDCO",
    a."MARRIED",
    a."JOBTITLE",
    a."EOW",
    a."EOW_DATE",
    a."EOW_WEEK",
    b.office AS Userids_office,
    b.userid AS userids_win_id,
    b.domain
  FROM SS_EmplMast A,
    UserIDs B
  WHERE A.EmpNo = B.EmpNo
;
