--------------------------------------------------------
--  DDL for View SS_LEAVEAPP_EDTICB
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_LEAVEAPP_EDTICB" ("APP_NO", "EMPNO", "APP_DATE", "REP_TO", "PROJNO", "CARETAKER", "LEAVEPERIOD", "LEAVETYPE", "BDATE", "EDATE", "REASON", "MCERT", "WORK_LDATE", "RESM_DATE", "CONTACT_ADD", "CONTACT_PHN", "CONTACT_STD", "LAST_HRS", "LAST_MN", "RESM_HRS", "RESM_MN", "DATAENTRYBY", "OFFICE", "HOD_APPRL", "HOD_APPRL_DT", "HOD_CODE", "HRD_APPRL", "HRD_APPRL_DT", "HRD_CODE", "DISCREPANCY", "USER_TCP_IP", "HOD_TCP_IP", "HRD_TCP_IP", "HODREASON", "HRDREASON", "HD_DATE", "HD_PART") AS 
  Select "APP_NO","EMPNO","APP_DATE","REP_TO","PROJNO","CARETAKER","LEAVEPERIOD","LEAVETYPE","BDATE","EDATE","REASON","MCERT","WORK_LDATE","RESM_DATE","CONTACT_ADD","CONTACT_PHN","CONTACT_STD","LAST_HRS","LAST_MN","RESM_HRS","RESM_MN","DATAENTRYBY","OFFICE","HOD_APPRL","HOD_APPRL_DT","HOD_CODE","HRD_APPRL","HRD_APPRL_DT","HRD_CODE","DISCREPANCY","USER_TCP_IP","HOD_TCP_IP","HRD_TCP_IP","HODREASON","HRDREASON","HD_DATE","HD_PART" from SelfService_EDTicb.SS_LeaveApp WITH READ ONLY
;
