--------------------------------------------------------
--  DDL for View SS_OTMASTER_EDTICB
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_OTMASTER_EDTICB" ("EMPNO", "MON", "YYYY", "MONTH", "OT", "CO", "APP_DATE", "USER_TCP_IP", "HOD_APPRL", "HOD_CODE", "HOD_TCP_IP", "HOD_APPRL_DT", "HOD_REMARKS", "HRD_APPRL", "HRD_CODE", "HRD_TCP_IP", "HRD_APPRL_DT", "HRD_REMARKS", "APP_NO", "HOD_APPRD_OT", "HOD_APPRD_CO", "HRD_APPRD_OT", "HRD_APPRD_CO", "HRD_ADJUSTMENT_OT", "HRD_SUNDAY_OT") AS 
  Select "EMPNO","MON","YYYY","MONTH","OT","CO","APP_DATE","USER_TCP_IP","HOD_APPRL","HOD_CODE","HOD_TCP_IP","HOD_APPRL_DT","HOD_REMARKS","HRD_APPRL","HRD_CODE","HRD_TCP_IP","HRD_APPRL_DT","HRD_REMARKS","APP_NO","HOD_APPRD_OT","HOD_APPRD_CO","HRD_APPRD_OT","HRD_APPRD_CO","HRD_ADJUSTMENT_OT","HRD_SUNDAY_OT" From SelfService_EDTicb.SS_OTMaster WITH READ ONLY
;
