--------------------------------------------------------
--  DDL for View SS_ONDUTYAPP_EDTICB
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_ONDUTYAPP_EDTICB" ("EMPNO", "HH", "MM", "PDATE", "DD", "MON", "YYYY", "TYPE", "APP_NO", "DESCRIPTION", "HOD_APPRL", "HOD_APPRL_DT", "HOD_CODE", "HRD_APPRL", "HRD_APPRL_DT", "HRD_CODE", "APP_DATE", "HH1", "MM1", "REASON", "USER_TCP_IP", "HOD_TCP_IP", "HRD_TCP_IP", "HODREASON", "HRDREASON", "ODTYPE") AS 
  Select "EMPNO","HH","MM","PDATE","DD","MON","YYYY","TYPE","APP_NO","DESCRIPTION","HOD_APPRL","HOD_APPRL_DT","HOD_CODE","HRD_APPRL","HRD_APPRL_DT","HRD_CODE","APP_DATE","HH1","MM1","REASON","USER_TCP_IP","HOD_TCP_IP","HRD_TCP_IP","HODREASON","HRDREASON","ODTYPE" 
from SelfService_EDTICB.SS_OnDutyApp WITH READ ONLY
;
