--------------------------------------------------------
--  DDL for View SS_VU_CONTMAST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "SELFSERVICE"."SS_VU_CONTMAST" ("PUNCHNO", "ENTRYDATE", "EMPNO") AS 
  (

SELECT A.PUNCHNO,A.ENTRYDATE, A.EMPNO FROM SS_CONTMAST A, (

SELECT PUNCHNO, MAX(ENTRYDATE) ENTRYDATE FROM 
SS_CONTMAST GROUP BY PUNCHNO ) b WHERE A.PUNCHNO=B.PUNCHNO AND A.ENTRYDATE=B.ENTRYDATE
)
;
