--------------------------------------------------------
--  Constraints for Table DM_GUESTMASTER
--------------------------------------------------------

  ALTER TABLE "DM_GUESTMASTER" ADD CONSTRAINT "DM_GUESTMASTER_PK" PRIMARY KEY ("GNUM")
  USING INDEX  ENABLE;
  ALTER TABLE "DM_GUESTMASTER" MODIFY ("GTODATE" NOT NULL ENABLE);
  ALTER TABLE "DM_GUESTMASTER" MODIFY ("GFROMDATE" NOT NULL ENABLE);
  ALTER TABLE "DM_GUESTMASTER" MODIFY ("GNAME" NOT NULL ENABLE);
  ALTER TABLE "DM_GUESTMASTER" MODIFY ("GNUM" NOT NULL ENABLE);
