--------------------------------------------------------
--  Constraints for Table DM_LAPTOP_PERMT
--------------------------------------------------------

  ALTER TABLE "DM_LAPTOP_PERMT" ADD CONSTRAINT "DM_LAPTOP_PERMT_PK" PRIMARY KEY ("EMPNO", "BARCODE", "ISSUEDATE")
  USING INDEX  ENABLE;
  ALTER TABLE "DM_LAPTOP_PERMT" MODIFY ("ISSUEDATE" NOT NULL ENABLE);
  ALTER TABLE "DM_LAPTOP_PERMT" MODIFY ("BARCODE" NOT NULL ENABLE);
  ALTER TABLE "DM_LAPTOP_PERMT" MODIFY ("EMPNO" NOT NULL ENABLE);
