--------------------------------------------------------
--  Constraints for Table DM_NEWJOIN_TRANS
--------------------------------------------------------

  ALTER TABLE "DM_NEWJOIN_TRANS" ADD CONSTRAINT "DM_NEWJOIN_TRANS_PK" PRIMARY KEY ("NEWJOINREQNUM", "NEWJOINREQDATE", "EMPNO")
  USING INDEX  ENABLE;
  ALTER TABLE "DM_NEWJOIN_TRANS" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "DM_NEWJOIN_TRANS" MODIFY ("NEWJOINREQDATE" NOT NULL ENABLE);
  ALTER TABLE "DM_NEWJOIN_TRANS" MODIFY ("NEWJOINREQNUM" NOT NULL ENABLE);
