--------------------------------------------------------
--  Constraints for Table DM_PENDING_PC_LOCK
--------------------------------------------------------

  ALTER TABLE "DM_PENDING_PC_LOCK" ADD CONSTRAINT "DM_PENDING_PC_LOCK_PK" PRIMARY KEY ("EMPNO", "TDATE", "PCNAME")
  USING INDEX  ENABLE;
  ALTER TABLE "DM_PENDING_PC_LOCK" MODIFY ("PCNAME" NOT NULL ENABLE);
  ALTER TABLE "DM_PENDING_PC_LOCK" MODIFY ("TDATE" NOT NULL ENABLE);
  ALTER TABLE "DM_PENDING_PC_LOCK" MODIFY ("EMPNO" NOT NULL ENABLE);
