--------------------------------------------------------
--  Constraints for Table DM_TRAN_HIST_20100416
--------------------------------------------------------

  ALTER TABLE "DM_TRAN_HIST_20100416" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "DM_TRAN_HIST_20100416" MODIFY ("DESK_FLAG" NOT NULL ENABLE);
  ALTER TABLE "DM_TRAN_HIST_20100416" MODIFY ("DESKID" NOT NULL ENABLE);
  ALTER TABLE "DM_TRAN_HIST_20100416" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "DM_TRAN_HIST_20100416" MODIFY ("MOVEREQNUM" NOT NULL ENABLE);
