--------------------------------------------------------
--  Constraints for Table DM_TASKFORCETRAN
--------------------------------------------------------

  ALTER TABLE "DM_TASKFORCETRAN" ADD CONSTRAINT "DM_TASKFORCETRAN_PK" PRIMARY KEY ("EMPNO", "TID", "SINCEDATE")
  USING INDEX  ENABLE;
  ALTER TABLE "DM_TASKFORCETRAN" MODIFY ("SINCEDATE" NOT NULL ENABLE);
  ALTER TABLE "DM_TASKFORCETRAN" MODIFY ("TID" NOT NULL ENABLE);
  ALTER TABLE "DM_TASKFORCETRAN" MODIFY ("EMPNO" NOT NULL ENABLE);
