--------------------------------------------------------
--  Constraints for Table SS_REJOIN
--------------------------------------------------------

  ALTER TABLE "SS_REJOIN" ADD CONSTRAINT "SS_REJOIN_PK" PRIMARY KEY ("EMPNO", "JOINDATE")
  USING INDEX  ENABLE;
  ALTER TABLE "SS_REJOIN" MODIFY ("JOINDATE" NOT NULL ENABLE);
  ALTER TABLE "SS_REJOIN" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SS_REJOIN" MODIFY ("REJOINREQDATE" NOT NULL ENABLE);
  ALTER TABLE "SS_REJOIN" MODIFY ("REJOINREQNUM" NOT NULL ENABLE);
