--------------------------------------------------------
--  Constraints for Table EMP_DETAILS_4_PP
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_4_PP" MODIFY ("R_ADD_2" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_4_PP" MODIFY ("R_ADD_1" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_4_PP" MODIFY ("PHONE_OFF" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_4_PP" MODIFY ("MAIL_ID" NOT NULL ENABLE);
