--------------------------------------------------------
--  Constraints for Table EMP_BLOOD_GROUP_TYPE
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_BLOOD_GROUP_TYPE" ADD CONSTRAINT "CHK_UPPER" CHECK (code = upper(code)
) ENABLE NOVALIDATE;
  ALTER TABLE "COMMONMASTERS"."EMP_BLOOD_GROUP_TYPE" ADD CONSTRAINT "PK_BGT" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "COMMONMASTERS"."EMP_BLOOD_GROUP_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_BLOOD_GROUP_TYPE" MODIFY ("CODE" NOT NULL ENABLE);
