--------------------------------------------------------
--  Constraints for Table EMP_SUP_ANNUATION
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_SUP_ANNUATION" ADD CONSTRAINT "EMP_SUP_ANNUATION_PK" PRIMARY KEY ("EMPNO", "NOM_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "COMMONMASTERS"."EMP_SUP_ANNUATION" MODIFY ("NOM_NAME" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_SUP_ANNUATION" MODIFY ("EMPNO" NOT NULL ENABLE);
