--------------------------------------------------------
--  Constraints for Table EMP_RELATION_MAST
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_RELATION_MAST" ADD CONSTRAINT "U_REL_DESC" UNIQUE ("DESCRIPTION")
  USING INDEX  ENABLE;
  ALTER TABLE "COMMONMASTERS"."EMP_RELATION_MAST" ADD CONSTRAINT "CHK_REL_CASE" CHECK (description = Upper(description)
) ENABLE NOVALIDATE;
  ALTER TABLE "COMMONMASTERS"."EMP_RELATION_MAST" ADD CONSTRAINT "PK_RELATION" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE;
