--------------------------------------------------------
--  Constraints for Table EMP_BUS_MASTER
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_BUS_MASTER" ADD CONSTRAINT "CHK_CAPS" CHECK (CODE = UPPER(CODE) AND DESCRIPTION = UPPER(DESCRIPTION)
) ENABLE NOVALIDATE;
  ALTER TABLE "COMMONMASTERS"."EMP_BUS_MASTER" ADD CONSTRAINT "PK_BUS_CODE" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "COMMONMASTERS"."EMP_BUS_MASTER" MODIFY ("CODE" NOT NULL ENABLE);
