--------------------------------------------------------
--  Constraints for Table EMP_OCCUPATION
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_OCCUPATION" ADD CONSTRAINT "CHK_OCC_U_DESC" UNIQUE ("DESCRIPTION")
  USING INDEX  ENABLE;
  ALTER TABLE "COMMONMASTERS"."EMP_OCCUPATION" ADD CONSTRAINT "CHK_OCC_CASE" CHECK (description=upper(description)
) ENABLE NOVALIDATE;
  ALTER TABLE "COMMONMASTERS"."EMP_OCCUPATION" ADD CONSTRAINT "PK_OCCUPATION" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE;
