--------------------------------------------------------
--  Constraints for Table EMP_LOCK_STATUS
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_LOCK_STATUS" ADD CONSTRAINT "EMP_LOCK_STATUS_PK" PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE;
  ALTER TABLE "COMMONMASTERS"."EMP_LOCK_STATUS" MODIFY ("FMLY_LOCK_OPEN" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_LOCK_STATUS" MODIFY ("PRIM_LOCK_OPEN" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_LOCK_STATUS" MODIFY ("EMPNO" NOT NULL ENABLE);
