--------------------------------------------------------
--  Constraints for Table EMP_DETAILS_20051228
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_20051228" MODIFY ("R_ADD_2" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_20051228" MODIFY ("R_ADD_1" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_20051228" MODIFY ("PHONE_OFF" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_20051228" MODIFY ("MAIL_ID" NOT NULL ENABLE);
