--------------------------------------------------------
--  Constraints for Table EMP_DETAILS_08DEC2010
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_08DEC2010" MODIFY ("R_ADD_2" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_08DEC2010" MODIFY ("R_ADD_1" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_08DEC2010" MODIFY ("PHONE_OFF" NOT NULL ENABLE);
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS_08DEC2010" MODIFY ("MAIL_ID" NOT NULL ENABLE);
