--------------------------------------------------------
--  Constraints for Table EMP_DETAILS
--------------------------------------------------------

  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS" ADD CONSTRAINT "CHK_CASE" CHECK ("NAME"=UPPER("NAME") AND "SURNAME"=UPPER("SURNAME") AND "FATHER_NAME"=UPPER("FATHER_NAME") AND "DOMAIN_LOGIN"=LOWER("DOMAIN_LOGIN") AND "MAIL_ID"=LOWER("MAIL_ID") AND "PASSPORT_NO"=UPPER("PASSPORT_NO") AND "PASSPORT_ISSUED_AT"=UPPER("PASSPORT_ISSUED_AT") AND "PAN"=UPPER("PAN")) ENABLE NOVALIDATE;
  ALTER TABLE "COMMONMASTERS"."EMP_DETAILS" ADD CONSTRAINT "PK_EMPDETAILS" PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE;
