--------------------------------------------------------
--  DDL for Table AD_TEMP_1
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."AD_TEMP_1" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"LOCATION" VARCHAR2(20 BYTE), 
	"TELEXTN" VARCHAR2(10 BYTE), 
	"MOBILE" VARCHAR2(10 BYTE), 
	"TOUPDATE" NUMBER(1,0), 
	"MODDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
