--------------------------------------------------------
--  DDL for Table EMP_PUNCH_4_9794
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."EMP_PUNCH_4_9794" 
   (	"CHAR_EMPNO" VARCHAR2(5 BYTE), 
	"FULL_NAME" VARCHAR2(26 BYTE), 
	"PPDATE" VARCHAR2(10 BYTE), 
	"D_DAY" CHAR(3 BYTE), 
	"FIRST_PUNCH_ADJ" VARCHAR2(4000 BYTE), 
	"LAST_PUNCH_ADJ" VARCHAR2(4000 BYTE), 
	"MORN_TEA_PUNCH" VARCHAR2(4000 BYTE), 
	"MORN_BREAK" VARCHAR2(4000 BYTE), 
	"LUNCH" VARCHAR2(4000 BYTE), 
	"EVENING_TEA" VARCHAR2(4000 BYTE), 
	"EVENING_BREAK" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
