--------------------------------------------------------
--  DDL for Table FTP_ADMIN_USER
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."FTP_ADMIN_USER" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"USERID" VARCHAR2(25 BYTE), 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."FTP_ADMIN_USER"."ISACTIVE" IS '0 - Inactive, 1 - Active';
