
  CREATE TABLE "SELFSERVICE"."HSE_QUIZ_MASTER" 
   (	"QUIZ_ID" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"QUIZ_DATE" DATE NOT NULL ENABLE, 
	"QUIZ_START_DATE" DATE NOT NULL ENABLE, 
	"QUIZ_END_DATE" DATE NOT NULL ENABLE, 
	"EMP_SUBMIT_COUNT" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"EMP_COUNT" NUMBER(5,0) NOT NULL ENABLE, 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	 CONSTRAINT "HSE_QUIZ_MASTER_PK" PRIMARY KEY ("QUIZ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

