--------------------------------------------------------
--  DDL for Table LL_DOCUMENTS
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."LL_DOCUMENTS" 
   (	"ORGREQNUM" VARCHAR2(20 BYTE), 
	"DOCUMENT_NAME" VARCHAR2(255 BYTE), 
	"DOCUMENT_TYPE" VARCHAR2(20 BYTE), 
	"DOCUMENT" BLOB, 
	"STATUS" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" 
 LOB ("DOCUMENT") STORE AS BASICFILE (
  TABLESPACE "APPL_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
