--------------------------------------------------------
--  DDL for Table LL_RECORDED
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."LL_RECORDED" 
   (	"LLNUM" VARCHAR2(20 BYTE), 
	"LLDATE" DATE, 
	"LLCATEGORY" VARCHAR2(1 BYTE), 
	"LLAUTHOR" VARCHAR2(30 BYTE), 
	"LLCOAUTHOR" VARCHAR2(100 BYTE), 
	"LLDEPT" VARCHAR2(4 BYTE), 
	"LLSTATUS" VARCHAR2(1 BYTE), 
	"LLPROJECT" VARCHAR2(5 BYTE), 
	"LLCOUNTRY" VARCHAR2(25 BYTE), 
	"LLPLANT" VARCHAR2(40 BYTE), 
	"LLTECHNOLOGY" VARCHAR2(40 BYTE), 
	"LLFROM" VARCHAR2(4 BYTE), 
	"LLTO" VARCHAR2(4 BYTE), 
	"LLRPHASE" VARCHAR2(50 BYTE), 
	"LLPPHASE" VARCHAR2(50 BYTE), 
	"LLSUBJECT" VARCHAR2(1000 BYTE), 
	"LLACTIVITY" VARCHAR2(1100 BYTE), 
	"LLPACKAGE" VARCHAR2(1000 BYTE), 
	"LLEVENT" VARCHAR2(1000 BYTE), 
	"LLIMPACT" VARCHAR2(1000 BYTE), 
	"LLAPPLIED" VARCHAR2(1100 BYTE), 
	"LLSOLUTION" VARCHAR2(1000 BYTE), 
	"LLRECIPIENT" VARCHAR2(1000 BYTE), 
	"ORGREQNUM" VARCHAR2(20 BYTE), 
	"REVIEWACCEPTDATE" DATE, 
	"CLOSEDATE" DATE, 
	"LLPRJNAME" VARCHAR2(60 BYTE), 
	"PROPCATEGORY" VARCHAR2(100 BYTE), 
	"OWNDEPT" VARCHAR2(4 BYTE), 
	"HODSTATUS" NUMBER(1,0), 
	"KEYWORDDEPT" VARCHAR2(4 BYTE), 
	"HODSTATUSDATE" DATE, 
	"TEMPREF" VARCHAR2(20 BYTE), 
	"CHNGREQ" VARCHAR2(100 BYTE), 
	"CHNGDESC" VARCHAR2(200 BYTE), 
	"TRGTDATE" DATE, 
	"SUBJECTNEW" VARCHAR2(400 BYTE), 
	"LLARCHIVED" NUMBER(1,0) DEFAULT 0, 
	"LLNUM_FIN" VARCHAR2(20 BYTE), 
	"LLNUM_FIN_DATE" VARCHAR2(20 BYTE), 
	"TOSHAREPOINT" NUMBER(1,0) DEFAULT 0, 
	"TOSPDATE" DATE, 
	"COMPNAME" VARCHAR2(20 BYTE), 
	"OPENFLAG" NUMBER, 
	"OPENFLAG_DATE" DATE, 
	"HOD_CLOSEFLAG" NUMBER, 
	"HOD_CLOSEFLAG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."LL_RECORDED"."LLSTATUS" IS '"R" Recorded, "E" Evaluated, "C" Closed, "X" Terminated';
   COMMENT ON COLUMN "SELFSERVICE"."LL_RECORDED"."HODSTATUS" IS '"0" Default, "1" Accepted, "2" Teminated';
   COMMENT ON COLUMN "SELFSERVICE"."LL_RECORDED"."LLARCHIVED" IS '"1" Archived (Old)';
   COMMENT ON COLUMN "SELFSERVICE"."LL_RECORDED"."TOSHAREPOINT" IS '"1" Deployed on SP';
   COMMENT ON COLUMN "SELFSERVICE"."LL_RECORDED"."OPENFLAG" IS '"Null" Deafult, "0" Closed, "1" Open';
   COMMENT ON COLUMN "SELFSERVICE"."LL_RECORDED"."HOD_CLOSEFLAG" IS '"Null" Deafult, "0" Open, "1" Closed';
