--------------------------------------------------------
--  DDL for Table LL_RECORDED_20150123
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."LL_RECORDED_20150123" 
   (	"LLNUM" VARCHAR2(20 BYTE), 
	"LLDATE" DATE, 
	"LLCATEGORY" VARCHAR2(1 BYTE), 
	"LLAUTHOR" VARCHAR2(30 BYTE), 
	"LLCOAUTHOR" VARCHAR2(100 BYTE), 
	"LLDEPT" VARCHAR2(4 BYTE), 
	"LLSTATUS" VARCHAR2(1 BYTE), 
	"LLPROJECT" VARCHAR2(5 BYTE), 
	"LLCOUNTRY" VARCHAR2(25 BYTE), 
	"LLPLANT" VARCHAR2(40 BYTE), 
	"LLTECHNOLOGY" VARCHAR2(40 BYTE), 
	"LLFROM" VARCHAR2(4 BYTE), 
	"LLTO" VARCHAR2(4 BYTE), 
	"LLRPHASE" VARCHAR2(50 BYTE), 
	"LLPPHASE" VARCHAR2(50 BYTE), 
	"LLSUBJECT" VARCHAR2(400 BYTE), 
	"LLACTIVITY" VARCHAR2(400 BYTE), 
	"LLPACKAGE" VARCHAR2(400 BYTE), 
	"LLEVENT" VARCHAR2(400 BYTE), 
	"LLIMPACT" VARCHAR2(400 BYTE), 
	"LLAPPLIED" VARCHAR2(400 BYTE), 
	"LLSOLUTION" VARCHAR2(400 BYTE), 
	"LLRECIPIENT" VARCHAR2(400 BYTE), 
	"ORGREQNUM" VARCHAR2(20 BYTE), 
	"REVIEWACCEPTDATE" DATE, 
	"CLOSEDATE" DATE, 
	"LLPRJNAME" VARCHAR2(60 BYTE), 
	"PROPCATEGORY" VARCHAR2(100 BYTE), 
	"OWNDEPT" VARCHAR2(4 BYTE), 
	"HODSTATUS" NUMBER(1,0), 
	"KEYWORDDEPT" VARCHAR2(4 BYTE), 
	"HODSTATUSDATE" DATE, 
	"TEMPREF" VARCHAR2(20 BYTE), 
	"CHNGREQ" VARCHAR2(30 BYTE), 
	"CHNGDESC" VARCHAR2(200 BYTE), 
	"TRGTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
