--------------------------------------------------------
--  DDL for Table PRINT_LOG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."PRINT_LOG" 
   (	"USER_NAME" VARCHAR2(30 BYTE), 
	"COLOR" VARCHAR2(130 BYTE), 
	"PRINT_DATE" DATE, 
	"PERIOD" VARCHAR2(12 BYTE), 
	"PAGECOUNT" NUMBER, 
	"EMPNO" VARCHAR2(5 BYTE), 
	"EMP_NAME" VARCHAR2(35 BYTE), 
	"PARENT" CHAR(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
