--------------------------------------------------------
--  DDL for Table SS_9794_PUNCH_REQUIRED_1
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_9794_PUNCH_REQUIRED_1" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(35 BYTE), 
	"PARENT" CHAR(4 BYTE), 
	"YYYYMM" VARCHAR2(6 BYTE), 
	"TS_DATE" DATE, 
	"TS_DATE_CHR" VARCHAR2(8 BYTE), 
	"TIME_SHEET_HRS" NUMBER(5,0), 
	"SS_PUNCH_1" VARCHAR2(15 BYTE), 
	"SS_PUNCH_LAST" VARCHAR2(15 BYTE), 
	"SS_WRK_HRS" VARCHAR2(4000 BYTE), 
	"FIRST_PUNCH_BT" VARCHAR2(4000 BYTE), 
	"LAST_PUNCH_BT" VARCHAR2(4000 BYTE), 
	"WRK_HRS_BT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
