--------------------------------------------------------
--  DDL for Table SS_9794_TS_SS_MAY_JUN
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_9794_TS_SS_MAY_JUN" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"YYYYMM" VARCHAR2(6 BYTE), 
	"TS_DATE" DATE, 
	"PROJNO" VARCHAR2(7 BYTE), 
	"WORK_HOURS" NUMBER(5,0), 
	"FIRST_PUNCH" VARCHAR2(15 BYTE), 
	"LAST_PUNCH" VARCHAR2(15 BYTE), 
	"FIRST_PUNCH_SEC" NUMBER, 
	"LAST_PUNCH_SEC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
