--------------------------------------------------------
--  DDL for Table SS_9794_PUNCH_FIRST_LAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_9794_PUNCH_FIRST_LAST" 
   (	"EMPNO" CHAR(5 BYTE), 
	"YYYY" CHAR(4 BYTE), 
	"MON" CHAR(2 BYTE), 
	"DD" CHAR(2 BYTE), 
	"P_DATE" DATE, 
	"FIRST_PUNCH" NUMBER, 
	"LAST_PUNCH" NUMBER, 
	"FIRST_PUNCH_C" VARCHAR2(4000 BYTE), 
	"LAST_PUNCH_C" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
