--------------------------------------------------------
--  DDL for Table SS_9794_TS_PERIOD
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_9794_TS_PERIOD" 
   (	"PERIOD" VARCHAR2(6 BYTE), 
	"IS_OPEN" VARCHAR2(2 BYTE), 
	"MODIFIED_ON" DATE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
