--------------------------------------------------------
--  DDL for Table SS_9794_PUNCH_GENERATE
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_9794_PUNCH_GENERATE" 
   (	"FOR_EMP" VARCHAR2(5 BYTE), 
	"FOR_DATE" DATE, 
	"SRC_EMP" VARCHAR2(5 BYTE), 
	"SRC_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
