--------------------------------------------------------
--  DDL for Table SS_ABSENT_DETAIL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_ABSENT_DETAIL" 
   (	"KEY_ID" VARCHAR2(8 BYTE), 
	"ABSENT_YYYYMM" VARCHAR2(6 BYTE), 
	"PAYSLIP_YYYYMM" VARCHAR2(6 BYTE), 
	"EMPNO" VARCHAR2(5 BYTE), 
	"ABSENT_DAYS" VARCHAR2(120 BYTE), 
	"CL_BAL" VARCHAR2(15 BYTE), 
	"SL_BAL" VARCHAR2(15 BYTE), 
	"PL_BAL" VARCHAR2(15 BYTE), 
	"CO_BAL" VARCHAR2(15 BYTE), 
	"NO_MAIL" VARCHAR2(2 BYTE), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
