--------------------------------------------------------
--  DDL for Table SS_BATCH_LOG_DETAILS
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_BATCH_LOG_DETAILS" 
   (	"BATCH_KEY_ID" VARCHAR2(8 BYTE), 
	"ITEM_REF" VARCHAR2(10 BYTE), 
	"LOG_DESC" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
