--------------------------------------------------------
--  DDL for Table SS_BATCH_ERROR_MAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_BATCH_ERROR_MAST" 
   (	"ERR_CODE" VARCHAR2(5 BYTE), 
	"ERR_DESC" VARCHAR2(100 BYTE), 
	"REF_PROG" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
