--------------------------------------------------------
--  DDL for Table SS_CLINIC_LIMIT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_CLINIC_LIMIT" 
   (	"CLINIC" CHAR(2 BYTE), 
	"APPLIMIT" NUMBER(2,0) DEFAULT 0, 
	"FORDEPUTATION" NUMBER(1,0) DEFAULT 0, 
	"APPDATE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
