--------------------------------------------------------
--  DDL for Table SS_DAYS_DETAILS_1
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_DAYS_DETAILS_1" 
   (	"D_DATE" DATE, 
	"D_DD" CHAR(2 BYTE), 
	"D_MM" CHAR(2 BYTE), 
	"D_YYYY" CHAR(4 BYTE), 
	"D_MON" CHAR(3 BYTE), 
	"D_DAY" CHAR(3 BYTE), 
	"WK_OF_YEAR" CHAR(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
