--------------------------------------------------------
--  DDL for Table SS_DESKASSIGNMENT_20091126
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_DESKASSIGNMENT_20091126" 
   (	"EMPNO" CHAR(5 BYTE), 
	"LOGINID" VARCHAR2(20 BYTE), 
	"OFFLOC" CHAR(2 BYTE), 
	"DESKID" CHAR(7 BYTE), 
	"TFORCE" CHAR(2 BYTE), 
	"SHFT" CHAR(1 BYTE), 
	"COMPNAME" VARCHAR2(20 BYTE), 
	"PCCODE" VARCHAR2(20 BYTE), 
	"PCMOD" CHAR(2 BYTE), 
	"M1CODE" VARCHAR2(20 BYTE), 
	"M1MOD" CHAR(2 BYTE), 
	"M2CODE" VARCHAR2(20 BYTE), 
	"M2MOD" CHAR(2 BYTE), 
	"TELNO" VARCHAR2(10 BYTE), 
	"TELCODE" VARCHAR2(20 BYTE), 
	"TMOD" CHAR(2 BYTE), 
	"UPDATE_FLAG" NUMBER(38,0), 
	"DESKID_OLD" CHAR(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
