--------------------------------------------------------
--  DDL for Table SS_DMS_STATUS2021
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_DMS_STATUS2021" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"ASSET_TYPE" VARCHAR2(20 BYTE), 
	"DMS_ASSETID" VARCHAR2(13 BYTE), 
	"ISMATCH" VARCHAR2(1 BYTE), 
	"CURR_ASSETID" VARCHAR2(13 BYTE), 
	"REMARK" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
