--------------------------------------------------------
--  DDL for Table SS_DELTAHRSBAL_OT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_DELTAHRSBAL_OT" 
   (	"EMPNO" CHAR(5 BYTE), 
	"MON" CHAR(2 BYTE), 
	"YYYY" CHAR(4 BYTE), 
	"DELTAHRS" NUMBER(7,0), 
	"LDAY_CFWD_DHRS" NUMBER(7,0), 
	"LC_APPCNTR" NUMBER(3,0), 
	"PDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
