--------------------------------------------------------
--  DDL for Table SS_DELTAHRSBAL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_DELTAHRSBAL" 
   (	"EMPNO" CHAR(5 BYTE), 
	"PDATE" DATE, 
	"MM" NUMBER(7,0), 
	"LC_APPCNTR" NUMBER(3,0), 
	"OT_MM" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
