--------------------------------------------------------
--  DDL for Table SS_DEPU
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_DEPU" 
   (	"EMPNO" CHAR(5 BYTE), 
	"APP_NO" VARCHAR2(60 BYTE), 
	"BDATE" DATE, 
	"EDATE" DATE, 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"TYPE" CHAR(2 BYTE), 
	"HOD_APPRL" NUMBER(1,0), 
	"HOD_APPRL_DT" DATE, 
	"HOD_CODE" CHAR(5 BYTE), 
	"HRD_APPRL" NUMBER(1,0), 
	"HRD_APPRL_DT" DATE, 
	"HRD_CODE" CHAR(5 BYTE), 
	"APP_DATE" DATE, 
	"REASON" VARCHAR2(60 BYTE), 
	"USER_TCP_IP" VARCHAR2(30 BYTE), 
	"HOD_TCP_IP" VARCHAR2(30 BYTE), 
	"HRD_TCP_IP" VARCHAR2(30 BYTE), 
	"HODREASON" VARCHAR2(60 BYTE), 
	"HRDREASON" VARCHAR2(60 BYTE), 
	"CHG_NO" NUMBER(3,0), 
	"CHG_DATE" DATE, 
	"LEAD_APPRL" NUMBER(1,0), 
	"LEAD_APPRL_DT" DATE, 
	"LEAD_CODE" VARCHAR2(5 BYTE), 
	"LEAD_TCP_IP" VARCHAR2(30 BYTE), 
	"LEAD_REASON" VARCHAR2(60 BYTE), 
	"LEAD_APPRL_EMPNO" VARCHAR2(5 BYTE), 
	"CHG_BY" VARCHAR2(5 BYTE), 
	"SITE_CODE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
