--------------------------------------------------------
--  DDL for Table SS_DMS_STATUS2020
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_DMS_STATUS2020" 
   (	"EMPNO" CHAR(5 BYTE), 
	"PC" VARCHAR2(13 BYTE), 
	"MON1" VARCHAR2(13 BYTE), 
	"MON2" VARCHAR2(13 BYTE), 
	"PRNT" VARCHAR2(13 BYTE), 
	"REMARKS" VARCHAR2(200 BYTE), 
	"MODDATE" DATE, 
	"MODUSER" CHAR(5 BYTE), 
	"DOCSTN" VARCHAR2(13 BYTE), 
	"PCFLAG" CHAR(1 BYTE), 
	"PCMOD" VARCHAR2(60 BYTE), 
	"MONFLAG1" CHAR(1 BYTE), 
	"MONMOD1" VARCHAR2(60 BYTE), 
	"MONFLAG2" CHAR(1 BYTE), 
	"MONMOD2" VARCHAR2(60 BYTE), 
	"PRNTFLAG" CHAR(1 BYTE), 
	"PRNTMOD" VARCHAR2(60 BYTE), 
	"DOCSTNFLAG" CHAR(1 BYTE), 
	"DOCSTNMOD" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
