--------------------------------------------------------
--  DDL for Table SS_EMP_COMP_LASTDATE_4_MUSTER
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_EMP_COMP_LASTDATE_4_MUSTER" 
   (	"EMPNO" CHAR(5 BYTE), 
	"COMPANY" CHAR(4 BYTE), 
	"LASTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
