--------------------------------------------------------
--  DDL for Table SS_FEEDBACK
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_FEEDBACK" 
   (	"EMPNO" CHAR(5 BYTE), 
	"ENTITY" CHAR(4 BYTE), 
	"OVERALL" NUMBER(1,0), 
	"ARRANGEMENT" NUMBER(1,0), 
	"PRESENTATION" NUMBER(1,0), 
	"CONTENT" NUMBER(1,0), 
	"DURATION" NUMBER(1,0), 
	"INTERESTING" NUMBER(1,0), 
	"TECHNICAL" NUMBER(1,0), 
	"AUDIBILITY" NUMBER(1,0), 
	"VISIBILITY" NUMBER(1,0), 
	"VIEWALL" NUMBER(1,0), 
	"SUGGEST" VARCHAR2(200 BYTE), 
	"TRANSLATOR" NUMBER(1,0), 
	"UNDERSTAND" NUMBER(1,0), 
	"INFORMATIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
