--------------------------------------------------------
--  DDL for Table SS_FIM_DATA
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_FIM_DATA" 
   (	"EMPNO" CHAR(5 BYTE), 
	"EMP_NAME" VARCHAR2(100 BYTE), 
	"META_ID" VARCHAR2(20 BYTE), 
	"DOMAIN" VARCHAR2(20 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(20 BYTE), 
	"EMAIL_ID" VARCHAR2(100 BYTE), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
