--------------------------------------------------------
--  DDL for Table SS_GENERAL_CODES
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_GENERAL_CODES" 
   (	"CATG" CHAR(4 BYTE), 
	"PURPOSE" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"DESCRIPTION" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"CODE1" CHAR(1 BYTE) DEFAULT NULL, 
	"CODE2" CHAR(2 BYTE) DEFAULT NULL, 
	"CODE3" CHAR(3 BYTE) DEFAULT NULL, 
	"CODE4" CHAR(4 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."SS_GENERAL_CODES"."CATG" IS 'Use this field in where clause only (Group codes)';
   COMMENT ON COLUMN "SELFSERVICE"."SS_GENERAL_CODES"."PURPOSE" IS 'This field gives info of a Category';
   COMMENT ON COLUMN "SELFSERVICE"."SS_GENERAL_CODES"."CODE1" IS 'Code belonging to Category';
   COMMENT ON COLUMN "SELFSERVICE"."SS_GENERAL_CODES"."CODE2" IS 'Code belonging to Category';
   COMMENT ON COLUMN "SELFSERVICE"."SS_GENERAL_CODES"."CODE3" IS 'Code belonging to Category';
   COMMENT ON COLUMN "SELFSERVICE"."SS_GENERAL_CODES"."CODE4" IS 'Code belonging to Category';
