--------------------------------------------------------
--  DDL for Table SS_HOLIDAY_ATTENDANCE
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_HOLIDAY_ATTENDANCE" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"PROJNO" VARCHAR2(7 BYTE), 
	"PDATE" DATE, 
	"START_HH" NUMBER(2,0), 
	"START_MM" NUMBER(2,0), 
	"END_HH" NUMBER(2,0), 
	"END_MM" NUMBER(2,0), 
	"REMARKS" VARCHAR2(60 BYTE), 
	"LOCATION" VARCHAR2(10 BYTE), 
	"LEAD_APPRL" NUMBER(1,0), 
	"LEAD_CODE" VARCHAR2(5 BYTE), 
	"LEAD_APPRL_DATE" DATE, 
	"LEAD_TCP_IP" VARCHAR2(30 BYTE), 
	"LEAD_APPRL_EMPNO" VARCHAR2(5 BYTE), 
	"HOD_APPRL" NUMBER(1,0), 
	"HOD_CODE" VARCHAR2(5 BYTE), 
	"HOD_APPRL_DATE" DATE, 
	"HOD_TCP_IP" VARCHAR2(30 BYTE), 
	"HRD_APPRL" NUMBER(1,0), 
	"HRD_CODE" VARCHAR2(5 BYTE), 
	"HRD_APPRL_DATE" DATE, 
	"HRD_TCP_IP" VARCHAR2(30 BYTE), 
	"APP_NO" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(80 BYTE), 
	"APP_DATE" DATE, 
	"USER_TCP_IP" VARCHAR2(30 BYTE), 
	"HODREASON" VARCHAR2(60 BYTE), 
	"HRDREASON" VARCHAR2(60 BYTE), 
	"LEAD_REASON" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
