--------------------------------------------------------
--  DDL for Table SS_HSESUGG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_HSESUGG" 
   (	"SUGGNO" CHAR(9 BYTE), 
	"SUGGDATE" DATE, 
	"COSTCODE" CHAR(4 BYTE), 
	"IMP" NUMBER(1,0), 
	"DEV" NUMBER(1,0), 
	"ELM" NUMBER(1,0), 
	"SUGG" VARCHAR2(400 BYTE), 
	"BENEFIT" VARCHAR2(400 BYTE), 
	"SAFETY" VARCHAR2(400 BYTE), 
	"HODACCEPT" NUMBER(1,0), 
	"HODCODE" CHAR(5 BYTE), 
	"HODDATE" DATE, 
	"REFNO" VARCHAR2(15 BYTE), 
	"CLOSED" NUMBER(1,0), 
	"CLOSEDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
