--------------------------------------------------------
--  DDL for Table SS_HEALTH_EMP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_HEALTH_EMP" 
   (	"APPLNO" CHAR(20 BYTE), 
	"APPL_DT" DATE, 
	"EMPNO" CHAR(5 BYTE), 
	"COSTCODE" CHAR(4 BYTE), 
	"DESGCODE" CHAR(6 BYTE), 
	"GRADE" CHAR(2 BYTE), 
	"DEP" NUMBER(1,0), 
	"DEP_DT" DATE, 
	"CLINIC" CHAR(2 BYTE), 
	"LOCATION" VARCHAR2(25 BYTE), 
	"APP_DT" DATE, 
	"ALT_DT" DATE, 
	"YYYY" CHAR(4 BYTE), 
	"OFFICELOC" VARCHAR2(2 BYTE), 
	"MOBILENO" VARCHAR2(10 BYTE), 
	"ATTND" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."SS_HEALTH_EMP"."ATTND" IS '0 - ToAttend, 1 - Attened, 2 - Not Attended';
