--------------------------------------------------------
--  DDL for Table SS_HSE_QUIZ
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_HSE_QUIZ" 
   (	"EMPNO" CHAR(5 BYTE), 
	"IMPROVE" VARCHAR2(30 BYTE), 
	"ISO_VER" VARCHAR2(30 BYTE), 
	"HSE_PROC" VARCHAR2(30 BYTE), 
	"HSE_DOC" VARCHAR2(30 BYTE), 
	"HSE_PROJPLAN" VARCHAR2(30 BYTE), 
	"EMERGENCY" VARCHAR2(40 BYTE), 
	"EMERGENCYPHONE" VARCHAR2(30 BYTE), 
	"FLAG_WHERE" NUMBER(1,0), 
	"FLAG_ADD" NUMBER(1,0), 
	"FLAG_ENVIR" NUMBER(1,0), 
	"FLAG_HELT_HAZ" NUMBER(1,0), 
	"FLAG_HSE_REQ" NUMBER(1,0), 
	"FLAG_HSE_OBJ" NUMBER(1,0), 
	"FLAG_INCIDENTS" NUMBER(1,0), 
	"FLAG_AUDITS" NUMBER(1,0), 
	"SEND_TO_HSE" NUMBER(1,0), 
	"APPROVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
