--------------------------------------------------------
--  DDL for Table SS_HALFDAYMAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_HALFDAYMAST" 
   (	"SHIFTCODE" CHAR(2 BYTE), 
	"PARENT" CHAR(4 BYTE), 
	"HDAY1_STARTHH" NUMBER(2,0), 
	"HDAY1_STARTMM" NUMBER(2,0), 
	"HDAY1_ENDHH" NUMBER(2,0), 
	"HDAY1_ENDMM" NUMBER(2,0), 
	"HDAY2_STARTHH" NUMBER(2,0), 
	"HDAY2_STARTMM" NUMBER(2,0), 
	"HDAY2_ENDHH" NUMBER(2,0), 
	"HDAY2_ENDMM" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
