--------------------------------------------------------
--  DDL for Table SS_HSE_INCIDENTREPORT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_HSE_INCIDENTREPORT" 
   (	"REPORTID" VARCHAR2(16 BYTE), 
	"REPORTDATE" DATE, 
	"YYYY" VARCHAR2(7 BYTE), 
	"OFFICE" CHAR(2 BYTE), 
	"LOC" VARCHAR2(50 BYTE), 
	"COSTCODE" CHAR(4 BYTE), 
	"INCDATE" DATE, 
	"INCTIME" VARCHAR2(6 BYTE), 
	"INCTYPE" CHAR(1 BYTE), 
	"NATURE" CHAR(1 BYTE), 
	"B_HEAD" NUMBER(1,0) DEFAULT 0, 
	"B_NECK" NUMBER(1,0) DEFAULT 0, 
	"B_FOREARM" NUMBER(1,0) DEFAULT 0, 
	"B_LEGS" NUMBER(1,0) DEFAULT 0, 
	"B_FACE" NUMBER(1,0) DEFAULT 0, 
	"B_SHOULDER" NUMBER(1,0) DEFAULT 0, 
	"B_ELBOW" NUMBER(1,0) DEFAULT 0, 
	"B_KNEE" NUMBER(1,0) DEFAULT 0, 
	"B_MOUTH" NUMBER(1,0) DEFAULT 0, 
	"B_CHEST" NUMBER(1,0) DEFAULT 0, 
	"B_WRIST" NUMBER(1,0) DEFAULT 0, 
	"B_ANKLE" NUMBER(1,0) DEFAULT 0, 
	"B_EAR" NUMBER(1,0) DEFAULT 0, 
	"B_ABDOMEN" NUMBER(1,0) DEFAULT 0, 
	"B_HIP" NUMBER(1,0) DEFAULT 0, 
	"B_FOOT" NUMBER(1,0) DEFAULT 0, 
	"B_EYE" NUMBER(1,0) DEFAULT 0, 
	"B_BACK" NUMBER(1,0) DEFAULT 0, 
	"B_THIGH" NUMBER(1,0) DEFAULT 0, 
	"B_OTHER" NUMBER(1,0) DEFAULT 0, 
	"EMPNO" CHAR(5 BYTE), 
	"EMPNAME" VARCHAR2(50 BYTE), 
	"DESG" VARCHAR2(50 BYTE), 
	"AGE" VARCHAR2(2 BYTE), 
	"SEX" CHAR(1 BYTE), 
	"SUBCONTRACT" CHAR(1 BYTE) DEFAULT 0, 
	"SUBCONTRACTNAME" VARCHAR2(50 BYTE), 
	"AID" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(300 BYTE), 
	"CAUSES" VARCHAR2(200 BYTE), 
	"ACTION" VARCHAR2(200 BYTE), 
	"MAILSEND" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
