--------------------------------------------------------
--  DDL for Table SS_LEAVE_BAL_MAX_LIMIT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LEAVE_BAL_MAX_LIMIT" 
   (	"YYYYMM" VARCHAR2(6 BYTE), 
	"MAX_LEAVE_BAL" NUMBER(4,0), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
