--------------------------------------------------------
--  DDL for Table SS_LUNCHMAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LUNCHMAST" 
   (	"SHIFTCODE" CHAR(2 BYTE), 
	"PARENT" CHAR(4 BYTE), 
	"STARTHH" NUMBER(2,0), 
	"STARTMN" NUMBER(2,0), 
	"ENDHH" NUMBER(2,0), 
	"ENDMN" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
