--------------------------------------------------------
--  DDL for Table SS_LEAVE_UPLOAD_LOG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG" 
   (	"FILENAME" CHAR(60 BYTE), 
	"FILE_UP_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"KEY" CHAR(60 BYTE), 
	"ISDELETED" NUMBER(1,0) DEFAULT 0, 
	"DEL_DATE" DATE, 
	"LEDG_DATE" DATE, 
	"DEL_REASON" VARCHAR2(100 BYTE), 
	"ISERR" NUMBER(1,0), 
	"ERR_DESC" VARCHAR2(500 BYTE), 
	"CLIENT_FILE_NAME" VARCHAR2(60 BYTE), 
	"ADJ_TYPE" CHAR(2 BYTE), 
	"DB_CR" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."FILENAME" IS 'Name of the file Uploaded';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."FILE_UP_DATE" IS 'Date of File Upload';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."DESCRIPTION" IS 'Narration to appear in the SS_LeaveLedg';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."KEY" IS 'Used to identify entries in SS_LeaveLedg table and also to rollback all entries';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."ISDELETED" IS 'Flag to identify the rollback of Upload';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."DEL_DATE" IS 'Date of rollback of upload';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."LEDG_DATE" IS 'Date on which leave shall be Dr/Cr in Leave Ledg';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."DEL_REASON" IS 'Reason for deleting the file.';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."ISERR" IS 'Was there an error while uploading the file';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."ERR_DESC" IS 'Description Of the Error';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_LOG"."CLIENT_FILE_NAME" IS 'Name of the file on clients machine';
