--------------------------------------------------------
--  DDL for Table SS_LEAVE_ADJ
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LEAVE_ADJ" 
   (	"EMPNO" CHAR(5 BYTE), 
	"ADJ_DT" DATE, 
	"ADJ_NO" VARCHAR2(60 BYTE), 
	"LEAVETYPE" CHAR(2 BYTE), 
	"DATAENTRYBY" CHAR(5 BYTE), 
	"DB_CR" CHAR(1 BYTE), 
	"ADJ_TYPE" CHAR(2 BYTE), 
	"BDATE" DATE, 
	"EDATE" DATE, 
	"LEAVEPERIOD" NUMBER(5,1), 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"TCP_IP" VARCHAR2(30 BYTE), 
	"HD_DATE" DATE, 
	"HD_PART" NUMBER(1,0), 
	"ENTRY_DATE" DATE, 
	"MED_CERT_FILE_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
