--------------------------------------------------------
--  DDL for Table SS_LEAVEBAL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LEAVEBAL" 
   (	"EMPNO" CHAR(5 BYTE), 
	"BALDATE" DATE, 
	"SL_BAL" NUMBER(7,1), 
	"PL_BAL" NUMBER(7,1), 
	"CL_BAL" NUMBER(7,1), 
	"EX_BAL" NUMBER(7,1), 
	"CO_BAL" NUMBER(7,1), 
	"OH_BAL" NUMBER(7,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
