--------------------------------------------------------
--  DDL for Table SS_LEAVELEDG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LEAVELEDG" 
   (	"APP_NO" VARCHAR2(60 BYTE), 
	"APP_DATE" DATE, 
	"LEAVETYPE" CHAR(2 BYTE), 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"EMPNO" CHAR(5 BYTE), 
	"LEAVEPERIOD" NUMBER(8,1), 
	"DB_CR" CHAR(1 BYTE), 
	"TABLETAG" NUMBER(2,0), 
	"BDATE" DATE, 
	"EDATE" DATE, 
	"ADJ_TYPE" VARCHAR2(2 BYTE), 
	"HD_DATE" DATE, 
	"HD_PART" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
