--------------------------------------------------------
--  DDL for Table SS_LEAD_APPROVER
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LEAD_APPROVER" 
   (	"PARENT" CHAR(4 BYTE), 
	"EMPNO" CHAR(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT UPDATE ON "SELFSERVICE"."SS_LEAD_APPROVER" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SS_LEAD_APPROVER" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SS_LEAD_APPROVER" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SS_LEAD_APPROVER" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SS_LEAD_APPROVER" TO "REMOTEWORKING";
