--------------------------------------------------------
--  DDL for Table SS_LEAVE_UPLOAD_TEMP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP" 
   (	"EMPNO" CHAR(5 BYTE), 
	"LEAVETYPE" CHAR(2 BYTE), 
	"LEAVEPERIOD" NUMBER(11,3), 
	"DR_CR" CHAR(1 BYTE), 
	"KEY" CHAR(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP"."EMPNO" IS 'Employee Number';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP"."LEAVETYPE" IS 'Leave Type (CL,SL,PL, etc)';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP"."LEAVEPERIOD" IS 'Period of leave in Hours';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP"."DR_CR" IS 'Specify if the leave is to be debited / credited in Leave Ledg';
   COMMENT ON COLUMN "SELFSERVICE"."SS_LEAVE_UPLOAD_TEMP"."KEY" IS 'Used to track deltails back in Log table and also to bulk rollback';
