--------------------------------------------------------
--  DDL for Table SS_MUSTER_4ALLOWANCE_20101006
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_MUSTER_4ALLOWANCE_20101006" 
   (	"EMPNO" CHAR(5 BYTE), 
	"MNTH" CHAR(6 BYTE), 
	"SHIFT" CHAR(62 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
