--------------------------------------------------------
--  DDL for Table SS_MONTHLY_CREDIT_EXCEPTION
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_MONTHLY_CREDIT_EXCEPTION" 
   (	"FROM_DATE" DATE, 
	"EMPNO" CHAR(5 BYTE), 
	"LEAVE_PERIOD" NUMBER(5,2), 
	"MODIFIED_ON" DATE, 
	"KEY_ID" CHAR(8 BYTE), 
	"XL_ROW_NR" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
