--------------------------------------------------------
--  DDL for Table SS_ONDUTYAPP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_ONDUTYAPP" 
   (	"EMPNO" CHAR(5 BYTE), 
	"HH" NUMBER(2,0), 
	"MM" NUMBER(2,0), 
	"PDATE" DATE, 
	"DD" CHAR(2 BYTE), 
	"MON" CHAR(2 BYTE), 
	"YYYY" CHAR(4 BYTE), 
	"TYPE" CHAR(2 BYTE), 
	"APP_NO" VARCHAR2(60 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"HOD_APPRL" NUMBER(1,0), 
	"HOD_APPRL_DT" DATE, 
	"HOD_CODE" CHAR(5 BYTE), 
	"HRD_APPRL" NUMBER(1,0), 
	"HRD_APPRL_DT" DATE, 
	"HRD_CODE" CHAR(5 BYTE), 
	"APP_DATE" DATE, 
	"HH1" NUMBER(2,0), 
	"MM1" NUMBER(2,0), 
	"REASON" VARCHAR2(60 BYTE), 
	"USER_TCP_IP" VARCHAR2(30 BYTE), 
	"HOD_TCP_IP" VARCHAR2(30 BYTE), 
	"HRD_TCP_IP" VARCHAR2(30 BYTE), 
	"HODREASON" VARCHAR2(60 BYTE), 
	"HRDREASON" VARCHAR2(60 BYTE), 
	"ODTYPE" NUMBER(1,0), 
	"LEAD_APPRL" NUMBER(1,0), 
	"LEAD_CODE" VARCHAR2(5 BYTE), 
	"LEAD_APPRL_DT" DATE, 
	"LEAD_TCP_IP" VARCHAR2(30 BYTE), 
	"LEAD_REASON" VARCHAR2(60 BYTE), 
	"LEAD_APPRL_EMPNO" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
