--------------------------------------------------------
--  DDL for Table SS_OTAPPRL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_OTAPPRL" 
   (	"EMPNO" CHAR(5 BYTE), 
	"MNTH" CHAR(6 BYTE), 
	"HOD_APPRL" NUMBER(1,0), 
	"HRD_APPRL" NUMBER(1,0), 
	"HOD_CODE" CHAR(5 BYTE), 
	"HOD_TCP_IP" VARCHAR2(30 BYTE), 
	"HOD_APPRL_DT" DATE, 
	"HODREASON" VARCHAR2(60 BYTE), 
	"HRD_CODE" CHAR(5 BYTE), 
	"HRD_TCP_IP" VARCHAR2(30 BYTE), 
	"HRD_APPRL_DT" DATE, 
	"HRDREASON" VARCHAR2(60 BYTE), 
	"TOTAL_OT" NUMBER(8,0), 
	"APPROVED_OT" NUMBER(8,0), 
	"APPL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
