--------------------------------------------------------
--  DDL for Table SS_OTMASTER
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_OTMASTER" 
   (	"EMPNO" CHAR(5 BYTE), 
	"MON" CHAR(2 BYTE), 
	"YYYY" CHAR(4 BYTE), 
	"MONTH" CHAR(3 BYTE), 
	"OT" NUMBER(10,0), 
	"CO" NUMBER(10,0), 
	"APP_DATE" DATE, 
	"USER_TCP_IP" VARCHAR2(50 BYTE), 
	"HOD_APPRL" NUMBER(1,0), 
	"HOD_CODE" CHAR(5 BYTE), 
	"HOD_TCP_IP" VARCHAR2(30 BYTE), 
	"HOD_APPRL_DT" DATE, 
	"HOD_REMARKS" VARCHAR2(100 BYTE), 
	"HRD_APPRL" NUMBER(1,0), 
	"HRD_CODE" CHAR(5 BYTE), 
	"HRD_TCP_IP" VARCHAR2(30 BYTE), 
	"HRD_APPRL_DT" DATE, 
	"HRD_REMARKS" VARCHAR2(100 BYTE), 
	"APP_NO" VARCHAR2(50 BYTE), 
	"HOD_APPRD_OT" NUMBER(10,0), 
	"HOD_APPRD_CO" NUMBER(10,0), 
	"HRD_APPRD_OT" NUMBER(10,0), 
	"HRD_APPRD_CO" NUMBER(10,0), 
	"HRD_SUNDAY_OT" NUMBER(10,0), 
	"HRD_ADJUSTMENT_OT" NUMBER(10,0), 
	"HOD_APPRD_HHOT" NUMBER(10,0), 
	"HRD_APPRD_HHOT" NUMBER(10,0), 
	"HHOT" NUMBER(10,0), 
	"HRD_ADJUSTMENT_HHOT" NUMBER(2,0) DEFAULT 0, 
	"LEAD_APPRL_EMPNO" CHAR(5 BYTE), 
	"LEAD_APPRL" NUMBER(1,0), 
	"LEAD_APPRL_DT" DATE, 
	"LEAD_APPRD_CO" NUMBER(10,0), 
	"LEAD_APPRD_OT" NUMBER(10,0), 
	"LEAD_APPRD_HHOT" NUMBER(10,0), 
	"LEAD_REMARKS" VARCHAR2(60 BYTE), 
	"LEAD_CODE" CHAR(5 BYTE), 
	"LEAD_TCP_IP" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
