--------------------------------------------------------
--  DDL for Table SS_OT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_OT" 
   (	"EMPNO" CHAR(5 BYTE), 
	"HH" NUMBER, 
	"MM" NUMBER, 
	"PDATE" DATE, 
	"DD" CHAR(2 BYTE), 
	"MON" CHAR(2 BYTE), 
	"YYYY" CHAR(4 BYTE), 
	"HHSORT" NUMBER, 
	"MMSORT" NUMBER, 
	"FROMTAB" NUMBER, 
	"OT" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
