--------------------------------------------------------
--  DDL for Table SS_OT_DETAILS_4_YEAR
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_OT_DETAILS_4_YEAR" 
   (	"EMPNO" CHAR(5 BYTE), 
	"NAME" VARCHAR2(35 BYTE), 
	"PARENT" CHAR(4 BYTE), 
	"DELTA_HOURS" NUMBER, 
	"PENALTYHRS" NUMBER, 
	"D_DATE" DATE, 
	"SHIFTCODE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
