--------------------------------------------------------
--  DDL for Table SS_OTDETAIL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_OTDETAIL" 
   (	"EMPNO" CHAR(5 BYTE), 
	"MON" CHAR(2 BYTE), 
	"YYYY" CHAR(4 BYTE), 
	"DAY" NUMBER(2,0), 
	"D_DETAILS" VARCHAR2(1000 BYTE), 
	"W_OT_MAX" NUMBER(8,0), 
	"W_CO" NUMBER(8,0), 
	"W_OT_CLAIM" NUMBER(8,0), 
	"W_DETAILS" VARCHAR2(500 BYTE), 
	"OF_MON" CHAR(2 BYTE), 
	"APP_NO" VARCHAR2(50 BYTE), 
	"CO_BOOL" NUMBER(1,0), 
	"WK_OF_YEAR" CHAR(2 BYTE), 
	"HOD_APPRD_OT" NUMBER(8,0), 
	"HOD_APPRD_CO" NUMBER(8,0), 
	"HOD_CO_BOOL" NUMBER(1,0), 
	"HOD_OT_MAX" NUMBER(8,0), 
	"DAY_YYYY" CHAR(4 BYTE), 
	"W_HHOT_CLAIM" NUMBER(10,0), 
	"W_HHOT_MAX" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
