--------------------------------------------------------
--  DDL for Table SS_PUNCH_BAL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_PUNCH_BAL" 
   (	"EMPNO" CHAR(5 BYTE), 
	"PDATE" DATE, 
	"MON" CHAR(2 BYTE), 
	"YYYY" CHAR(4 BYTE), 
	"DELTAHRS" NUMBER(6,0), 
	"SLV_APP_NOS" NUMBER(2,0), 
	"PEN_LV_HRS" NUMBER(4,0), 
	"WRK_HRS" NUMBER(7,2), 
	"LV_HRS" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
