--------------------------------------------------------
--  DDL for Table SS_PUNCH_UPLOAD_BLOB
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_PUNCH_UPLOAD_BLOB" 
   (	"KEY_ID" VARCHAR2(5 BYTE), 
	"MODIFIED_ON" DATE, 
	"FILE_BLOB" BLOB, 
	"FILE_TYPE" VARCHAR2(20 BYTE), 
	"PROCESS_STATUS" VARCHAR2(2 BYTE), 
	"FILE_NAME" VARCHAR2(200 BYTE), 
	"PROCESS_MESSAGE" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" 
 LOB ("FILE_BLOB") STORE AS BASICFILE (
  TABLESPACE "APPL_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SELFSERVICE"."SS_PUNCH_UPLOAD_BLOB"."PROCESS_STATUS" IS 'UP-Uploaded; WP-Work Progress; OK - Success; KO - Failure';
