--------------------------------------------------------
--  DDL for Table SS_PHONE_CALL_LOG_20171120
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_PHONE_CALL_LOG_20171120" 
   (	"GLOBAL_CALL_ID" NUMBER(10,0), 
	"CALL_ID" NUMBER(10,0), 
	"CALL_START" DATE, 
	"CALL_FROM" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(129 BYTE), 
	"CALL_TO" VARCHAR2(20 BYTE), 
	"CALL_TO_FINAL" VARCHAR2(20 BYTE), 
	"CALL_CONNECT" DATE, 
	"CALL_DIS_CONNECT" DATE, 
	"LAST_REDIRECT_DN" VARCHAR2(20 BYTE), 
	"CALL_DURATION" NUMBER(15,0), 
	"COMMENT_TEXT" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
