--------------------------------------------------------
--  DDL for Table SS_PHOTOCONSENT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_PHOTOCONSENT" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"BORNIN" VARCHAR2(35 BYTE), 
	"DOB" VARCHAR2(11 BYTE), 
	"RESIDENT" VARCHAR2(35 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"TAXNO" VARCHAR2(10 BYTE), 
	"ALTNO" VARCHAR2(16 BYTE), 
	"DATE_PLACE" VARCHAR2(35 BYTE), 
	"AGREE" NUMBER(1,0), 
	"CREATED_ON" DATE, 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
