--------------------------------------------------------
--  DDL for Table SS_PRINT_LOG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_PRINT_LOG" 
   (	"PRINT_DATE" DATE, 
	"TIME" VARCHAR2(11 BYTE), 
	"PRINT_SERVER" VARCHAR2(20 BYTE), 
	"QUE_NAME" VARCHAR2(20 BYTE), 
	"USERID" VARCHAR2(30 BYTE), 
	"USERID2" VARCHAR2(30 BYTE), 
	"PC_NAME" VARCHAR2(30 BYTE), 
	"FILE_NAME" VARCHAR2(1000 BYTE), 
	"PAGES" NUMBER(5,0), 
	"NOT_KNOWN" VARCHAR2(30 BYTE), 
	"COPIES" NUMBER(4,0), 
	"COLUMN12" VARCHAR2(100 BYTE), 
	"PRINT_TYPE" VARCHAR2(100 BYTE), 
	"COLOR" VARCHAR2(130 BYTE), 
	"PAGE_SIZE" VARCHAR2(90 BYTE), 
	"FIELD_1" VARCHAR2(40 BYTE), 
	"FIELD_2" VARCHAR2(40 BYTE), 
	"FIELD_3" VARCHAR2(60 BYTE), 
	"FIELD_4" VARCHAR2(40 BYTE), 
	"FIELD_5" VARCHAR2(40 BYTE), 
	"FIELD_6" VARCHAR2(50 BYTE), 
	"EMPNO" VARCHAR2(5 BYTE), 
	"PARENT" VARCHAR2(4 BYTE), 
	"PAGE_TYPE" VARCHAR2(6 BYTE), 
	"COST" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
