--------------------------------------------------------
--  DDL for Table SS_PAPER_SIZE_MAP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_PAPER_SIZE_MAP" 
   (	"SRC_PAPER_SIZE" VARCHAR2(20 BYTE), 
	"MAP_PAPER_SIZE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
