--------------------------------------------------------
--  DDL for Table SS_PHONE_EXT_LOG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_PHONE_EXT_LOG" 
   (	"PHONE_BAR_CODE" VARCHAR2(60 BYTE), 
	"PHONE_EXT" VARCHAR2(7 BYTE), 
	"REMARKS" VARCHAR2(200 BYTE), 
	"LOG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
