--------------------------------------------------------
--  DDL for Table SS_REJOIN
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_REJOIN" 
   (	"REJOINREQNUM" VARCHAR2(20 BYTE), 
	"REJOINREQDATE" DATE, 
	"EMPNO" CHAR(5 BYTE), 
	"COSTCODE" CHAR(6 BYTE), 
	"JOINDATE" DATE, 
	"SCR_CODE" CHAR(5 BYTE), 
	"SCR_DATE" DATE, 
	"HOD_CODE" CHAR(5 BYTE), 
	"HOD_APPRL" NUMBER(1,0) DEFAULT 0, 
	"HOD_APPRL_DT" DATE, 
	"HOD_TCPIP" VARCHAR2(30 BYTE), 
	"IT_CODE" CHAR(5 BYTE), 
	"IT_APPRL" NUMBER(1,0) DEFAULT NULL, 
	"IT_APPRL_DT" DATE, 
	"ITCORD_APPRL" NUMBER(1,0), 
	"ITCORD_APPRL_DT" DATE, 
	"TARGETDESK" VARCHAR2(7 BYTE), 
	"COMP" NUMBER(1,0), 
	"MON1" NUMBER(1,0), 
	"MON2" NUMBER(1,0), 
	"TEL" NUMBER(1,0), 
	"PRINT" NUMBER(1,0), 
	"DESKREQ" NUMBER(1,0), 
	"DESKLOC" VARCHAR2(20 BYTE), 
	"DESKSHARE" NUMBER(1,0) DEFAULT 0, 
	"LONGDEPUT" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT SELECT ON "SELFSERVICE"."SS_REJOIN" TO "DMS";
