--------------------------------------------------------
--  DDL for Table SS_REPORT_MAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_REPORT_MAST" 
   (	"REP_ID" VARCHAR2(2 BYTE), 
	"REP_NAME" VARCHAR2(60 BYTE), 
	"REP_FILE" VARCHAR2(100 BYTE), 
	"FOR_HOD" NUMBER(1,0), 
	"PERIOD_REQUIRED" NUMBER(1,0), 
	"PARENT_REQUIRED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
