--------------------------------------------------------
--  DDL for Table SS_SITE_LOC_MAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_SITE_LOC_MAST" 
   (	"LOC_CODE" CHAR(2 BYTE), 
	"LOC_DESC" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
