--------------------------------------------------------
--  DDL for Table SS_SITE_ALLOWANCE_PROCESSED
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_SITE_ALLOWANCE_PROCESSED" 
   (	"EMPNO" CHAR(5 BYTE), 
	"PROCESSED_MONTH" DATE, 
	"GRADE" CHAR(2 BYTE), 
	"SITE_CODE" CHAR(4 BYTE), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"AMOUNT" NUMBER(6,0), 
	"DELETED" NUMBER(1,0) DEFAULT 0, 
	"MODIFIED_ON" DATE DEFAULT sysdate, 
	"SYS_PROC_MONTH" CHAR(6 BYTE), 
	"IS_ERROR" NUMBER(1,0), 
	"ERROR_TEXT" VARCHAR2(200 BYTE), 
	"ROLL_OVER_COMPLETE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
