--------------------------------------------------------
--  DDL for Table SS_SITE_ALLWNC_PERIOD_ADJ_DEL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_SITE_ALLWNC_PERIOD_ADJ_DEL" 
   (	"EMPNO" CHAR(5 BYTE), 
	"ADJUSTMENT_MONTH" DATE, 
	"ADJ_FROM" DATE, 
	"ADJ_TO" DATE, 
	"REMARKS" VARCHAR2(60 BYTE), 
	"MODIFIED_ON" DATE, 
	"ADJ_MONTH" CHAR(6 BYTE), 
	"FOR_ALLOWANCE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
