--------------------------------------------------------
--  DDL for Table SS_SHIFTMAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_SHIFTMAST" 
   (	"SHIFTCODE" CHAR(2 BYTE), 
	"SHIFTDESC" VARCHAR2(60 BYTE), 
	"TIMEIN_HH" NUMBER(2,0), 
	"TIMEIN_MN" NUMBER(2,0), 
	"TIMEOUT_HH" NUMBER(2,0), 
	"TIMEOUT_MN" NUMBER(2,0), 
	"SHIFT4ALLOWANCE" NUMBER(1,0), 
	"LUNCH_MN" NUMBER(2,0), 
	"OT_APPLICABLE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
