--------------------------------------------------------
--  DDL for Table SS_USERMAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_USERMAST" 
   (	"EMPNO" CHAR(5 BYTE), 
	"TYPE" NUMBER(2,0), 
	"DESCRIPTION" VARCHAR2(30 BYTE), 
	"ACTIVE" NUMBER(1,0), 
	"TCP_IP" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT SELECT ON "SELFSERVICE"."SS_USERMAST" TO "DMS";
  GRANT UPDATE ON "SELFSERVICE"."SS_USERMAST" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SS_USERMAST" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SS_USERMAST" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SS_USERMAST" TO "TCMPL_APP_CONFIG";
