--------------------------------------------------------
--  DDL for Table SS_USB_REQUEST_CHG_LOG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_USB_REQUEST_CHG_LOG" 
   (	"KEY_ID" VARCHAR2(8 BYTE), 
	"EMPNO" VARCHAR2(5 BYTE), 
	"COMP_NAME" VARCHAR2(30 BYTE), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
