--------------------------------------------------------
--  DDL for Table SS_WORKED_HRS_MAST
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_WORKED_HRS_MAST" 
   (	"KEY_ID" VARCHAR2(5 BYTE), 
	"YYYYMM" VARCHAR2(6 BYTE), 
	"MODIFIED_ON" DATE, 
	"PROC_STATUS" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."SS_WORKED_HRS_MAST"."PROC_STATUS" IS 'OK Complete, KO Error, WP Work in Progress';
