--------------------------------------------------------
--  DDL for Table SS_WORKED_HRS_DETAIL
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_WORKED_HRS_DETAIL" 
   (	"KEY_ID" VARCHAR2(5 BYTE), 
	"YYYYMM" VARCHAR2(6 BYTE), 
	"EMPNO" VARCHAR2(5 BYTE), 
	"TAR_WORK_HRS" NUMBER(10,5), 
	"ACT_WORK_HRS" NUMBER(10,5), 
	"ACT_SAT_WORK_HRS" NUMBER(10,5), 
	"ACT_SAT_WORK_DAYS" NUMBER(10,5), 
	"ACT_SUN_WORK_HRS" NUMBER(10,5), 
	"ACT_SUN_WORK_DAYS" NUMBER(10,5), 
	"ACT_HH_WORK_HRS" NUMBER(10,5), 
	"ACT_HH_WORK_DAYS" NUMBER(10,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
