--------------------------------------------------------
--  DDL for Table SS_XL_BLOB
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SS_XL_BLOB" 
   (	"BLOB_FIELD" BLOB, 
	"KEY_ID" VARCHAR2(8 BYTE), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" 
 LOB ("BLOB_FIELD") STORE AS BASICFILE (
  TABLESPACE "APPL_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT UPDATE ON "SELFSERVICE"."SS_XL_BLOB" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SS_XL_BLOB" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SS_XL_BLOB" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SS_XL_BLOB" TO "TCMPL_APP_CONFIG";
