--------------------------------------------------------
--  DDL for Table SWP_TPL_VACCINE_BATCH_EMP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_TPL_VACCINE_BATCH_EMP" 
   (	"EMPNO" CHAR(5 BYTE), 
	"BATCH_KEY_ID" VARCHAR2(8 BYTE), 
	"TIME_SLOT" VARCHAR2(20 BYTE), 
	"TRANSPORT" VARCHAR2(50 BYTE), 
	"JAB_FOR_THIS_SLOT" VARCHAR2(20 BYTE), 
	"INOCULATED" VARCHAR2(2 BYTE), 
	"BUS_ROUTE_ID" VARCHAR2(200 BYTE), 
	"BUS_PICKUP_POINTS" VARCHAR2(2000 BYTE), 
	"BUS_START_TIME" VARCHAR2(20 BYTE), 
	"BUS_MOBILE" VARCHAR2(300 BYTE), 
	"PREFERRED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT UPDATE ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH_EMP" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH_EMP" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH_EMP" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH_EMP" TO "TCMPL_APP_CONFIG";
