--------------------------------------------------------
--  DDL for Table SWP_TPL_VACCINE_BATCH
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_TPL_VACCINE_BATCH" 
   (	"BATCH_KEY_ID" VARCHAR2(8 BYTE), 
	"VACCINE_DATE" DATE, 
	"EMP_ASSIGN_END_DATE" DATE, 
	"IS_OPEN" VARCHAR2(2 BYTE), 
	"MODIFIED_ON" DATE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT UPDATE ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_TPL_VACCINE_BATCH" TO "TCMPL_APP_CONFIG";
