--------------------------------------------------------
--  DDL for Table SWP_MAIL_LOG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_MAIL_LOG" 
   (	"SUBJECT" VARCHAR2(1000 BYTE), 
	"MAIL_SENT_TO_CC_BCC" VARCHAR2(4000 BYTE), 
	"MODIFIED_ON" DATE, 
	"MAIL_SENT_STATUS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
