--------------------------------------------------------
--  DDL for Table SWP_VACCINATION_OFFICE_BATCH_2
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" 
   (	"EMPNO" CHAR(5 BYTE), 
	"VACCINATION_FOR" VARCHAR2(20 BYTE), 
	"PREFERRED_DATE" DATE, 
	"JAB_NUMBER" VARCHAR2(20 BYTE), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT UPDATE ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_BATCH_2" TO "TCMPL_APP_CONFIG";
