--------------------------------------------------------
--  DDL for Table SWP_IT_PREREQUISITES
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_IT_PREREQUISITES" 
   (	"EMPNO" CHAR(5 BYTE), 
	"DOWNLOAD_SPEED" VARCHAR2(2 BYTE), 
	"UPLOAD_SPEED" VARCHAR2(2 BYTE), 
	"MONTHLY_QUOTA" VARCHAR2(2 BYTE), 
	"ISP_NAME" VARCHAR2(30 BYTE), 
	"ROUTER_BRAND" VARCHAR2(60 BYTE), 
	"ROUTER_MODEL" VARCHAR2(60 BYTE), 
	"MODIFIED_ON" DATE, 
	"MS_AUTH_ON_OWN_MOB" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."SWP_IT_PREREQUISITES"."DOWNLOAD_SPEED" IS 'OK = Greater than 10MB';
   COMMENT ON COLUMN "SELFSERVICE"."SWP_IT_PREREQUISITES"."UPLOAD_SPEED" IS 'OK = Greater than 10MB';
   COMMENT ON COLUMN "SELFSERVICE"."SWP_IT_PREREQUISITES"."MONTHLY_QUOTA" IS 'OK = Greater than 200GB';
   COMMENT ON COLUMN "SELFSERVICE"."SWP_IT_PREREQUISITES"."ISP_NAME" IS 'KO = MTNL / BSNL';
   COMMENT ON COLUMN "SELFSERVICE"."SWP_IT_PREREQUISITES"."MS_AUTH_ON_OWN_MOB" IS 'OK = Install on Own Mobile, KK=Company Provided Mobile';
  GRANT UPDATE ON "SELFSERVICE"."SWP_IT_PREREQUISITES" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_IT_PREREQUISITES" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_IT_PREREQUISITES" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_IT_PREREQUISITES" TO "TCMPL_APP_CONFIG";
