--------------------------------------------------------
--  DDL for Table SWP_EMP_TRAINING
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_EMP_TRAINING" 
   (	"EMPNO" CHAR(5 BYTE), 
	"SECURITY" NUMBER(1,0), 
	"SHAREPOINT16" NUMBER(1,0), 
	"ONEDRIVE365" NUMBER(1,0), 
	"TEAMS" NUMBER(1,0), 
	"PLANNER" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT UPDATE ON "SELFSERVICE"."SWP_EMP_TRAINING" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_EMP_TRAINING" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_EMP_TRAINING" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_EMP_TRAINING" TO "TCMPL_APP_CONFIG";
