--------------------------------------------------------
--  DDL for Table SWP_VACCINE_DATES
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_VACCINE_DATES" 
   (	"EMPNO" CHAR(5 BYTE), 
	"JAB1_DATE" DATE, 
	"JAB2_DATE" DATE, 
	"MODIFIED_ON" DATE, 
	"VACCINE_TYPE" VARCHAR2(20 BYTE), 
	"IS_JAB1_BY_OFFICE" VARCHAR2(2 BYTE), 
	"IS_JAB2_BY_OFFICE" VARCHAR2(2 BYTE), 
	"MODIFIED_BY" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT UPDATE ON "SELFSERVICE"."SWP_VACCINE_DATES" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_VACCINE_DATES" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_VACCINE_DATES" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_VACCINE_DATES" TO "TCMPL_APP_CONFIG";
