--------------------------------------------------------
--  DDL for Table SWP_CONFIG_WEEKS
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_CONFIG_WEEKS" 
   (	"KEY_ID" CHAR(8 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PLANNING_FLAG" NUMBER(1,0), 
	"PLANNING_OPEN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."SWP_CONFIG_WEEKS"."PLANNING_FLAG" IS '2(Current/Future), 1(Current), 0(Past)';
   COMMENT ON COLUMN "SELFSERVICE"."SWP_CONFIG_WEEKS"."PLANNING_OPEN" IS '1 - Open / 0 - Close';
