--------------------------------------------------------
--  DDL for Table SWP_VACCINATION_OFFICE_FAMILY
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_FAMILY" 
   (	"EMPNO" CHAR(5 BYTE), 
	"FAMILY_MEMBER_NAME" VARCHAR2(100 BYTE), 
	"RELATION" VARCHAR2(20 BYTE), 
	"YEAR_OF_BIRTH" NUMBER, 
	"MODIFIED_ON" DATE, 
	"KEY_ID" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT UPDATE ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_FAMILY" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_FAMILY" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_FAMILY" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_VACCINATION_OFFICE_FAMILY" TO "TCMPL_APP_CONFIG";
