--------------------------------------------------------
--  DDL for Table SWP_SMART_ATTENDANCE_PLAN
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_SMART_ATTENDANCE_PLAN" 
   (	"KEY_ID" CHAR(10 BYTE), 
	"WS_KEY_ID" CHAR(10 BYTE), 
	"EMPNO" CHAR(5 BYTE), 
	"ATTENDANCE_DATE" DATE, 
	"MODIFIED_ON" DATE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE), 
	"DESKID" VARCHAR2(10 BYTE), 
	"WEEK_KEY_ID" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
