--------------------------------------------------------
--  DDL for Table SWP_EXCLUDE_EMP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" 
   (	"KEY_ID" VARCHAR2(10 BYTE), 
	"EMPNO" CHAR(5 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REASON" VARCHAR2(400 BYTE), 
	"MODIFIED_ON" DATE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE), 
	"IS_ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
--------------------------------------------------------
--  DDL for Index SWP_EXCLUDE_EMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."SWP_EXCLUDE_EMP_PK" ON "SELFSERVICE"."SWP_EXCLUDE_EMP" ("KEY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
--------------------------------------------------------
--  DDL for Index SWP_EXCLUDE_EMP_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."SWP_EXCLUDE_EMP_UK" ON "SELFSERVICE"."SWP_EXCLUDE_EMP" ("EMPNO", "START_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
--------------------------------------------------------
--  Constraints for Table SWP_EXCLUDE_EMP
--------------------------------------------------------

  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" ADD CONSTRAINT "SWP_EXCLUDE_EMP_UK" UNIQUE ("EMPNO", "START_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("MODIFIED_ON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" ADD CONSTRAINT "SWP_EXCLUDE_EMP_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE;
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
  ALTER TABLE "SELFSERVICE"."SWP_EXCLUDE_EMP" MODIFY ("KEY_ID" NOT NULL ENABLE);
