--------------------------------------------------------
--  DDL for Table SWP_VACCINATION_OFFICE_210612
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_VACCINATION_OFFICE_210612" 
   (	"EMPNO" CHAR(5 BYTE), 
	"COWIN_REGTRD" VARCHAR2(2 BYTE), 
	"MOBILE" VARCHAR2(10 BYTE), 
	"OFFICE_BUS" VARCHAR2(2 BYTE), 
	"OFFICE_BUS_ROUTE" VARCHAR2(10 BYTE), 
	"ATTENDING_VACCINATION" VARCHAR2(2 BYTE), 
	"NOT_ATTENDING_REASON" VARCHAR2(200 BYTE), 
	"JAB_NUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
