--------------------------------------------------------
--  DDL for Table SWP_BUS_ROUTES
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."SWP_BUS_ROUTES" 
   (	"ROUTE_ID" VARCHAR2(10 BYTE), 
	"PICKUP_POINTS" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
  GRANT UPDATE ON "SELFSERVICE"."SWP_BUS_ROUTES" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."SWP_BUS_ROUTES" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."SWP_BUS_ROUTES" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."SWP_BUS_ROUTES" TO "TCMPL_APP_CONFIG";
