--------------------------------------------------------
--  DDL for Table USERIDS
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."USERIDS" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"OFFICE" VARCHAR2(40 BYTE), 
	"USERID" VARCHAR2(50 BYTE), 
	"DATETIME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"DOMAIN" VARCHAR2(50 BYTE), 
	"MODIFIED_ON" DATE, 
	"INSERT_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "ITINV_STK" WITH GRANT OPTION;
  GRANT DELETE ON "SELFSERVICE"."USERIDS" TO "DMS";
  GRANT INSERT ON "SELFSERVICE"."USERIDS" TO "DMS";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "DMS" WITH GRANT OPTION;
  GRANT UPDATE ON "SELFSERVICE"."USERIDS" TO "DMS";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "AMS" WITH GRANT OPTION;
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "IOT_TCMPL" WITH GRANT OPTION;
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "STATIONERY" WITH GRANT OPTION;
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "TCMPL_HR" WITH GRANT OPTION;
  GRANT UPDATE ON "SELFSERVICE"."USERIDS" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "SELFSERVICE"."USERIDS" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "SELFSERVICE"."USERIDS" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "RWM3";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "REMOTEWORKING";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "NEW_TIMECURR";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "COMMONMASTERS";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "TIMECURR";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "HR_MBO";
  GRANT SELECT ON "SELFSERVICE"."USERIDS" TO "EIPM_HSE";
