--------------------------------------------------------
--  DDL for Table USERIDS_20210510
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."USERIDS_20210510" 
   (	"EMPNO" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"OFFICE" VARCHAR2(40 BYTE), 
	"USERID" VARCHAR2(50 BYTE), 
	"DATETIME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"DOMAIN" VARCHAR2(50 BYTE), 
	"MODIFIED_ON" DATE, 
	"INSERT_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
