--------------------------------------------------------
--  DDL for Table USERID_LOG
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."USERID_LOG" 
   (	"EMPNO_OLD" VARCHAR2(5 BYTE), 
	"USERID_OLD" VARCHAR2(60 BYTE), 
	"EMPNO_NU" VARCHAR2(5 BYTE), 
	"USERID_NU" VARCHAR2(60 BYTE), 
	"OPERATION" VARCHAR2(20 BYTE), 
	"MODIFIED_ON" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
