--------------------------------------------------------
--  DDL for Table XDM_LOGINRIGHT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_LOGINRIGHT" 
   (	"TRANS_ID" VARCHAR2(20 BYTE), 
	"TRANS_DATE" DATE, 
	"FROM_DESK" VARCHAR2(7 BYTE), 
	"FROM_MACHINE" VARCHAR2(20 BYTE), 
	"TO_DESK" VARCHAR2(7 BYTE), 
	"TO_MACHINE" VARCHAR2(20 BYTE), 
	"EMPNO" CHAR(5 BYTE), 
	"FLAG_APPRD" NUMBER(1,0), 
	"LOG_FILE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
