--------------------------------------------------------
--  DDL for Table XDM_ASSETMOVE_TRAN_16APR10
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ASSETMOVE_TRAN_16APR10" 
   (	"MOVEREQNUM" VARCHAR2(18 BYTE), 
	"MOVEREQDATE" DATE, 
	"EMPNO" CHAR(5 BYTE), 
	"CURRDESK" VARCHAR2(7 BYTE), 
	"TARGETDESK" VARCHAR2(7 BYTE), 
	"IT_APPRL" NUMBER(1,0), 
	"IT_CODE" CHAR(5 BYTE), 
	"IT_DATE" DATE, 
	"IT_CORD_APPRL" NUMBER(1,0), 
	"IT_CORD_DATE" DATE, 
	"ASSETFLAG" NUMBER(1,0), 
	"EMPFLAG" NUMBER(1,0), 
	"COMP" NUMBER(1,0), 
	"MON1" NUMBER(1,0), 
	"MON2" NUMBER(1,0), 
	"TEL" NUMBER(1,0), 
	"PRINT" NUMBER(1,0), 
	"DESKREQ" NUMBER(1,0), 
	"DESKLOC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
