--------------------------------------------------------
--  DDL for Table XDM_LAPTOP
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_LAPTOP" 
   (	"LP_REQNO" VARCHAR2(20 BYTE), 
	"LP_REQDATE" DATE, 
	"EMPNO" CHAR(5 BYTE), 
	"PROJNO" CHAR(7 BYTE), 
	"FDATE" DATE, 
	"TDATE" DATE, 
	"EDATE" DATE, 
	"HOD_CODE" CHAR(5 BYTE), 
	"HOD_APPRL" NUMBER(1,0), 
	"HOD_APPRL_DT" DATE, 
	"IT_APPRL_DT" DATE, 
	"ISSUEDATE" DATE, 
	"SOFTLIST" VARCHAR2(200 BYTE), 
	"REMARKS" VARCHAR2(200 BYTE), 
	"BARCODE" VARCHAR2(13 BYTE), 
	"RETURNDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
