--------------------------------------------------------
--  DDL for Table XDM_SPECIAL_SHIFTING
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_SPECIAL_SHIFTING" 
   (	"EMPNO" CHAR(5 BYTE), 
	"LOGINID" VARCHAR2(20 BYTE), 
	"COMPNAME" VARCHAR2(20 BYTE), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"REASON" VARCHAR2(50 BYTE), 
	"FLAG_APPLIED" NUMBER(1,0), 
	"FLAG_ROLLBACK" NUMBER(1,0), 
	"TRANS_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
