--------------------------------------------------------
--  DDL for Table XDM_ASSET_MODIFY
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ASSET_MODIFY" 
   (	"REQNUM" VARCHAR2(25 BYTE), 
	"REQDATE" DATE, 
	"DESKID" VARCHAR2(7 BYTE), 
	"ASSETTYPE" CHAR(2 BYTE), 
	"ASEETID_OLD" VARCHAR2(13 BYTE), 
	"ASSETID_NEW" VARCHAR2(13 BYTE), 
	"ACTIONCODE" CHAR(1 BYTE), 
	"ENGG_CODE" CHAR(5 BYTE), 
	"ITCORD_STATUS" NUMBER(1,0) DEFAULT 0, 
	"ITCORD_CODE" CHAR(5 BYTE), 
	"ITCORD_DATE" DATE, 
	"ASSETNAME_OLD" VARCHAR2(20 BYTE), 
	"ASSETNAME_NEW" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."XDM_ASSET_MODIFY"."ACTIONCODE" IS '"R" - Replace, "A" - Add, "D" - Delete';
   COMMENT ON COLUMN "SELFSERVICE"."XDM_ASSET_MODIFY"."ITCORD_STATUS" IS '"0" - Pending, "1" - Done';
