--------------------------------------------------------
--  DDL for Table XDM_ACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ACTION_TYPE" 
   (	"TYPEID" NUMBER(2,0), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"OUTOFSERVICE_FLAG" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."XDM_ACTION_TYPE"."OUTOFSERVICE_FLAG" IS '1 is out_of_service, -1 is non ou_of_service';
