--------------------------------------------------------
--  DDL for Table XDM_GUESTMASTER
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_GUESTMASTER" 
   (	"GNUM" CHAR(5 BYTE), 
	"GNAME" VARCHAR2(30 BYTE), 
	"GCOSTCODE" CHAR(4 BYTE), 
	"GPROJNUM" CHAR(7 BYTE), 
	"GFROMDATE" DATE, 
	"GTODATE" DATE, 
	"GDATE" DATE, 
	"HOD_APPRL" NUMBER(1,0), 
	"HOD_CODE" CHAR(5 BYTE), 
	"HOD_DATE" DATE, 
	"IT_APPRL" NUMBER(1,0), 
	"IT_CODE" CHAR(5 BYTE), 
	"IT_DATE" DATE, 
	"ITCORD_APPRL" NUMBER(1,0), 
	"ITCORD_DATE" DATE, 
	"TARGETDESK" VARCHAR2(7 BYTE), 
	"COMP" NUMBER(1,0), 
	"MON1" NUMBER(1,0), 
	"MON2" NUMBER(1,0), 
	"TEL" NUMBER(1,0), 
	"PRINT" NUMBER(1,0), 
	"DESKREQ" NUMBER(1,0), 
	"DESKLOC" VARCHAR2(20 BYTE), 
	"GMODDATE" DATE, 
	"GMODBY" CHAR(5 BYTE), 
	"DESKSHARE" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
