--------------------------------------------------------
--  DDL for Table XDM_DESKMASTER
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_DESKMASTER" 
   (	"DESKID" VARCHAR2(7 BYTE), 
	"OFFICE" CHAR(5 BYTE), 
	"FLOOR" VARCHAR2(8 BYTE), 
	"SEATNO" VARCHAR2(10 BYTE), 
	"WING" VARCHAR2(5 BYTE), 
	"ASSETCODE" VARCHAR2(20 BYTE), 
	"NOEXIST" CHAR(1 BYTE), 
	"CABIN" CHAR(1 BYTE), 
	"REMARKS" VARCHAR2(20 BYTE), 
	"DESKID_OLD" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
