--------------------------------------------------------
--  DDL for Table XDM_DESKMASTER_OLD
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_DESKMASTER_OLD" 
   (	"DESKID" CHAR(6 BYTE), 
	"OFFICE" CHAR(5 BYTE), 
	"FLOOR" CHAR(8 BYTE), 
	"SEATNO" CHAR(10 BYTE), 
	"WING" CHAR(5 BYTE), 
	"ASSETCODE" CHAR(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
