--------------------------------------------------------
--  DDL for Table XDM_ONDEPUTATION_31JAN2010
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ONDEPUTATION_31JAN2010" 
   (	"LOCATION" VARCHAR2(38 BYTE), 
	"EMPNO" VARCHAR2(5 BYTE), 
	"PROJECT" VARCHAR2(37 BYTE), 
	"DESG" VARCHAR2(39 BYTE), 
	"FROMDATE" VARCHAR2(8 BYTE), 
	"TODATE" VARCHAR2(7 BYTE), 
	"DESCRIPTION" VARCHAR2(96 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
