--------------------------------------------------------
--  DDL for Table XDM_EMP_LEFT
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_EMP_LEFT" 
   (	"REQNUM" CHAR(11 BYTE), 
	"REQDATE" DATE, 
	"REQBY" CHAR(5 BYTE), 
	"EMPNO" CHAR(5 BYTE), 
	"DOL" DATE, 
	"ACTION_FLAG" NUMBER DEFAULT 0, 
	"ACTIONBY" CHAR(5 BYTE), 
	"ACTIONDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."XDM_EMP_LEFT"."ACTION_FLAG" IS '"0" means Live; "1" means Close';
