--------------------------------------------------------
--  DDL for Table XDM_ASSETCODE_20DEC
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ASSETCODE_20DEC" 
   (	"BARCODE" CHAR(13 BYTE), 
	"PONUM" CHAR(15 BYTE), 
	"GRNUM" CHAR(15 BYTE), 
	"INVOICENUM" VARCHAR2(20 BYTE), 
	"ASSETTYPE" CHAR(2 BYTE), 
	"STPI" NUMBER(1,0), 
	"BARCODE1" NUMBER(5,0), 
	"ASSETCODE" CHAR(7 BYTE), 
	"PRNTFLAG" NUMBER(1,0), 
	"SERIALNUM" VARCHAR2(35 BYTE), 
	"SCRAP" NUMBER(1,0), 
	"SCRAP_DATE" DATE, 
	"MODEL" VARCHAR2(50 BYTE), 
	"COMPNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
