--------------------------------------------------------
--  DDL for Table XDM_AMS_TRANSCODE
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_AMS_TRANSCODE" 
   (	"BARCODE" VARCHAR2(13 BYTE), 
	"AMS_ASSET_ID" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
