--------------------------------------------------------
--  DDL for Table XDM_INTERNETMASTER
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_INTERNETMASTER" 
   (	"EMPNO" CHAR(5 BYTE), 
	"PC_NAME" VARCHAR2(25 BYTE), 
	"PC_IP" VARCHAR2(20 BYTE), 
	"INTERNET_ID" VARCHAR2(50 BYTE), 
	"GRANT_DATE" DATE, 
	"ACCESS_STATUS" NUMBER(1,0) DEFAULT 0, 
	"REVOKE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."XDM_INTERNETMASTER"."ACCESS_STATUS" IS '"1" is Granted, "-1" is Revoked';
