--------------------------------------------------------
--  DDL for Table XDM_ASSET_REMOVED
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ASSET_REMOVED" 
   (	"ASSET_CODE" VARCHAR2(30 BYTE), 
	"PC_NAME" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"MODIFIED_ON" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
