--------------------------------------------------------
--  DDL for Table XDM_ASSETCODE
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ASSETCODE" 
   (	"BARCODE" CHAR(13 BYTE), 
	"PONUM" CHAR(15 BYTE), 
	"GRNUM" CHAR(15 BYTE), 
	"INVOICENUM" VARCHAR2(20 BYTE), 
	"ASSETTYPE" CHAR(2 BYTE), 
	"STPI" NUMBER(1,0), 
	"BARCODE1" NUMBER(5,0), 
	"ASSETCODE" CHAR(7 BYTE), 
	"PRNTFLAG" NUMBER(1,0), 
	"SERIALNUM" VARCHAR2(35 BYTE), 
	"SCRAP" NUMBER(1,0), 
	"SCRAP_DATE" DATE, 
	"MODEL" VARCHAR2(50 BYTE), 
	"COMPNAME" VARCHAR2(20 BYTE), 
	"OUT_OF_SERVICE" NUMBER(1,0), 
	"PODATE" DATE, 
	"WARRANTY_END" DATE, 
	"HDD" VARCHAR2(20 BYTE), 
	"RAM" VARCHAR2(20 BYTE), 
	"PROCESSOR" VARCHAR2(50 BYTE), 
	"OPTICAL_DRIVE" VARCHAR2(50 BYTE), 
	"INVOICE_DATE" DATE, 
	"SAP_ASSETCODE" VARCHAR2(50 BYTE), 
	"OUTOFSERVICE_TYPE" NUMBER(1,0), 
	"TO_BE_SCRAP" NUMBER(1,0), 
	"BARCODE_OLD" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
