--------------------------------------------------------
--  DDL for Table XDM_ASSETMODIFICATION
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_ASSETMODIFICATION" 
   (	"MOVEREQNUM" VARCHAR2(17 BYTE), 
	"DESKID" VARCHAR2(7 BYTE), 
	"FROM_ASSET" VARCHAR2(20 BYTE), 
	"TO_ASSET" VARCHAR2(20 BYTE), 
	"REMOVED" NUMBER(1,0), 
	"MODIFY_BY" CHAR(5 BYTE), 
	"MODIFY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
