--------------------------------------------------------
--  DDL for Table XDM_INTERNET
--------------------------------------------------------

  CREATE TABLE "SELFSERVICE"."XDM_INTERNET" 
   (	"EMPNO" CHAR(5 BYTE), 
	"CURRDESK" VARCHAR2(7 BYTE), 
	"CURRPC" VARCHAR2(20 BYTE), 
	"OLDDESK" VARCHAR2(7 BYTE), 
	"OLDPC" VARCHAR2(20 BYTE), 
	"CURRIP" VARCHAR2(20 BYTE), 
	"INTERNETID" VARCHAR2(65 BYTE), 
	"GRANTSTATUS" NUMBER(1,0) DEFAULT 0, 
	"GRANTDATE" DATE, 
	"REVOKESTATUS" NUMBER(1,0) DEFAULT 0, 
	"REVOKEDATE" DATE, 
	"REMARKS" VARCHAR2(100 BYTE), 
	"RECDATE" DATE, 
	"DSKMGMT" NUMBER(1,0) DEFAULT 1, 
	"REVOKEFLAG" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "SELFSERVICE"."XDM_INTERNET"."GRANTSTATUS" IS '"0" Default, "1" Granted, "2" To Delete';
   COMMENT ON COLUMN "SELFSERVICE"."XDM_INTERNET"."REVOKESTATUS" IS '"0" No, "1" Yes';
   COMMENT ON COLUMN "SELFSERVICE"."XDM_INTERNET"."DSKMGMT" IS '"0" No, "1" Yes';
   COMMENT ON COLUMN "SELFSERVICE"."XDM_INTERNET"."REVOKEFLAG" IS '"0" Default, "1" To be Revoke';
