--------------------------------------------------------
--  DDL for Index FTP_ADMIN_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."FTP_ADMIN_USER_PK" ON "SELFSERVICE"."FTP_ADMIN_USER" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
