--------------------------------------------------------
--  DDL for Index IDX_GEN_CODES
--------------------------------------------------------

  CREATE INDEX "SELFSERVICE"."IDX_GEN_CODES" ON "SELFSERVICE"."SS_GENERAL_CODES" ("CATG", "CODE1", "CODE2", "CODE3", "CODE4") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
