--------------------------------------------------------
--  DDL for Index PK_EMPNO_BDATE_DEPU_HIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."PK_EMPNO_BDATE_DEPU_HIST" ON "SELFSERVICE"."SS_DEPU_HIST" ("EMPNO", "BDATE", "CHG_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
