--------------------------------------------------------
--  DDL for Index PK_SEC_EMPNO_HOD_REP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."PK_SEC_EMPNO_HOD_REP" ON "SELFSERVICE"."SS_SECRETARY_REP" ("EMPNO", "HOD", "REP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
