--------------------------------------------------------
--  DDL for Index PK_SEC
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."PK_SEC" ON "SELFSERVICE"."SS_SECRETARY_20081011" ("EMPNO", "HOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
