--------------------------------------------------------
--  DDL for Index SS_HEALTH_HRD_IDX$$_1B5D0004
--------------------------------------------------------

  CREATE INDEX "SELFSERVICE"."SS_HEALTH_HRD_IDX$$_1B5D0004" ON "SELFSERVICE"."SS_HEALTH_HRD" ("PRNT", "APPLNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
