--------------------------------------------------------
--  DDL for Index SS_IND_ETY_DT_PRN_Q_CANON
--------------------------------------------------------

  CREATE INDEX "SELFSERVICE"."SS_IND_ETY_DT_PRN_Q_CANON" ON "SELFSERVICE"."SS_PAGECOUNT_CANON" ("ENTRY_DATE", "PRN_QUEUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
