--------------------------------------------------------
--  DDL for Index U_EMPNOHH1MM1TYPEPDATE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELFSERVICE"."U_EMPNOHH1MM1TYPEPDATE" ON "SELFSERVICE"."SS_ONDUTYAPP" ("EMPNO", "PDATE", "HH1", "MM1", "TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
