
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TCMPL_HR"."OFB_VU_MODULE_USER_ROLE_ACTIONS" ("MODULE_ID", "ACTION_ID", "ACTION_NAME", "ACTION_DESC", "EMPNO") AS 
  Select
    "MODULE_ID","ACTION_ID","ACTION_NAME","ACTION_DESC","EMPNO"
From
    tcmpl_app_config.vu_module_user_role_actions_4_ofb;

