
  CREATE TABLE "TCMPL_HR"."DG_MID_TRANSFER_COSTCODE_POST_APPROVALS_LOG" 
   (	"KEY_ID" CHAR(8 BYTE) NOT NULL ENABLE, 
	"TRANSFER_END_DATE" DATE NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(100 BYTE), 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

