CREATE TABLE DG_MID_TRANSFER_TYPE (
    VALUE       NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(50) NOT NULL,
    STATUS      NUMBER NOT NULL,
    CONSTRAINT DG_MID_TRANSFER_TYPE_PK PRIMARY KEY ( VALUE ) ENABLE
);

ALTER TABLE DG_MID_TRANSFER_COSTCODE
    ADD CONSTRAINT DG_MID_TRANSFER_COSTCODE_FK1 FOREIGN KEY ( TRANSFER_TYPE_FK )
        REFERENCES DG_MID_TRANSFER_TYPE ( VALUE )
    ENABLE;

INSERT INTO "TCMPL_HR"."DG_MID_TRANSFER_TYPE" (VALUE, DESCRIPTION, STATUS) VALUES ('0', 'Permanent', '1');
INSERT INTO "TCMPL_HR"."DG_MID_TRANSFER_TYPE" (VALUE, DESCRIPTION, STATUS) VALUES ('1', 'Temporary-site', '1');
INSERT INTO "TCMPL_HR"."DG_MID_TRANSFER_TYPE" (VALUE, DESCRIPTION, STATUS) VALUES ('2', 'Return from site', '1');

GRANT UPDATE ON "TCMPL_HR"."DG_MID_TRANSFER_TYPE" TO "TCMPL_APP_CONFIG";
GRANT SELECT ON "TCMPL_HR"."DG_MID_TRANSFER_TYPE" TO "TCMPL_APP_CONFIG";
GRANT INSERT ON "TCMPL_HR"."DG_MID_TRANSFER_TYPE" TO "TCMPL_APP_CONFIG";
GRANT DELETE ON "TCMPL_HR"."DG_MID_TRANSFER_TYPE" TO "TCMPL_APP_CONFIG";  
