
  CREATE TABLE "TCMPL_HR"."DG_MID_TRANSFER_COSTCODE" 
   (	"KEY_ID" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"TRANSFER_TYPE_FK" NUMBER NOT NULL ENABLE, 
	"EMP_NO" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"CURRENT_COSTCODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"TARGET_COSTCODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"TRANSFER_DATE" DATE NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"STATUS" NUMBER, 
	"EFFECTIVE_TRANSFER_DATE" DATE, 
	"DESGCODE" VARCHAR2(6 BYTE), 
	"MODIFIED_ON" DATE NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"FLAG" NUMBER DEFAULT 0, 
	"SITE_CODE" VARCHAR2(4 BYTE), 
	 CONSTRAINT "DG_MID_TRANSFER_COSTCODE_PK" PRIMARY KEY ("KEY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "DG_MID_TRANSFER_COSTCODE_FK1" FOREIGN KEY ("TRANSFER_TYPE_FK")
	  REFERENCES "TCMPL_HR"."DG_MID_TRANSFER_TYPE" ("VALUE") ENABLE, 
	 CONSTRAINT "DG_MID_TRANSFER_COSTCODE_FK2" FOREIGN KEY ("STATUS")
	  REFERENCES "TCMPL_HR"."DG_MID_TRANSFER_STATUS" ("VALUE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

