
  CREATE TABLE "TCMPL_HR"."MIS_RESIGNED_MAIL_LOG" 
   (	"MAIL_TO" VARCHAR2(2000 BYTE), 
	"MAIL_FROM" VARCHAR2(2000 BYTE), 
	"MAIL_BCC" VARCHAR2(2000 BYTE), 
	"MAIL_SUCCESS" VARCHAR2(200 BYTE), 
	"MAIL_SUCCESS_MESSAGE" VARCHAR2(2000 BYTE), 
	"MAIL_DATE" DATE, 
	"MAIL_CC" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" 
  NO INMEMORY ("MAIL_BCC") ;


  GRANT DELETE ON "TCMPL_HR"."MIS_RESIGNED_MAIL_LOG" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."MIS_RESIGNED_MAIL_LOG" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."MIS_RESIGNED_MAIL_LOG" TO "TCMPL_APP_CONFIG";
  GRANT UPDATE ON "TCMPL_HR"."MIS_RESIGNED_MAIL_LOG" TO "TCMPL_APP_CONFIG";
