--------------------------------------------------------
--  DDL for Table OFB_EMP_CONTACT_INFO
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_EMP_CONTACT_INFO" 
   (	"EMPNO" CHAR(5), 
	"ADDRESS" VARCHAR2(200), 
	"MOBILE_PRIMARY" VARCHAR2(10), 
	"ALTERNATE_NUMBER" NVARCHAR2(20), 
	"MODIFIED_ON" DATE, 
	"RELIEVING_DATE" DATE, 
	"HR_NOTE" VARCHAR2(200)
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_EMP_CONTACT_INFO" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_EMP_CONTACT_INFO" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_EMP_CONTACT_INFO" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_EMP_CONTACT_INFO" TO "TCMPL_APP_CONFIG";
