--------------------------------------------------------
--  DDL for Table OFB_EMP_EXITS
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_EMP_EXITS" 
   (	"EMPNO" CHAR(5), 
	"PARENT" CHAR(4), 
	"END_BY_DATE" DATE, 
	"RELIEVING_DATE" DATE, 
	"REMARKS" VARCHAR2(200), 
	"HR_NOTE" VARCHAR2(200), 
	"ADDRESS" VARCHAR2(200), 
	"MOBILE_PRIMARY" VARCHAR2(10), 
	"ALTERNATE_NUMBER" VARCHAR2(20), 
	"CREATED_BY" CHAR(5), 
	"CREATED_ON" DATE, 
	"MODIFIED_ON" DATE, 
	"MODIFIED_BY" CHAR(5), 
	"EMAIL_ID" VARCHAR2(100), 
	"RESIGNATION_DATE" DATE
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_EMP_EXITS" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_EMP_EXITS" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_EMP_EXITS" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_EMP_EXITS" TO "TCMPL_APP_CONFIG";
