--------------------------------------------------------
--  DDL for Table OFB_FILES
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_FILES" 
   (	"KEY_ID" CHAR(8), 
	"EMPNO" CHAR(5), 
	"UPLOAD_BY_GROUP" VARCHAR2(20), 
	"UPLOAD_BY_EMPNO" CHAR(5), 
	"CLIENT_FILE_NAME" VARCHAR2(100), 
	"SERVER_FILE_NAME" VARCHAR2(100), 
	"UPLOAD_DATE" DATE
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_FILES" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_FILES" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_FILES" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_FILES" TO "TCMPL_APP_CONFIG";
