--------------------------------------------------------
--  DDL for Table OFB_MAIL_LOG
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_MAIL_LOG" 
   (	"MAIL_TO" VARCHAR2(2000), 
	"MAIL_FROM" VARCHAR2(2000), 
	"MAIL_BCC" VARCHAR2(2000), 
	"MAIL_SUCCESS" VARCHAR2(200), 
	"MAIL_SUCCESS_MESSAGE" VARCHAR2(2000), 
	"MAIL_DATE" DATE
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_MAIL_LOG" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_MAIL_LOG" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_MAIL_LOG" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_MAIL_LOG" TO "TCMPL_APP_CONFIG";
