--------------------------------------------------------
--  DDL for Table OFB_COMMON_ACTIONS_MAPPING
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" 
   (	"COMMON_ACTION_ID" CHAR(5), 
	"ROLE_ID" CHAR(5), 
	"ACTION_ID" CHAR(5)
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" TO "TCMPL_APP_CONFIG";
