--------------------------------------------------------
--  DDL for Table OFB_COMMON_ACTIONS
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_COMMON_ACTIONS" 
   (	"COMMON_ACTION_ID" CHAR(5), 
	"COMMON_ACTION_DESC" VARCHAR2(200)
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_COMMON_ACTIONS" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_COMMON_ACTIONS" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_COMMON_ACTIONS" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_COMMON_ACTIONS" TO "TCMPL_APP_CONFIG";
