--------------------------------------------------------
--  DDL for Table OFB_EXIT_APPROVALS_LOG
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_EXIT_APPROVALS_LOG" 
   (	"EMPNO" CHAR(5), 
	"ACTION_ID" CHAR(5), 
	"IS_APPROVED" CHAR(2), 
	"REMARKS" VARCHAR2(200), 
	"APPROVED_BY" CHAR(5), 
	"MODIFIED_ON" DATE, 
	"KEY_ID" VARCHAR2(8)
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_EXIT_APPROVALS_LOG" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_EXIT_APPROVALS_LOG" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_EXIT_APPROVALS_LOG" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_EXIT_APPROVALS_LOG" TO "TCMPL_APP_CONFIG";
