--------------------------------------------------------
--  DDL for Table OFB_EXIT_APPROVAL_RESET_LOG
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_EXIT_APPROVAL_RESET_LOG" 
   (	"EMPNO" CHAR(5), 
	"ACTION_ID" CHAR(5), 
	"RESET_BY" CHAR(5), 
	"RESET_DATE" DATE
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_EXIT_APPROVAL_RESET_LOG" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_EXIT_APPROVAL_RESET_LOG" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_EXIT_APPROVAL_RESET_LOG" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_EXIT_APPROVAL_RESET_LOG" TO "TCMPL_APP_CONFIG";
