--------------------------------------------------------
--  DDL for Table OFB_EMP_EXIT_APPROVALS
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" 
   (	"EMPNO" CHAR(5), 
	"ACTION_ID" CHAR(5), 
	"REMARKS" VARCHAR2(200), 
	"IS_APPROVED" CHAR(2), 
	"APPROVAL_DATE" DATE, 
	"APPROVED_BY" CHAR(5), 
	"ROLE_ID" CHAR(5)
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_EMP_EXIT_APPROVALS" TO "TCMPL_APP_CONFIG";
