--------------------------------------------------------
--  DDL for Table OFB_ROLE_ACTIONS
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."OFB_ROLE_ACTIONS" 
   (	"ACTION_ID" CHAR(5), 
	"ROLE_ID" CHAR(5), 
	"ACTION_NAME" VARCHAR2(20), 
	"ACTION_DESC" VARCHAR2(200), 
	"IS_ACTION_FOR_HOD" CHAR(2), 
	"HOD_COSTCODE" CHAR(4), 
	"CHECKER_ACTION_ID" CHAR(5), 
	"GROUP_NAME" VARCHAR2(20), 
	"SORT_ORDER" NUMBER(2,0), 
	"GROUP_DESC" VARCHAR2(30)
   ) ;
  GRANT UPDATE ON "TCMPL_HR"."OFB_ROLE_ACTIONS" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."OFB_ROLE_ACTIONS" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."OFB_ROLE_ACTIONS" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."OFB_ROLE_ACTIONS" TO "TCMPL_APP_CONFIG";
