--------------------------------------------------------
--  DDL for Table VPP_GRADE_GROUP_MASTER
--------------------------------------------------------

  
  CREATE TABLE "TCMPL_HR"."VPP_GRADE_GROUP_MASTER" 
   (	"GRADE_GRP_ID" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"GRADE_GRP" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"INSURED_SUM_ID_FROM" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"INSURED_SUM_ID_TO" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "VPP_GRADE_GROUP_MASTER_PK" PRIMARY KEY ("GRADE_GRP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "VPP_GRADE_GROUP_MASTER_UK1" UNIQUE ("GRADE_GRP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "VPP_GRADE_GROUP_MASTER_FK1" FOREIGN KEY ("INSURED_SUM_ID_FROM")
	  REFERENCES "TCMPL_HR"."VPP_INSURED_SUM_MASTER" ("INSURED_SUM_ID") ENABLE, 
	 CONSTRAINT "VPP_GRADE_GROUP_MASTER_FK2" FOREIGN KEY ("INSURED_SUM_ID_TO")
	  REFERENCES "TCMPL_HR"."VPP_INSURED_SUM_MASTER" ("INSURED_SUM_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;


  GRANT UPDATE ON "TCMPL_HR"."VPP_GRADE_GROUP_MASTER" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."VPP_GRADE_GROUP_MASTER" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."VPP_GRADE_GROUP_MASTER" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."VPP_GRADE_GROUP_MASTER" TO "TCMPL_APP_CONFIG";
