--------------------------------------------------------
--  DDL for Table VPP_INSURED_SUM_MASTER
--------------------------------------------------------

 
  CREATE TABLE "TCMPL_HR"."VPP_INSURED_SUM_MASTER" 
   (	"INSURED_SUM_ID" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"INSURED_SUM_AMT" NUMBER(6,0) NOT NULL ENABLE, 
	"INSURED_SUM_WORDS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INSURED_SUM_CURRID" VARCHAR2(3 BYTE) DEFAULT 'INR' NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "VPP_INSURED_SUM_MASTER_PK" PRIMARY KEY ("INSURED_SUM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "VPP_INSURED_SUM_MASTER_UK1" UNIQUE ("INSURED_SUM_AMT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE, 
	 CONSTRAINT "VPP_INSURED_SUM_MASTER_UK2" UNIQUE ("INSURED_SUM_WORDS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;

   COMMENT ON COLUMN "TCMPL_HR"."VPP_INSURED_SUM_MASTER"."IS_ACTIVE" IS '0 or 1';


  GRANT UPDATE ON "TCMPL_HR"."VPP_INSURED_SUM_MASTER" TO "TCMPL_APP_CONFIG";
  GRANT SELECT ON "TCMPL_HR"."VPP_INSURED_SUM_MASTER" TO "TCMPL_APP_CONFIG";
  GRANT INSERT ON "TCMPL_HR"."VPP_INSURED_SUM_MASTER" TO "TCMPL_APP_CONFIG";
  GRANT DELETE ON "TCMPL_HR"."VPP_INSURED_SUM_MASTER" TO "TCMPL_APP_CONFIG";
