--------------------------------------------------------
--  DDL for Table VPP_PREMIUM_MASTER
--------------------------------------------------------

  CREATE TABLE "TCMPL_HR"."VPP_PREMIUM_MASTER" 
   (	"INSURED_SUM_ID" VARCHAR2(3 BYTE), 
	"PERSONS" NUMBER, 
	"PREMIUM" NUMBER, 
	"LACS" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPL_DATA" ;
REM INSERTING into TCMPL_HR.VPP_PREMIUM_MASTER
SET DEFINE OFF;
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I01',1,22002,'2');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I01',2,27706,'2');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I01',3,49708,'2');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I01',4,55412,'2');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I02',1,25885,'3');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I02',2,32596,'3');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I02',3,58481,'3');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I02',4,65192,'3');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I03',1,28473,'4');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I03',2,35855,'4');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I03',3,64328,'4');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I03',4,71710,'4');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I04',1,31321,'5');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I04',2,39441,'5');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I04',3,70762,'5');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I04',4,78882,'5');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I05',1,34453,'6');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I05',2,43385,'6');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I05',3,77838,'6');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I05',4,86770,'6');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I06',1,39620,'7');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I06',2,49892,'7');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I06',3,89512,'7');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I06',4,99784,'7');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I07',1,45564,'8');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I07',2,57377,'8');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I07',3,102941,'8');
Insert into TCMPL_HR.VPP_PREMIUM_MASTER (INSURED_SUM_ID,PERSONS,PREMIUM,LACS) values ('I07',4,114754,'8');
--------------------------------------------------------
--  Constraints for Table VPP_PREMIUM_MASTER
--------------------------------------------------------

  ALTER TABLE "TCMPL_HR"."VPP_PREMIUM_MASTER" MODIFY ("PREMIUM" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."VPP_PREMIUM_MASTER" MODIFY ("PERSONS" NOT NULL ENABLE);
  ALTER TABLE "TCMPL_HR"."VPP_PREMIUM_MASTER" MODIFY ("INSURED_SUM_ID" NOT NULL ENABLE);