--------------------------------------------------------
--  Ref Constraints for Table OFB_COMMON_ACTIONS_MAPPING
--------------------------------------------------------

  ALTER TABLE "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" ADD CONSTRAINT "OFB_COMMON_ACTIONS_MAPPIN_FK1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "TCMPL_HR"."OFB_ROLES" ("ROLE_ID") ENABLE;
  ALTER TABLE "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" ADD CONSTRAINT "OFB_COMMON_ACTIONS_MAPPIN_FK2" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "TCMPL_HR"."OFB_ROLE_ACTIONS" ("ACTION_ID") ENABLE;
  ALTER TABLE "TCMPL_HR"."OFB_COMMON_ACTIONS_MAPPING" ADD CONSTRAINT "OFB_COMMON_ACTIONS_MAPPIN_FK3" FOREIGN KEY ("COMMON_ACTION_ID")
	  REFERENCES "TCMPL_HR"."OFB_COMMON_ACTIONS" ("COMMON_ACTION_ID") ENABLE;
