--------------------------------------------------------
--  DDL for Procedure UPDATEMAX6
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "TIMECURR"."UPDATEMAX6" IS
BEGIN

DECLARE 	CURSOR 
        C_EMPS IS SELECT DISTINCT EMPNO FROM TMPANI;

    --REC_EMPS  TMPANI%ROWTYPE;
    REC_EMPS VARCHAR(5);
    BEGIN 
    	OPEN C_EMPS;
    	 LOOP
		    FETCH C_EMPS INTO REC_EMPS;
		    dbms_output.put_line(REC_EMPS);
		    /*
		   DECLARE  CURSOR C_EMPS1 IS SELECT * FROM  TMPANI WHERE EMPNO = REC_EMPS;
    		REC_EMPROJ TMPANI%ROWTYPE;     
		    EMPSUM  NUMBER(4):=0;
			
    		BEGIN
			   OPEN C_EMPS1 ;
			   LOOP
				  FETCH C_EMPS1 INTO REC_EMPROJ ;
			 	  EMPSUM := EMPSUM + REC_EMPROJ.D29;
				  IF EMPSUM < 6 THEN
				      	INSERT INTO TMPANI1(YYMM ,EMPNO ,PARENT,ASSIGN ,PROJNO,WPCODE,ACTIVITY, D1 ,D2 ,D3,D4 ,D5,D6, D7,D8,D9,d10,D11,D12,D13,D14,d15,D16,D17,D18,D19,D20,D21,D22,D23,D24,D25, D26, D27, D28, D29,D30,D31,TOTAL, GRP,COMPANY )
                VALUES(REC_EMPROJ.YYMM ,REC_EMPROJ.EMPNO ,REC_EMPROJ.PARENT,REC_EMPROJ.ASSIGN ,REC_EMPROJ.PROJNO,REC_EMPROJ.WPCODE,REC_EMPROJ.ACTIVITY, REC_EMPROJ.D1 ,REC_EMPROJ.D2 ,REC_EMPROJ.D3,REC_EMPROJ.D4 ,REC_EMPROJ.D5,REC_EMPROJ.D6, REC_EMPROJ.D7,REC_EMPROJ.D8,REC_EMPROJ.D9,REC_EMPROJ.d10,REC_EMPROJ.D11,REC_EMPROJ.D12,REC_EMPROJ.D13,REC_EMPROJ.D14,REC_EMPROJ.d15,REC_EMPROJ.D16,REC_EMPROJ.D17,REC_EMPROJ.D18,REC_EMPROJ.D19,REC_EMPROJ.D20,REC_EMPROJ.D21,REC_EMPROJ.D22,REC_EMPROJ.D23,REC_EMPROJ.D24,REC_EMPROJ.D25, REC_EMPROJ.D26, REC_EMPROJ.D27, REC_EMPROJ.D28, REC_EMPROJ.D29,REC_EMPROJ.D30,REC_EMPROJ.D31,REC_EMPROJ.TOTAL, REC_EMPROJ.GRP,REC_EMPROJ.COMPANY);
  				END IF;
		  	 END LOOP;
         CLOSE C_EMPS1;
		   END;
		   */
    	END LOOP;
    	
      CLOSE C_EMPS; 
  END;
END;

/
